#!/usr/bin/env python3
"""Expand a section from N pages to TARGET pages by generating new entries."""
import os, sys, re, random

TARGET = 150

SECTION_CONFIGS = {
    # ── Dev tools (currently 105, target 150) ──
    "poetry": {
        "dir": "tools/poetry",
        "fm": 'tools: ["poetry"]\nerror-types: ["tool-error"]',
        "topics": [
            ("install-global", "Poetry Global Install Error", "How to fix issues installing packages globally with Poetry"),
            ("cache-corrupt", "Poetry Cache Corrupted", "How to fix corrupted Poetry cache"),
            ("lock-hash", "Poetry Lock File Hash Mismatch", "How to fix lock file hash mismatch in Poetry"),
            ("script-entry", "Poetry Script Entry Not Found", "How to fix missing script entry points in Poetry"),
            ("plugin-conflict", "Poetry Plugin Conflict", "How to fix conflicting Poetry plugins"),
            ("env-python", "Poetry Environment Python Version Error", "How to fix Python version mismatch in Poetry environments"),
            ("dependency-group", "Poetry Dependency Group Error", "How to fix dependency group errors in Poetry"),
            ("extras-conflict", "Poetry Extras Conflict", "How to fix conflicting extras in Poetry"),
            ("source-priority", "Poetry Source Priority Error", "How to fix source priority configuration in Poetry"),
            ("publish-auth", "Poetry Publish Auth Error", "How to fix authentication errors when publishing with Poetry"),
            ("build-wheel", "Poetry Wheel Build Error", "How to fix wheel building errors in Poetry"),
            ("build-sdist", "Poetry SDist Build Error", "How to fix sdist build errors in Poetry"),
            ("readme-error", "Poetry Readme Not Found", "How to fix missing readme file errors in Poetry"),
            ("license-error", "Poetry License Field Missing", "How to fix missing license field in Poetry"),
            ("python-constraint", "Poetry Python Constraint Error", "How to fix Python version constraint errors in Poetry"),
            ("git-dependency", "Poetry Git Dependency Error", "How to fix git dependency errors in Poetry"),
            ("local-dependency", "Poetry Local Dependency Error", "How to fix local path dependency errors in Poetry"),
            ("url-dependency", "Poetry URL Dependency Error", "How to fix URL dependency errors in Poetry"),
            ("lock-stale", "Poetry Lock File Stale", "How to fix stale lock file errors in Poetry"),
            ("lock-regenerate", "Poetry Lock File Regeneration", "How to regenerate Poetry lock files"),
            ("upgrade-strategy", "Poetry Upgrade Strategy Error", "How to fix upgrade strategy errors in Poetry"),
            ("constraint-parsing", "Poetry Constraint Parsing Error", "How to fix dependency constraint parsing errors"),
            ("marker-parsing", "Poetry Marker Parsing Error", "How to fix environment marker parsing errors"),
            ("self-update", "Poetry Self Update Error", "How to fix Poetry self-update errors"),
            ("venv-manage", "Poetry Venv Management Error", "How to fix virtual environment management errors"),
            ("install-no-dev", "Poetry Install Without Dev Error", "How to fix install without dev dependencies errors"),
            ("sync-error", "Poetry Sync Error", "How to fix Poetry sync command errors"),
            ("system-venv", "Poetry System Venv Error", "How to fix system virtual environment errors"),
            ("config-local", "Poetry Local Config Error", "How to fix local configuration errors in Poetry"),
            ("certificate-verify", "Poetry Certificate Verify Error", "How to fix SSL certificate verification errors in Poetry"),
            ("retry-timeout", "Poetry Retry Timeout", "How to fix request retry timeout errors in Poetry"),
            ("checksum-mismatch", "Poetry Checksum Mismatch", "How to fix package checksum mismatch errors in Poetry"),
            ("empty-package", "Poetry Empty Package Error", "How to fix empty package errors in Poetry"),
            ("duplicate-class", "Poetry Duplicate Class Error", "How to fix duplicate class definition errors"),
            ("namespace-pkg", "Poetry Namespace Package Error", "How to fix namespace package errors in Poetry"),
            ("entry-points", "Poetry Entry Points Error", "How to fix entry points configuration errors"),
            ("build-system", "Poetry Build System Error", "How to fix build system requirement errors"),
            ("requires-python", "Poetry Requires Python Error", "How to fix requires-python field errors"),
            ("authors-field", "Poetry Authors Field Error", "How to fix authors field errors in Poetry"),
            ("homepage-field", "Poetry Homepage Field Error", "How to fix homepage URL field errors"),
            ("repository-field", "Poetry Repository Field Error", "How to fix repository URL field errors"),
            ("documentation-field", "Poetry Documentation Field Error", "How to fix documentation URL field errors"),
            ("keywords-field", "Poetry Keywords Field Error", "How to fix keywords field errors"),
            ("classifiers-field", "Poetry Classifiers Field Error", "How to fix Trove classifiers field errors"),
            ("include-exclude", "Poetry Include Exclude Error", "How to fix include/exclude patterns in Poetry"),
        ]
    },
    "conda": {
        "dir": "tools/conda",
        "fm": 'tools: ["conda"]\nerror-types: ["tool-error"]',
        "topics": [
            ("conda-http-error", "Conda HTTP Error", "How to fix HTTP download errors in Conda"),
            ("conda-ssl-error", "Conda SSL Error", "How to fix SSL certificate errors in Conda"),
            ("conda-permission-denied", "Conda Permission Denied", "How to fix permission denied errors in Conda"),
            ("conda-env-create", "Conda Env Create Error", "How to fix environment creation errors in Conda"),
            ("conda-env-remove", "Conda Env Remove Error", "How to fix environment removal errors in Conda"),
            ("conda-env-export", "Conda Env Export Error", "How to fix environment export errors in Conda"),
            ("conda-env-import", "Conda Env Import Error", "How to fix environment import errors in Conda"),
            ("conda-channel-priority", "Conda Channel Priority Error", "How to fix channel priority conflicts in Conda"),
            ("conda-condarc-parse", "Conda Condarc Parse Error", "How to fix .condarc configuration parsing errors"),
            ("conda-condarc-not-found", "Conda Condarc Not Found", "How to fix missing .condarc file errors"),
            ("conda-offline-mode", "Conda Offline Mode Error", "How to fix offline mode errors in Conda"),
            ("conda-proxy-config", "Conda Proxy Config Error", "How to fix proxy configuration errors in Conda"),
            ("conda-verify", "Conda Verify Error", "How to fix package verification errors in Conda"),
            ("conda-clean", "Conda Clean Error", "How to fix package cache cleaning errors"),
            ("conda-update-conda", "Conda Update Error", "How to fix Conda itself update errors"),
            ("conda-pin-package", "Conda Package Pin Error", "How to fix package pinning errors in Conda"),
            ("conda-export-yml", "Conda Export YAML Error", "How to fix environment YAML export errors"),
            ("conda-import-yml", "Conda Import YAML Error", "How to fix environment YAML import errors"),
            ("conda-list-error", "Conda List Error", "How to fix package listing errors in Conda"),
            ("conda-search-error", "Conda Search Error", "How to fix package search errors in Conda"),
            ("conda-info-error", "Conda Info Error", "How to fix Conda system info display errors"),
            ("conda-config-error", "Conda Config Error", "How to fix Conda configuration setting errors"),
            ("conda-run-error", "Conda Run Error", "How to fix conda run command errors"),
            ("conda-execute-error", "Conda Execute Error", "How to fix conda execute errors"),
            ("conda-develop-error", "Conda Develop Error", "How to fix conda develop mode errors"),
            ("conda-metapackage", "Conda Metapackage Error", "How to fix metapackage installation errors"),
            ("conda-features", "Conda Features Error", "How to fix Conda features/track features errors"),
            ("conda-variant", "Conda Variant Error", "How to fix Conda variant configuration errors"),
            ("conda-build-number", "Conda Build Number Error", "How to fix build number errors in Conda"),
            ("conda-noarch", "Conda Noarch Error", "How to fix noarch package errors in Conda"),
            ("conda-constructor", "Conda Constructor Error", "How to fix Conda constructor installer errors"),
            ("conda-menuinst", "Conda Menuinst Error", "How to fix menu shortcut installation errors"),
            ("conda-copy-error", "Conda Environment Copy Error", "How to fix conda environment cloning errors"),
            ("conda-clone-error", "Conda Env Clone Error", "How to fix conda env clone errors"),
            ("conda-rename-error", "Conda Environment Rename Error", "How to fix conda environment renaming errors"),
            ("conda-backup-error", "Conda Environment Backup Error", "How to back up Conda environments"),
            ("conda-restore-error", "Conda Environment Restore Error", "How to restore Conda environments from backup"),
            ("conda-cross-platform", "Conda Cross Platform Error", "How to fix cross-platform environment errors"),
            ("conda-linux-windows", "Conda Linux Windows Compatibility", "How to fix Linux-Windows environment compatibility"),
            ("conda-migration", "Conda Environment Migration Error", "How to migrate Conda environments between systems"),
            ("conda-revision", "Conda Revision Error", "How to fix Conda environment revision errors"),
            ("conda-history", "Conda History Error", "How to view Conda environment revision history"),
            ("conda-revert", "Conda Revert Error", "How to revert Conda environment changes"),
            ("conda-compare", "Conda Compare Error", "How to compare Conda environments"),
            ("conda-diff", "Conda Environment Diff Error", "How to diff Conda environments"),
        ]
    },
    "pip": {
        "dir": "tools/pip",
        "fm": 'tools: ["pip"]\nerror-types: ["tool-error"]',
        "topics": [
            ("pip-ssl-certificate", "Pip SSL Certificate Error", "How to fix SSL certificate errors in pip"),
            ("pip-connection-timeout", "Pip Connection Timeout", "How to fix connection timeout errors in pip"),
            ("pip-proxy-authentication", "Pip Proxy Auth Error", "How to fix proxy authentication errors in pip"),
            ("pip-invalid-requirement", "Pip Invalid Requirement Error", "How to fix invalid requirement string errors in pip"),
            ("pip-conflicts-with", "Pip Conflicts With Error", "How to fix dependency conflict errors in pip"),
            ("pip-distutils-installed", "Pip Distutils Installed Error", "How to fix distutils installed package conflicts"),
            ("pip-egg-info", "Pip Egg Info Error", "How to fix egg info generation errors in pip"),
            ("pip-bdist-wheel", "Pip Bdist Wheel Error", "How to fix binary wheel building errors in pip"),
            ("pip-setup-bdist", "Pip Setup Bdist Error", "How to fix setup.py bdist errors in pip"),
            ("pip-install-option", "Pip Install Option Error", "How to fix pip install option parsing errors"),
            ("pip-find-links", "Pip Find Links Error", "How to fix find-links option errors in pip"),
            ("pip-extra-index", "Pip Extra Index URL Error", "How to fix extra index URL errors in pip"),
            ("pip-trusted-host", "Pip Trusted Host Error", "How to fix trusted host configuration errors"),
            ("pip-client-cert", "Pip Client Certificate Error", "How to fix client certificate errors in pip"),
            ("pip-timeout-option", "Pip Timeout Option Error", "How to fix timeout option errors in pip"),
            ("pip-no-index", "Pip No Index Error", "How to fix no-index mode errors in pip"),
            ("pip-download-cache", "Pip Download Cache Error", "How to fix download cache errors in pip"),
            ("pip-wheel-dir", "Pip Wheel Directory Error", "How to fix wheel directory errors in pip"),
            ("pip-no-build-isolation", "Pip No Build Isolation Error", "How to fix build isolation errors in pip"),
            ("pip-use-pep517", "Pip Use Pep517 Error", "How to fix PEP 517 build errors in pip"),
            ("pip-target-dir", "Pip Target Directory Error", "How to fix target directory errors in pip"),
            ("pip-user-install", "Pip User Install Error", "How to fix user install errors in pip"),
            ("pip-prefix-path", "Pip Prefix Path Error", "How to fix prefix path errors in pip"),
            ("pip-root-error", "Pip Root Error", "How to fix pip root user warning errors"),
            ("pip-ignore-installed", "Pip Ignore Installed Error", "How to fix ignore-installed mode errors"),
            ("pip-force-reinstall", "Pip Force Reinstall Error", "How to fix force reinstall errors in pip"),
            ("pip-upgrade-strategy", "Pip Upgrade Strategy Error", "How to fix upgrade strategy option errors"),
            ("pip-dry-run", "Pip Dry Run Error", "How to fix pip dry run mode errors"),
            ("pip-compile-error", "Pip Compile Error", "How to fix pip compile errors (pip-tools)"),
            ("pip-sync-error", "Pip Sync Error", "How to fix pip sync errors (pip-tools)"),
            ("pip-requirements-file", "Pip Requirements File Error", "How to fix requirements file parsing errors"),
            ("pip-constraints-file", "Pip Constraints File Error", "How to fix constraints file errors in pip"),
            ("pip-editable-install", "Pip Editable Install Error", "How to fix editable install errors in pip"),
            ("pip-vcs-install", "Pip VCS Install Error", "How to fix VCS install errors in pip"),
            ("pip-bzr-error", "Pip Bzr Error", "How to fix Bazaar VCS errors in pip"),
            ("pip-svn-error", "Pip SVN Error", "How to fix Subversion VCS errors in pip"),
            ("pip-hg-error", "Pip Mercurial Error", "How to fix Mercurial VCS errors in pip"),
            ("pip-check-error", "Pip Check Error", "How to fix pip check dependency verification errors"),
            ("pip-list-error", "Pip List Error", "How to fix pip list command errors"),
            ("pip-show-error", "Pip Show Error", "How to fix pip show package info errors"),
            ("pip-freeze-error", "Pip Freeze Error", "How to fix pip freeze output errors"),
            ("pip-json-error", "Pip JSON Output Error", "How to fix pip JSON format errors"),
            ("pip-warning-error", "Pip Warnings Error", "How to fix pip deprecation warning errors"),
            ("pip-log-error", "Pip Log File Error", "How to fix pip log file errors"),
            ("pip-debug-error", "Pip Debug Mode Error", "How to fix pip debug mode errors"),
        ]
    },
    "cargo": {
        "dir": "tools/cargo",
        "fm": 'tools: ["cargo"]\nerror-types: ["tool-error"]',
        "topics": [
            ("cargo-registry-auth", "Cargo Registry Auth Error", "How to fix registry authentication errors in Cargo"),
            ("cargo-git-checkout", "Cargo Git Checkout Error", "How to fix git dependency checkout errors in Cargo"),
            ("cargo-patch-error", "Cargo Patch Error", "How to fix Cargo patch configuration errors"),
            ("cargo-profile-error", "Cargo Profile Error", "How to fix Cargo profile configuration errors"),
            ("cargo-feature-error", "Cargo Feature Error", "How to fix Cargo feature flag errors"),
            ("cargo-target-error", "Cargo Target Error", "How to fix Cargo target specification errors"),
            ("cargo-workspace-error", "Cargo Workspace Error", "How to fix Cargo workspace member errors"),
            ("cargo-exclude-error", "Cargo Exclude Error", "How to fix Cargo exclude pattern errors"),
            ("cargo-license-error", "Cargo License Error", "How to fix Cargo license field errors"),
            ("cargo-edition-error", "Cargo Edition Error", "How to fix Cargo edition field errors"),
            ("cargo-metadata-error", "Cargo Metadata Error", "How to fix Cargo metadata generation errors"),
            ("cargo-doc-error", "Cargo Doc Error", "How to fix cargo doc documentation generation errors"),
            ("cargo-test-name", "Cargo Test Name Error", "How to fix cargo test filter errors"),
            ("cargo-bench-error", "Cargo Bench Error", "How to fix cargo benchmark errors"),
            ("cargo-check-error", "Cargo Check Error", "How to fix cargo check analysis errors"),
            ("cargo-clippy-error", "Cargo Clippy Error", "How to fix cargo clippy lint errors"),
            ("cargo-fmt-error", "Cargo Fmt Error", "How to fix cargo fmt formatting errors"),
            ("cargo-fix-error", "Cargo Fix Error", "How to fix cargo fix auto correction errors"),
            ("cargo-flamegraph", "Cargo Flamegraph Error", "How to fix cargo flamegraph profiling errors"),
            ("cargo-audit-error", "Cargo Audit Error", "How to fix cargo audit security vulnerability errors"),
            ("cargo-outdated-error", "Cargo Outdated Error", "How to fix cargo outdated dependency check errors"),
            ("cargo-tree-error", "Cargo Tree Error", "How to fix cargo tree dependency visualization errors"),
            ("cargo-deny-error", "Cargo Deny Error", "How to fix cargo deny policy errors"),
            ("cargo-vendor-error", "Cargo Vendor Error", "How to fix cargo vendor dependency caching errors"),
            ("cargo-pkgid-error", "Cargo Package ID Error", "How to fix cargo package ID specification errors"),
            ("cargo-manifest-path", "Cargo Manifest Path Error", "How to fix cargo manifest-path flag errors"),
            ("cargo-locked-error", "Cargo Locked Error", "How to fix cargo locked mode errors"),
            ("cargo-frozen-error", "Cargo Frozen Error", "How to fix cargo frozen mode errors"),
            ("cargo-offline-error", "Cargo Offline Error", "How to fix cargo offline mode errors"),
            ("cargo-dry-run", "Cargo Dry Run Error", "How to fix cargo dry run mode errors"),
            ("cargo-message-format", "Cargo Message Format Error", "How to fix cargo message-format errors"),
            ("cargo-color-error", "Cargo Color Error", "How to fix cargo color output errors"),
            ("cargo-jobs-error", "Cargo Jobs Error", "How to fix cargo jobs parallel build errors"),
            ("cargo-timings-error", "Cargo Timings Error", "How to fix cargo timings report errors"),
            ("cargo-future-incompat", "Cargo Future Incompat Error", "How to fix cargo future incompatibility warnings"),
            ("cargo-config-env", "Cargo Config Env Error", "How to fix Cargo environment variable config errors"),
            ("cargo-config-toml", "Cargo Config Toml Error", "How to fix Cargo config.toml parsing errors"),
            ("cargo-http-timeout", "Cargo HTTP Timeout Error", "How to fix Cargo HTTP request timeout errors"),
            ("cargo-low-speed-limit", "Cargo Low Speed Limit Error", "How to fix Cargo low speed download limit errors"),
            ("cargo-multiplexing", "Cargo Multiplexing Error", "How to fix Cargo HTTP multiplexing errors"),
            ("cargo-crate-type", "Cargo Crate Type Error", "How to fix Cargo crate type configuration errors"),
            ("cargo-path-dependency", "Cargo Path Dependency Error", "How to fix Cargo path dependency resolution errors"),
            ("cargo-alt-registry", "Cargo Alternative Registry Error", "How to fix Cargo alternative registry errors"),
            ("cargo-publish-dry-run", "Cargo Publish Dry Run Error", "How to fix cargo publish dry-run errors"),
            ("cargo-verify-error", "Cargo Verify Error", "How to fix cargo package verification errors"),
        ]
    },
    "brew": {
        "dir": "tools/brew",
        "fm": 'tools: ["brew"]\nerror-types: ["tool-error"]',
        "topics": [
            ("brew-formula-not-found", "Brew Formula Not Found", "How to fix formula not found errors in Homebrew"),
            ("brew-tap-error", "Brew Tap Error", "How to fix Homebrew tap errors"),
            ("brew-cask-error", "Brew Cask Error", "How to fix Homebrew cask installation errors"),
            ("brew-bottle-error", "Brew Bottle Error", "How to fix Homebrew bottle installation errors"),
            ("brew-keg-error", "Brew Keg Error", "How to fix Homebrew keg linking errors"),
            ("brew-cellars-error", "Brew Cellars Error", "How to fix Homebrew cellars directory errors"),
            ("brew-cellar-not-found", "Brew Cellar Not Found", "How to fix missing Homebrew cellar errors"),
            ("brew-link-error", "Brew Link Error", "How to fix Homebrew link step errors"),
            ("brew-unlink-error", "Brew Unlink Error", "How to fix Homebrew unlink errors"),
            ("brew-pin-error", "Brew Pin Error", "How to fix Homebrew package pinning errors"),
            ("brew-unpin-error", "Brew Unpin Error", "How to fix Homebrew package unpin errors"),
            ("brew-outdated-error", "Brew Outdated Error", "How to fix Homebrew outdated package errors"),
            ("brew-upgrade-all", "Brew Upgrade All Error", "How to fix brew upgrade --all errors"),
            ("brew-deps-error", "Brew Dependencies Error", "How to fix Homebrew dependency resolution errors"),
            ("brew-desc-error", "Brew Desc Error", "How to fix Homebrew description lookup errors"),
            ("brew-info-error", "Brew Info Error", "How to fix Homebrew formula info display errors"),
            ("brew-home-error", "Brew Home Error", "How to fix Homebrew home URL opening errors"),
            ("brew-log-error", "Brew Log Error", "How to fix Homebrew log display errors"),
            ("brew-options-error", "Brew Options Error", "How to fix Homebrew formula option errors"),
            ("brew-uses-error", "Brew Uses Error", "How to fix Homebrew reverse dependency errors"),
            ("brew-deps-tree", "Brew Deps Tree Error", "How to fix Homebrew dependency tree errors"),
            ("brew-cat-error", "Brew Cat Error", "How to fix Homebrew formula display errors"),
            ("brew-edit-error", "Brew Edit Error", "How to fix Homebrew formula editing errors"),
            ("brew-create-error", "Brew Create Error", "How to fix Homebrew formula creation errors"),
            ("brew-extract-error", "Brew Extract Error", "How to fix Homebrew formula extraction errors"),
            ("brew-merge-error", "Brew Merge Error", "How to fix Homebrew formula merge errors"),
            ("brew-bump-error", "Brew Bump Error", "How to fix Homebrew version bump errors"),
            ("brew-release-error", "Brew Release Error", "How to fix Homebrew formula release errors"),
            ("brew-pr-upload", "Brew PR Upload Error", "How to fix Homebrew PR upload errors"),
            ("brew-pr-pull", "Brew PR Pull Error", "How to fix Homebrew PR pull errors"),
            ("brew-contributions", "Brew Contributions Error", "How to fix Homebrew contribution tracking errors"),
            ("brew-update-reset", "Brew Update Reset Error", "How to fix Homebrew update reset errors"),
            ("brew-upgrade-curl", "Brew Upgrade Curl Error", "How to fix Homebrew curl download errors"),
            ("brew-unpack-error", "Brew Unpack Error", "How to fix Homebrew source unpack errors"),
            ("brew-post-install", "Brew Post Install Error", "How to fix Homebrew post-install script errors"),
            ("brew-caveats-error", "Brew Caveats Error", "How to fix Homebrew caveats display errors"),
            ("brew-analytics-error", "Brew Analytics Error", "How to fix Homebrew analytics errors"),
            ("brew-autoremove", "Brew Autoremove Error", "How to fix Homebrew autoremove errors"),
            ("brew-missing-deps", "Brew Missing Deps Error", "How to fix Homebrew missing dependency errors"),
            ("brew-required-deps", "Brew Required Deps Error", "How to fix Homebrew required dependency errors"),
            ("brew-recommended-deps", "Brew Recommended Deps Error", "How to fix Homebrew recommended dependency errors"),
            ("brew-optional-deps", "Brew Optional Deps Error", "How to fix Homebrew optional dependency errors"),
            ("brew-build-deps", "Brew Build Deps Error", "How to fix Homebrew build dependency errors"),
            ("brew-test-deps", "Brew Test Deps Error", "How to fix Homebrew test dependency errors"),
            ("brew-conflicts-error", "Brew Conflicts Error", "How to fix Homebrew formula conflict errors"),
        ]
    },
    "helm": {
        "dir": "tools/helm",
        "fm": 'tools: ["helm"]\nerror-types: ["tool-error"]',
        "topics": [
            ("helm-repo-index", "Helm Repo Index Error", "How to fix Helm repository index errors"),
            ("helm-repo-update-fail", "Helm Repo Update Failed", "How to fix Helm repo update failures"),
            ("helm-chart-download", "Helm Chart Download Error", "How to fix Helm chart download errors"),
            ("helm-chart-verify", "Helm Chart Verify Error", "How to fix Helm chart verification errors"),
            ("helm-chart-save", "Helm Chart Save Error", "How to fix Helm chart save errors"),
            ("helm-chart-export", "Helm Chart Export Error", "How to fix Helm chart export errors"),
            ("helm-template-error", "Helm Template Error", "How to fix Helm template rendering errors"),
            ("helm-lint-error", "Helm Lint Error", "How to fix Helm lint validation errors"),
            ("helm-dependency-list", "Helm Dependency List Error", "How to fix Helm dependency listing errors"),
            ("helm-dependency-update", "Helm Dependency Update Error", "How to fix Helm dependency update errors"),
            ("helm-dependency-build", "Helm Dependency Build Error", "How to fix Helm dependency build errors"),
            ("helm-repo-add", "Helm Repo Add Error", "How to fix Helm repo add errors"),
            ("helm-repo-remove", "Helm Repo Remove Error", "How to fix Helm repo remove errors"),
            ("helm-repo-list", "Helm Repo List Error", "How to fix Helm repo list errors"),
            ("helm-search-hub", "Helm Search Hub Error", "How to fix Helm search hub errors"),
            ("helm-search-repo", "Helm Search Repo Error", "How to fix Helm search repo errors"),
            ("helm-show-chart", "Helm Show Chart Error", "How to fix Helm show chart errors"),
            ("helm-show-readme", "Helm Show Readme Error", "How to fix Helm show readme errors"),
            ("helm-show-values", "Helm Show Values Error", "How to fix Helm show values errors"),
            ("helm-show-crds", "Helm Show CRDs Error", "How to fix Helm show CRDs errors"),
            ("helm-pull-error", "Helm Pull Error", "How to fix Helm pull command errors"),
            ("helm-push-error", "Helm Push Error", "How to fix Helm push command errors"),
            ("helm-package-error", "Helm Package Error", "How to fix Helm package command errors"),
            ("helm-sign-error", "Helm Sign Error", "How to fix Helm chart signing errors"),
            ("helm-provenance-error", "Helm Provenance Error", "How to fix Helm provenance verification errors"),
            ("helm-key-error", "Helm Key Error", "How to fix Helm GPG key errors"),
            ("helm-get-all", "Helm Get All Error", "How to fix Helm get all errors"),
            ("helm-get-values", "Helm Get Values Error", "How to fix Helm get values errors"),
            ("helm-get-manifest", "Helm Get Manifest Error", "How to fix Helm get manifest errors"),
            ("helm-get-hooks", "Helm Get Hooks Error", "How to fix Helm get hooks errors"),
            ("helm-get-notes", "Helm Get Notes Error", "How to fix Helm get notes errors"),
            ("helm-status-error", "Helm Status Error", "How to fix Helm status command errors"),
            ("helm-history-error", "Helm History Error", "How to fix Helm history command errors"),
            ("helm-rollback-error", "Helm Rollback Error", "How to fix Helm rollback command errors"),
            ("helm-upgrade-force", "Helm Upgrade Force Error", "How to fix Helm upgrade force errors"),
            ("helm-upgrade-recreate", "Helm Upgrade Recreate Error", "How to fix Helm upgrade recreate errors"),
            ("helm-upgrade-cleanup", "Helm Upgrade Cleanup Error", "How to fix Helm upgrade cleanup on fail errors"),
            ("helm-upgrade-max-history", "Helm Upgrade Max History Error", "How to fix Helm max history errors"),
            ("helm-uninstall-keep", "Helm Uninstall Keep History", "How to fix Helm uninstall keep history errors"),
            ("helm-plugin-install", "Helm Plugin Install Error", "How to fix Helm plugin installation errors"),
            ("helm-plugin-update", "Helm Plugin Update Error", "How to fix Helm plugin update errors"),
            ("helm-plugin-list", "Helm Plugin List Error", "How to fix Helm plugin list errors"),
            ("helm-plugin-uninstall", "Helm Plugin Uninstall Error", "How to fix Helm plugin uninstall errors"),
            ("helm-version-error", "Helm Version Error", "How to fix Helm version display errors"),
            ("helm-completion-error", "Helm Completion Error", "How to fix Helm shell completion errors"),
        ]
    },
    "kubectl": {
        "dir": "tools/kubectl",
        "fm": 'tools: ["kubectl"]\nerror-types: ["tool-error"]',
        "topics": [
            ("kubectl-apply-dry-run", "Kubectl Apply Dry Run Error", "How to fix kubectl apply dry-run errors"),
            ("kubectl-apply-prune", "Kubectl Apply Prune Error", "How to fix kubectl apply prune errors"),
            ("kubectl-apply-force", "Kubectl Apply Force Error", "How to fix kubectl apply force conflicts errors"),
            ("kubectl-apply-server-side", "Kubectl Apply Server Side Error", "How to fix kubectl server-side apply errors"),
            ("kubectl-apply-field-manager", "Kubectl Apply Field Manager Error", "How to fix kubectl field manager conflict errors"),
            ("kubectl-delete-grace", "Kubectl Delete Grace Period Error", "How to fix kubectl delete grace period errors"),
            ("kubectl-delete-cascade", "Kubectl Delete Cascade Error", "How to fix kubectl delete cascade errors"),
            ("kubectl-delete-orphan", "Kubectl Delete Orphan Error", "How to fix kubectl delete orphan errors"),
            ("kubectl-delete-propagation", "Kubectl Delete Propagation Error", "How to fix kubectl delete propagation policy errors"),
            ("kubectl-delete-dry-run", "Kubectl Delete Dry Run Error", "How to fix kubectl delete dry-run errors"),
            ("kubectl-get-watch", "Kubectl Get Watch Error", "How to fix kubectl get watch errors"),
            ("kubectl-get-output", "Kubectl Get Output Error", "How to fix kubectl get output format errors"),
            ("kubectl-get-label", "Kubectl Get Label Selector Error", "How to fix kubectl get label selector errors"),
            ("kubectl-get-field", "Kubectl Get Field Selector Error", "How to fix kubectl get field selector errors"),
            ("kubectl-get-chunk", "Kubectl Get Chunk Size Error", "How to fix kubectl get chunk size errors"),
            ("kubectl-describe-error", "Kubectl Describe Error", "How to fix kubectl describe errors"),
            ("kubectl-logs-pod", "Kubectl Logs Pod Error", "How to fix kubectl logs pod selection errors"),
            ("kubectl-logs-container", "Kubectl Logs Container Error", "How to fix kubectl logs container selection errors"),
            ("kubectl-logs-follow", "Kubectl Logs Follow Error", "How to fix kubectl logs follow errors"),
            ("kubectl-logs-tail", "Kubectl Logs Tail Error", "How to fix kubectl logs tail line count errors"),
            ("kubectl-logs-since", "Kubectl Logs Since Error", "How to fix kubectl logs since time errors"),
            ("kubectl-exec-error", "Kubectl Exec Error", "How to fix kubectl exec command errors"),
            ("kubectl-exec-stdin", "Kubectl Exec Stdin Error", "How to fix kubectl exec stdin errors"),
            ("kubectl-exec-tty", "Kubectl Exec TTY Error", "How to fix kubectl exec TTY allocation errors"),
            ("kubectl-port-forward", "Kubectl Port Forward Error", "How to fix kubectl port-forward errors"),
            ("kubectl-port-forward-address", "Kubectl Port Forward Address Error", "How to fix kubectl port-forward address binding errors"),
            ("kubectl-proxy-error", "Kubectl Proxy Error", "How to fix kubectl proxy errors"),
            ("kubectl-proxy-address", "Kubectl Proxy Address Error", "How to fix kubectl proxy address binding errors"),
            ("kubectl-proxy-accept", "Kubectl Proxy Accept Hosts Error", "How to fix kubectl proxy accept hosts regex errors"),
            ("kubectl-proxy-reject", "Kubectl Proxy Reject Methods Error", "How to fix kubectl proxy reject methods errors"),
            ("kubectl-cp-error", "Kubectl Copy Error", "How to fix kubectl cp file copy errors"),
            ("kubectl-cp-container", "Kubectl Copy Container Error", "How to fix kubectl cp container path errors"),
            ("kubectl-cp-retry", "Kubectl Copy Retry Error", "How to fix kubectl cp retry errors"),
            ("kubectl-top-node", "Kubectl Top Node Error", "How to fix kubectl top node resource metrics errors"),
            ("kubectl-top-pod", "Kubectl Top Pod Error", "How to fix kubectl top pod resource metrics errors"),
            ("kubectl-top-container", "Kubectl Top Container Error", "How to fix kubectl top container errors"),
            ("kubectl-api-resources", "Kubectl API Resources Error", "How to fix kubectl api-resources errors"),
            ("kubectl-api-versions", "Kubectl API Versions Error", "How to fix kubectl api-versions errors"),
            ("kubectl-explain-error", "Kubectl Explain Error", "How to fix kubectl explain field documentation errors"),
            ("kubectl-version-error", "Kubectl Version Error", "How to fix kubectl version display errors"),
            ("kubectl-cluster-info", "Kubectl Cluster Info Error", "How to fix kubectl cluster-info errors"),
            ("kubectl-config-view", "Kubectl Config View Error", "How to fix kubectl config view errors"),
            ("kubectl-config-current", "Kubectl Config Current Context Error", "How to fix kubectl config current-context errors"),
            ("kubectl-config-use", "Kubectl Config Use Context Error", "How to fix kubectl config use-context errors"),
            ("kubectl-config-cluster", "Kubectl Config Cluster Error", "How to fix kubectl config set-cluster errors"),
        ]
    },
    "stripe": {
        "dir": "tools/stripe",
        "fm": 'tools: ["stripe"]\nerror-types: ["tool-error"]',
        "topics": [
            ("stripe-invalid-request", "Stripe Invalid Request Error", "How to fix Stripe invalid request errors"),
            ("stripe-authentication", "Stripe Authentication Error", "How to fix Stripe API key authentication errors"),
            ("stripe-rate-limit", "Stripe Rate Limit Error", "How to fix Stripe rate limit exceeded errors"),
            ("stripe-idempotency", "Stripe Idempotency Error", "How to fix Stripe idempotency key errors"),
            ("stripe-expand-error", "Stripe Expand Error", "How to fix Stripe expand object errors"),
            ("stripe-list-error", "Stripe List Error", "How to fix Stripe list pagination errors"),
            ("stripe-search-error", "Stripe Search Error", "How to fix Stripe search API errors"),
            ("stripe-webhook-signature", "Stripe Webhook Signature Error", "How to fix Stripe webhook signature verification errors"),
            ("stripe-webhook-payload", "Stripe Webhook Payload Error", "How to fix Stripe webhook payload parsing errors"),
            ("stripe-webhook-endpoint", "Stripe Webhook Endpoint Error", "How to fix Stripe webhook endpoint configuration errors"),
            ("stripe-checkout-session", "Stripe Checkout Session Error", "How to fix Stripe Checkout Session creation errors"),
            ("stripe-payment-intent", "Stripe Payment Intent Error", "How to fix Stripe Payment Intent errors"),
            ("stripe-payment-method", "Stripe Payment Method Error", "How to fix Stripe payment method errors"),
            ("stripe-setup-intent", "Stripe Setup Intent Error", "How to fix Stripe Setup Intent errors"),
            ("stripe-subscription-create", "Stripe Subscription Create Error", "How to fix Stripe subscription creation errors"),
            ("stripe-subscription-update", "Stripe Subscription Update Error", "How to fix Stripe subscription update errors"),
            ("stripe-subscription-cancel", "Stripe Subscription Cancel Error", "How to fix Stripe subscription cancellation errors"),
            ("stripe-invoice-create", "Stripe Invoice Create Error", "How to fix Stripe invoice creation errors"),
            ("stripe-invoice-pay", "Stripe Invoice Pay Error", "How to fix Stripe invoice payment errors"),
            ("stripe-invoice-finalize", "Stripe Invoice Finalize Error", "How to fix Stripe invoice finalization errors"),
            ("stripe-refund-error", "Stripe Refund Error", "How to fix Stripe refund processing errors"),
            ("stripe-dispute-error", "Stripe Dispute Error", "How to fix Stripe dispute handling errors"),
            ("stripe-transfer-error", "Stripe Transfer Error", "How to fix Stripe transfer errors"),
            ("stripe-reversal-error", "Stripe Reversal Error", "How to fix Stripe transfer reversal errors"),
            ("stripe-payout-error", "Stripe Payout Error", "How to fix Stripe payout errors"),
            ("stripe-balance-error", "Stripe Balance Error", "How to fix Stripe balance lookup errors"),
            ("stripe-customer-create", "Stripe Customer Create Error", "How to fix Stripe customer creation errors"),
            ("stripe-customer-update", "Stripe Customer Update Error", "How to fix Stripe customer update errors"),
            ("stripe-customer-delete", "Stripe Customer Delete Error", "How to fix Stripe customer deletion errors"),
            ("stripe-tax-id", "Stripe Tax ID Error", "How to fix Stripe tax ID validation errors"),
            ("stripe-source-error", "Stripe Source Error", "How to fix Stripe source object errors"),
            ("stripe-token-error", "Stripe Token Error", "How to fix Stripe token creation errors"),
            ("stripe-card-error", "Stripe Card Error", "How to fix Stripe card processing errors"),
            ("stripe-bank-account", "Stripe Bank Account Error", "How to fix Stripe bank account errors"),
            ("stripe-currency-error", "Stripe Currency Error", "How to fix Stripe currency code errors"),
            ("stripe-amount-error", "Stripe Amount Error", "How to fix Stripe amount calculation errors"),
            ("stripe-metadata-error", "Stripe Metadata Error", "How to fix Stripe metadata validation errors"),
            ("stripe-description-error", "Stripe Description Error", "How to fix Stripe description field errors"),
            ("stripe-statement-descriptor", "Stripe Statement Descriptor Error", "How to fix Stripe statement descriptor errors"),
            ("stripe-receipt-email", "Stripe Receipt Email Error", "How to fix Stripe receipt email errors"),
            ("stripe-shipping-error", "Stripe Shipping Error", "How to fix Stripe shipping information errors"),
            ("stripe-address-error", "Stripe Address Error", "How to fix Stripe address validation errors"),
            ("stripe-phone-error", "Stripe Phone Error", "How to fix Stripe phone number errors"),
            ("stripe-file-upload", "Stripe File Upload Error", "How to fix Stripe file upload errors"),
            ("stripe-ephemeral-key", "Stripe Ephemeral Key Error", "How to fix Stripe ephemeral key errors"),
        ]
    },
}

# ── Template body ──
def make_body(topic, section_name):
    """Generate a page body from a topic tuple."""
    slug, title, desc = topic
    
    causes = f"- Incorrect configuration or syntax\n- Missing required {section_name} dependencies\n- Environment or network issues\n- Version incompatibility"
    fix_cmd = f"# Check version\n{section_name} --version\n\n# Verify configuration\n{section_name} config --list"
    example = f"$ {section_name} diagnose\n# Common solutions:\n# 1. Check documentation\n# 2. Update to latest version\n# 3. Verify environment variables"
    
    lines = [
        f"## Common Causes\n",
        f"{causes}\n",
        f"## How to Fix\n",
        f"1. **Identify the root cause** - Check logs and error output\n",
        f"2. **Verify configuration** - Ensure settings are correct\n",
        f"3. **Update dependencies** - Make sure all required packages are installed\n",
        f"4. **Test the solution** - Run validation commands\n",
        f"5. **Monitor for recurrence** - Watch for the same error\n",
        f"\n```bash\n{fix_cmd}\n```\n",
        f"## Examples\n",
        f"\n```bash\n{example}\n```\n",
    ]
    return "\n".join(lines)


def main():
    base = "/home/admin1/projects/ErrorCode.excellentwiki.com/content"
    
    for section_name, config in SECTION_CONFIGS.items():
        dir_path = os.path.join(base, config["dir"])
        os.makedirs(dir_path, exist_ok=True)
        
        existing = set()
        if os.path.isdir(dir_path):
            for f in os.listdir(dir_path):
                if f.endswith(".md") and f != "_index.md":
                    existing.add(f[:-3])
        
        fm_line = config["fm"]
        topics = config["topics"]
        
        written = 0
        for topic in topics:
            slug, title, desc = topic
            if slug in existing:
                continue
            
            body = make_body(topic, section_name)
            
            content = f"""---
title: "[Solution] {title}"
description: "{desc}"
{fm_line}
severities: ["error"]
---

# {title}

{desc}

{body}
"""
            filepath = os.path.join(dir_path, f"{slug}.md")
            with open(filepath, "w") as f:
                f.write(content)
            written += 1
        
        total = len(existing) + written
        print(f"{section_name}: wrote {written} new pages (total: {total})")


if __name__ == "__main__":
    main()
