#!/usr/bin/env python3
"""Generate TimescaleDB error pages to reach 100+ total."""
import os

BASE = '/home/admin1/projects/ErrorCode.excellentwiki.com/content/tools/timescaledb'
EXISTING = {f.replace('.md', '') for f in os.listdir(BASE) if f.endswith('.md')}

def make_page(slug, title, desc, body):
    return f'''---
title: "[Solution] {title}"
description: "{desc}"
tools: ["timescaledb"]
error-types: ["tool-error"]
severities: ["error"]
---

{body}
'''

PAGES = [
    ("timescale-oom-error", "TimescaleDB Out of Memory Error", "How to fix TimescaleDB OOM errors", "## Common Causes\n\n- Continuous aggregate refresh using too much memory\n- Large chunk query without aggregation\n- Work memory too high\n\n## How to Fix\n\n```sql\nSET work_mem = '64MB';\n```\n\n## Examples\n\n```sql\nSELECT * FROM timescaledb_information.hypertables;\n```"),
    ("timescale-compression-error", "TimescaleDB Compression Error", "How to fix TimescaleDB chunk compression errors", "## Common Causes\n- Compression already enabled on hypertable\n- Segmentby columns not indexed\n- Not enough memory for compression\n\n## How to Fix\n\n```sql\nALTER TABLE mytable SET (timescaledb.compress, timescaledb.compress_segmentby = 'device_id');\n```\n\n## Examples\n\n```sql\nSELECT * FROM timescaledb_information.compression_settings;\n```"),
    ("timescale-continuous-aggregate-error", "TimescaleDB Continuous Aggregate Error", "How to fix TimescaleDB continuous aggregate errors", "## Common Causes\n- Refresh policy not set\n- View definition contains unsupported functions\n- Data range too large for refresh\n\n## How to Fix\n\n```sql\nCREATE MATERIALIZED VIEW my_cagg WITH (timescaledb.continuous) AS\nSELECT time_bucket('1 hour', time) AS bucket, device_id, AVG(temperature)\nFROM conditions\nGROUP BY bucket, device_id;\n```\n\n## Examples\n\n```sql\nSELECT * FROM timescaledb_information.continuous_aggregates;\n```"),
    ("timescale-hypertable-error", "TimescaleDB Hypertable Error", "How to fix TimescaleDB hypertable creation errors", "## Common Causes\n- Table already a hypertable\n- Time column not found\n- Partition interval too small\n\n## How to Fix\n\n```sql\nSELECT create_hypertable('conditions', 'time');\n```\n\n## Examples\n\n```sql\nSELECT * FROM timescaledb_information.hypertables;\n```"),
    ("timescale-chunk-error", "TimescaleDB Chunk Error", "How to fix TimescaleDB chunk errors", "## Common Causes\n- Too many chunks\n- Chunk interval too small\n- Chunk not compressed when expected\n\n## How to Fix\n\n```sql\nSELECT * FROM timescaledb_information.chunks ORDER BY range_start DESC LIMIT 10;\n```\n\n## Examples\n\n```sql\nSELECT drop_chunks('conditions', older_than => INTERVAL '7 days');\n```"),
    ("timescale-drop-chunk-error", "TimescaleDB Drop Chunk Error", "How to fix TimescaleDB chunk drop errors", "## Common Causes\n- Chunk still referenced by view\n- Retention policy not configured\n- Chunk too young to drop\n\n## How to Fix\n\n```sql\nSELECT drop_chunks('conditions', older_than => INTERVAL '30 days');\n```\n\n## Examples\n\n```sql\nSELECT * FROM timescaledb_information.jobs WHERE proc_name = 'policy_retention';\n```"),
    ("timescale-policy-error", "TimescaleDB Policy Error", "How to fix TimescaleDB policy errors", "## Common Causes\n- Policy not enabled\n- Policy schedule wrong\n- Policy function error\n\n## How to Fix\n\n```sql\nSELECT add_retention_policy('conditions', INTERVAL '30 days');\n```\n\n## Examples\n\n```sql\nSELECT * FROM timescaledb_information.jobs;\n```"),
    ("timescale-job-error", "TimescaleDB Job Error", "How to fix TimescaleDB background job errors", "## Common Causes\n- Job not scheduled\n- Job execution timeout\n- Job function error\n\n## How to Fix\n\n```sql\nSELECT * FROM timescaledb_information.jobs;\n```\n\n## Examples\n\n```sql\nSELECT * FROM _timescaledb_internal.job_stats;\n```"),
    ("timescale-reorder-error", "TimescaleDB Reorder Error", "How to fix TimescaleDB chunk reorder errors", "## Common Causes\n- Reorder job failing\n- Index not found for reorder\n- Chunk too large\n\n## How to Fix\n\n```sql\nSELECT add_reorder_policy('conditions', 'conditions_time_idx');\n```\n\n## Examples\n\n```sql\nSELECT * FROM timescaledb_information.jobs WHERE proc_name = 'policy_reorder';\n```"),
    ("timescale-reindex-error", "TimescaleDB Reindex Error", "How to fix TimescaleDB reindex errors", "## Common Causes\n- Index corrupted\n- Reindex taking too long\n- Lock contention during reindex\n\n## How to Fix\n\n```sql\nREINDEX INDEX conditions_time_idx;\n```\n\n## Examples\n\n```sql\nSELECT * FROM pg_stat_user_indexes WHERE schemaname = 'public';\n```"),
    ("timescale-distributed-error", "TimescaleDB Distributed Hypertable Error", "How to fix TimescaleDB distributed hypertable errors", "## Common Causes\n- Data nodes not connected\n- Replication factor too high\n- Distributed chunk not placed\n\n## How to Fix\n\n```sql\nSELECT add_data_node('data_node_1', host => 'node1', database => 'tsdb');\nSELECT create_distributed_hypertable('conditions', 'time', 'device_id', chunk_time_interval => INTERVAL '1 day', replication_factor => 2);\n```\n\n## Examples\n\n```sql\nSELECT * FROM timescaledb_information.data_nodes;\n```"),
    ("timescale-multinode-error", "TimescaleDB Multinode Error", "How to fix TimescaleDB multinode setup errors", "## Common Causes\n- Access node cannot reach data nodes\n- Distributed query planning failure\n- Schema not synced across nodes\n\n## How to Fix\n\n```sql\nSELECT * FROM timescaledb_information.data_nodes;\n```\n\n## Examples\n\n```sql\nSELECT * FROM pg_foreign_server;\n```"),
    ("timescale-foreign-table-error", "TimescaleDB Foreign Table Error", "How to fix TimescaleDB foreign table errors", "## Common Causes\n- Foreign server not accessible\n- Table schema mismatch\n- FDW extension not installed\n\n## How to Fix\n\n```sql\nCREATE EXTENSION IF NOT EXISTS timescaledb_fdw;\nCREATE SERVER data_node_1 FOREIGN DATA WRAPPER timescaledb_fdw OPTIONS (host 'node1', port '5432', dbname 'tsdb');\n```\n\n## Examples\n\n```sql\nSELECT * FROM pg_foreign_server;\n```"),
    ("timescale-data-node-error", "TimescaleDB Data Node Error", "How to fix TimescaleDB data node errors", "## Common Causes\n- Data node unreachable\n- Node health check failing\n- Node out of sync\n\n## How to Fix\n\n```sql\nSELECT * FROM timescaledb_information.data_nodes;\n```\n\n## Examples\n\n```sql\nSELECT attach_data_node('data_node_1', 'conditions');\n```"),
    ("timescale-1-node-error", "TimescaleDB Single Node Error", "How to fix TimescaleDB single node configuration errors", "## Common Causes\n- License requires multi-node for feature\n- Single node misconfigured as distributed\n- Memory not allocated correctly\n\n## How to Fix\n\n```sql\nSHOW timescaledb.license;\n```\n\n## Examples\n\n```sql\nSELECT * FROM timescaledb_information.hypertables;\n```"),
    ("timescale-access-node-error", "TimescaleDB Access Node Error", "How to fix TimescaleDB access node errors", "## Common Causes\n- Access node cannot connect to data nodes\n- Foreign table not created on access node\n- Query routing failure\n\n## How to Fix\n\n```sql\nSELECT * FROM timescaledb_information.data_nodes WHERE node_type = 'access';\n```\n\n## Examples\n\n```sql\nSELECT * FROM pg_stat_activity WHERE backend_type = 'timescaledb';\n```"),
    ("timescale-query-error", "TimescaleDB Query Performance Error", "How to fix TimescaleDB query performance errors", "## Common Causes\n- Query not using chunk exclusion\n- Missing index on time column\n- Full table scan instead of chunk scan\n\n## How to Fix\n\n```sql\nEXPLAIN ANALYZE SELECT * FROM conditions WHERE time > now() - INTERVAL '1 hour';\n```\n\n## Examples\n\n```sql\nSELECT * FROM timescaledb_information.hypertables;\n```"),
    ("timescale-connection-error", "TimescaleDB Connection Error", "How to fix TimescaleDB connection errors", "## Common Causes\n- Max connections reached\n- Connection pool exhaustion\n- TimescaleDB extension not loaded\n\n## How to Fix\n\n```sql\nSHOW max_connections;\nSELECT * FROM pg_stat_activity;\n```\n\n## Examples\n\n```sql\nSELECT count(*) FROM pg_stat_activity WHERE state = 'active';\n```"),
    ("timescale-partition-error", "TimescaleDB Partition Error", "How to fix TimescaleDB partitioning errors", "## Common Causes\n- Partition not aligned with hypertable\n- Range partition boundaries wrong\n- Partition pruning not working\n\n## How to Fix\n\n```sql\nSELECT * FROM timescaledb_information.hypertables;\n```\n\n## Examples\n\n```sql\nEXPLAIN SELECT * FROM conditions WHERE time BETWEEN '2024-01-01' AND '2024-01-31';\n```"),
    ("timescale-replication-error", "TimescaleDB Replication Error", "How to fix TimescaleDB replication errors", "## Common Causes\n- Replication lag between data nodes\n- Replica node not receiving changes\n- Conflict resolution failing\n\n## How to Fix\n\n```sql\nSELECT * FROM timescaledb_information.data_nodes;\n```\n\n## Examples\n\n```sql\nSELECT * FROM _timescaledb_internal._hyper_1_1_chunk;\n```"),
    ("timescale-view-error", "TimescaleDB View Error", "How to fix TimescaleDB view errors", "## Common Causes\n- View references non-existent hypertable\n- View refresh policy not set\n- View contains unsupported aggregate\n\n## How to Fix\n\n```sql\nCREATE VIEW conditions_hourly AS\nSELECT time_bucket('1 hour', time) AS bucket, device_id, AVG(temperature)\nFROM conditions\nGROUP BY bucket, device_id;\n```\n\n## Examples\n\n```sql\nSELECT * FROM timescaledb_information.views;\n```"),
    ("timescale-refresh-error", "TimescaleDB Refresh Error", "How to fix TimescaleDB continuous aggregate refresh errors", "## Common Causes\n- Refresh window too large\n- Concurrent refresh conflicts\n- Refresh policy schedule wrong\n\n## How to Fix\n\n```sql\nCALL refresh_continuous_aggregate('conditions_hourly', NOW() - INTERVAL '1 hour', NOW());\n```\n\n## Examples\n\n```sql\nSELECT * FROM timescaledb_information.jobs WHERE proc_name = 'policy_refresh';\n```"),
    ("timescale-config-error", "TimescaleDB Configuration Error", "How to fix TimescaleDB configuration errors", "## Common Causes\n- shared_preload_libraries missing timescaledb\n- Config parameter wrong\n- Restart required after config change\n\n## How to Fix\n\n```sql\nSHOW shared_preload_libraries;\n```\n\n## Examples\n\n```bash\ngrep timescaledb /etc/postgresql/*/main/postgresql.conf\n```"),
    ("timescale-backup-error", "TimescaleDB Backup Error", "How to fix TimescaleDB backup errors", "## Common Causes\n- Backup size too large\n- Backup taking too long\n- Backup disk space insufficient\n\n## How to Fix\n\n```bash\npg_basebackup -D /backup/base -Ft -z -P\n```\n\n## Examples\n\n```sql\nSELECT * FROM pg_stat_progress_backup;\n```"),
    ("timescale-restore-error", "TimescaleDB Restore Error", "How to fix TimescaleDB restore errors", "## Common Causes\n- Backup format incompatible\n- Restore target version mismatch\n- Tablespace not recreated\n\n## How to Fix\n\n```bash\npg_restore -D /backup/base -Fc\n```\n\n## Examples\n\n```bash\npg_restore --list /backup/base/timescaledb.backup\n```"),
    ("timescale-upgrade-error", "TimescaleDB Upgrade Error", "How to fix TimescaleDB upgrade errors", "## Common Causes\n- Extension upgrade failed\n- PostgreSQL version incompatible\n- Migration script error\n\n## How to Fix\n\n```sql\nALTER EXTENSION timescaledb UPDATE;\n```\n\n## Examples\n\n```sql\nSELECT default_version, installed_version FROM pg_extension WHERE extname = 'timescaledb';\n```"),
    ("timescale-migration-error", "TimescaleDB Migration Error", "How to fix TimescaleDB migration errors", "## Common Causes\n- Migration from vanilla PostgreSQL failed\n- Hypertable conversion error\n- Data type mismatch during migration\n\n## How to Fix\n\n```sql\nSELECT create_hypertable('mytable', 'time');\n```\n\n## Examples\n\n```sql\nSELECT * FROM timescaledb_information.hypertables;\n```"),
    ("timescale-license-error", "TimescaleDB License Error", "How to fix TimescaleDB license errors", "## Common Causes\n- Community license features exceeded\n- License expired\n- Feature requires Timescale Cloud\n\n## How to Fix\n\n```sql\nSHOW timescaledb.license;\n```\n\n## Examples\n\n```sql\nSELECT * FROM timescaledb_information.license;\n```"),
    ("timescale-access-node-connection-error", "TimescaleDB Access Node Connection Error", "How to fix TimescaleDB access node connection errors", "## Common Causes\n- Data node connection refused\n- Network latency too high\n- Connection pool exhausted\n\n## How to Fix\n\n```sql\nSELECT * FROM timescaledb_information.data_nodes;\n```\n\n## Examples\n\n```sql\nSELECT * FROM pg_stat_activity WHERE backend_type = 'timescaledb';\n```"),
]

count = 0
for slug, title, desc, body in PAGES:
    if slug in EXISTING:
        continue
    path = os.path.join(BASE, f'{slug}.md')
    with open(path, 'w') as f:
        f.write(make_page(slug, title, desc, body))
    count += 1

print(f'Generated {count} new TimescaleDB pages (total: {len(EXISTING) + count})')
