#!/usr/bin/env python3
"""Generate new MySQL error pages"""
import os

EXISTING = {f.replace('.md', '') for f in os.listdir('/home/admin1/projects/ErrorCode.excellentwiki.com/content/tools/mysql/') if f.endswith('.md')}

PAGES_DATA = [
    ("mysql-cant-connect", "MySQL Can't connect to server",
     "Fix MySQL 'Can't connect to MySQL server' error. Resolve connection failures when the MySQL server is unreachable.",
     "ERROR 2003 (HY000): Can't connect to MySQL server on 'host' (111)\n\nThis error occurs when the MySQL client cannot connect to the MySQL server. The server may not be running, the hostname may be wrong, or a firewall may be blocking the connection."),
    ("mysql-access-denied-user", "MySQL Access denied for user",
     "Fix MySQL 'Access denied for user' error. Resolve authentication failures when connecting to the MySQL server.",
     "ERROR 1045 (28000): Access denied for user 'user'@'host' (using password: YES)\n\nThis error occurs when the username or password is incorrect, or the user does not have permission to connect from the specified host."),
    ("mysql-database-exists", "MySQL Can't create database error",
     "Fix MySQL 'Can't create database' error. Resolve database creation failures when the database already exists or permissions are insufficient.",
     "ERROR 1007 (HY000): Can't create database 'dbname'; database exists\n\nThis error occurs when you try to create a database that already exists."),
    ("mysql-unknown-database", "MySQL Unknown database error",
     "Fix MySQL 'Unknown database' error. Resolve failures when trying to use a non-existent database.",
     "ERROR 1049 (42000): Unknown database 'dbname'\n\nThis error occurs when you try to use or connect to a database that does not exist."),
    ("mysql-cant-drop-database", "MySQL Can't drop database error",
     "Fix MySQL 'Can't drop database' error. Resolve database deletion failures.",
     "ERROR 1008 (HY000): Can't drop database 'dbname'; database doesn't exist\n\nThis error occurs when you try to drop a database that does not exist."),
    ("mysql-table-exists", "MySQL Table already exists error",
     "Fix MySQL 'Table already exists' error. Resolve table creation failures when the table name is already in use.",
     "ERROR 1050 (42S01): Table 'tablename' already exists\n\nThis error occurs when you try to create a table that already exists in the database."),
    ("mysql-unknown-table", "MySQL Unknown table error",
     "Fix MySQL 'Unknown table' error. Resolve failures when referencing a non-existent table.",
     "ERROR 1051 (42S02): Unknown table 'tablename'\n\nThis error occurs when you try to access or modify a table that does not exist."),
    ("mysql-cant-drop-table", "MySQL Can't drop table error",
     "Fix MySQL 'Can't drop table' error. Resolve table deletion failures.",
     "ERROR 1051 (42S02): Can't drop table 'tablename'; table doesn't exist\n\nThis error occurs when you try to drop a table that does not exist."),
    ("mysql-unknown-column-in-where", "MySQL Unknown column in where clause",
     "Fix MySQL 'Unknown column in where clause' error. Resolve query failures from invalid column references.",
     "ERROR 1054 (42S22): Unknown column 'col' in 'where clause'\n\nThis error occurs when a column referenced in the WHERE clause does not exist in the table."),
    ("mysql-unknown-column-in-order", "MySQL Unknown column in order clause",
     "Fix MySQL 'Unknown column in order clause' error. Resolve query failures from invalid column references.",
     "ERROR 1054 (42S22): Unknown column 'col' in 'order clause'\n\nThis error occurs when a column referenced in the ORDER BY clause does not exist."),
    ("mysql-unknown-column-in-group", "MySQL Unknown column in group clause",
     "Fix MySQL 'Unknown column in group clause' error. Resolve GROUP BY query failures.",
     "ERROR 1054 (42S22): Unknown column 'col' in 'group statement'\n\nThis error occurs when a column referenced in GROUP BY does not exist."),
    ("mysql-mix-of-group", "MySQL Mix of GROUP columns error",
     "Fix MySQL 'mix of GROUP columns' error. Resolve ONLY_FULL_GROUP_BY SQL mode violations.",
     "ERROR 1055 (42000): Expression of SELECT list is not in GROUP BY clause\n\nThis error occurs when a column in SELECT is not in GROUP BY and is not an aggregate function."),
    ("mysql-wrong-value-count", "MySQL Wrong value count error",
     "Fix MySQL 'Column count doesn't match value count' error. Resolve INSERT failures from column/value mismatches.",
     "ERROR 1136 (21S01): Column count doesn't match value count at row 1\n\nThis error occurs when the number of values in an INSERT does not match the number of columns."),
    ("mysql-no-default", "MySQL No default value error",
     "Fix MySQL 'No default value' error. Resolve INSERT failures when a column has no default value and is not specified.",
     "ERROR 1364 (HY000): Field 'fieldname' doesn't have a default value\n\nThis error occurs when you insert a row without specifying a value for a column that has no default and is NOT NULL."),
    ("mysql-truncated-incorrect-value", "MySQL Truncated incorrect value error",
     "Fix MySQL 'Truncated incorrect value' error. Resolve data truncation warnings for invalid values.",
     "Warning: Truncated incorrect <type> value: '<value>'\n\nThis warning occurs when MySQL truncates a value to fit the column data type."),
    ("mysql-data-truncated", "MySQL Data truncated error",
     "Fix MySQL 'Data truncated' error. Resolve column insertion failures when data is too large.",
     "ERROR 1265 (01000): Data truncated for column 'col' at row 1\n\nThis error occurs when data exceeds the column's maximum length or precision."),
    ("mysql-out-of-range", "MySQL Out of range value error",
     "Fix MySQL 'Out of range' value error. Resolve numeric overflow issues in columns.",
     "ERROR 1264 (22003): Out of range value for column 'col' at row 1\n\nThis error occurs when a numeric value is too large or too small for the column type."),
    ("mysql-duplicate-column", "MySQL Duplicate column name error",
     "Fix MySQL 'Duplicate column name' error. Resolve ALTER TABLE failures when adding a column that already exists.",
     "ERROR 1060 (42S21): Duplicate column name 'col'\n\nThis error occurs when you try to add a column that already exists in the table."),
    ("mysql-cant-add-foreign-key", "MySQL Can't add foreign key error",
     "Fix MySQL 'Can't add foreign key' error. Resolve foreign key constraint creation failures.",
     "ERROR 1215 (HY000): Cannot add foreign key constraint\n\nThis error occurs when the foreign key references a column that does not exist, has incompatible types, or the referenced table/column does not exist."),
    ("mysql-cant-create-table-errno", "MySQL Can't create table errno error",
     "Fix MySQL 'Can't create table' file system error. Resolve table creation failures due to OS-level issues.",
     "ERROR 1005 (HY000): Can't create table 'db.tablename' (errno: 13)\n\nThis error occurs when MySQL cannot create the table file due to permission issues or filesystem errors."),
    ("mysql-get-errno", "MySQL Got error errno",
     "Fix MySQL 'Got error' from storage engine. Resolve storage engine internal errors.",
     "ERROR 1030 (HY000): Got error <n> from storage engine\n\nThis error occurs when the storage engine (InnoDB, MyISAM) encounters an internal error."),
    ("mysql-file-not-found", "MySQL File not found error",
     "Fix MySQL 'File not found' error. Resolve missing file errors for MySQL data files.",
     "ERROR 1017 (HY000): Can't find file: 'tablename' (errno: 2)\n\nThis error occurs when MySQL cannot find a table's data file in the data directory."),
    ("mysql-record-too-long", "MySQL Record too long error",
     "Fix MySQL 'Record too long' error. Resolve row size limits for MySQL tables.",
     "ERROR 1118 (42000): Row size too large. The maximum row size for the used table type is 65535.\n\nThis error occurs when the total row size exceeds the maximum row length limit."),
    ("mysql-too-big-precision", "MySQL Too big precision error",
     "Fix MySQL 'Too big precision' error. Resolve DECIMAL precision specification errors.",
     "ERROR 1425 (42000): Too big precision <n> specified for 'col'. Maximum is 65.\n\nThis error occurs when the precision specified for a DECIMAL column exceeds the maximum of 65."),
    ("mysql-too-big-scale", "MySQL Too big scale error",
     "Fix MySQL 'Too big scale' error. Resolve DECIMAL scale specification errors.",
     "ERROR 1426 (42000): Too big scale <n> specified for 'col'. Maximum is 30.\n\nThis error occurs when the scale for a DECIMAL column exceeds the maximum of 30."),
    ("mysql-partition-error", "MySQL Partition error",
     "Fix MySQL 'Partition' error. Resolve table partitioning failures.",
     "ERROR 1486 (HY000): Partition management error\n\nThis error occurs when there is an issue with table partitioning configuration."),
    ("mysql-tablespace-error", "MySQL Tablespace error",
     "Fix MySQL 'Tablespace' error. Resolve tablespace-related issues for InnoDB tables.",
     "ERROR 1680 (42000): Tablespace <name> does not exist\n\nThis error occurs when referencing a non-existent tablespace."),
    ("mysql-general-error-default", "MySQL General error default value",
     "Fix MySQL 'General error' with default value. Resolve incompatible default value issues.",
     "ERROR 1067 (42000): Invalid default value for 'col'\n\nThis error occurs when the default value specified for a column is not valid for the column data type."),
    ("mysql-bad-null", "MySQL Bad NULL error",
     "Fix MySQL 'Column cannot be null' error. Resolve NOT NULL constraint violations.",
     "ERROR 1048 (23000): Column 'col' cannot be null\n\nThis error occurs when you try to insert NULL into a column defined as NOT NULL."),
    ("mysql-subquery-return-more", "MySQL Subquery returns more than one row",
     "Fix MySQL 'Subquery returns more than one row' error. Resolve single-value subquery issues.",
     "ERROR 1242 (21000): Subquery returns more than 1 row\n\nThis error occurs when a subquery used with =, <, >, etc. returns multiple rows."),
    ("mysql-unknown-system-var", "MySQL Unknown system variable",
     "Fix MySQL 'Unknown system variable' error. Resolve configuration variable reference issues.",
     "ERROR 1193 (HY000): Unknown system variable 'varname'\n\nThis error occurs when you reference a system variable that does not exist."),
    ("mysql-incorrect-key-file", "MySQL Incorrect key file error",
     "Fix MySQL 'Incorrect key file' error. Resolve MyISAM table index corruption.",
     "ERROR 126 (HY000): Incorrect key file for table 'tablename'; try to repair it\n\nThis error occurs when a MyISAM table's index file is corrupted."),
    ("mysql-old-format", "MySQL Old format error",
     "Fix MySQL 'Old format' error. Resolve incompatibility with older table formats.",
     "ERROR 1178 (42000): The storage engine for the table doesn't support <operation>\n\nThis error occurs when you try to use a feature not supported by the table's storage engine."),
    ("mysql-sp-does-not-exist", "MySQL Stored procedure does not exist",
     "Fix MySQL 'Stored procedure does not exist' error. Resolve SP execution failures.",
     "ERROR 1305 (42000): PROCEDURE <name> does not exist\n\nThis error occurs when you try to call a stored procedure that does not exist."),
    ("mysql-function-does-not-exist", "MySQL Function does not exist",
     "Fix MySQL 'Function does not exist' error. Resolve UDF and stored function execution failures.",
     "ERROR 1305 (42000): FUNCTION <name> does not exist\n\nThis error occurs when you try to call a function that does not exist in the database."),
    ("mysql-view-does-not-exist", "MySQL View does not exist",
     "Fix MySQL 'View does not exist' error. Resolve view reference failures.",
     "ERROR 1356 (HY000): View 'viewname' does not exist\n\nThis error occurs when you reference a view that does not exist."),
    ("mysql-trigger-does-not-exist", "MySQL Trigger does not exist",
     "Fix MySQL 'Trigger does not exist' error. Resolve trigger reference failures.",
     "ERROR 1360 (HY000): Trigger does not exist\n\nThis error occurs when you try to drop or alter a trigger that does not exist."),
    ("mysql-event-does-not-exist", "MySQL Event does not exist",
     "Fix MySQL 'Event does not exist' error. Resolve scheduled event reference failures.",
     "ERROR 1539 (HY000): Event '<name>' does not exist\n\nThis error occurs when you reference a scheduled event that does not exist."),
    ("mysql-user-already-exists", "MySQL User already exists error",
     "Fix MySQL 'User already exists' error. Resolve user creation failures for duplicate users.",
     "ERROR 1396 (HY000): Operation CREATE USER failed for 'user'@'host'\n\nThis error occurs when you try to create a user that already exists."),
    ("mysql-cant-drop-user", "MySQL Can't drop user error",
     "Fix MySQL 'Can't drop user' error. Resolve user deletion failures.",
     "ERROR 1396 (HY000): Operation DROP USER failed for 'user'@'host'\n\nThis error occurs when you try to drop a user that does not exist."),
    ("mysql-grant-privilege", "MySQL Grant privilege error",
     "Fix MySQL 'Grant privilege' error. Resolve permission assignment failures.",
     "ERROR 1410 (42000): You are not allowed to create a user with GRANT\n\nThis error occurs when you do not have the GRANT privilege."),
    ("mysql-revoke-privilege", "MySQL Revoke privilege error",
     "Fix MySQL 'Revoke privilege' error. Resolve permission removal failures.",
     "ERROR 1147 (42000): There is no such grant defined for user on host\n\nThis error occurs when the privilege you are trying to revoke does not exist."),
    ("mysql-flush-privileges", "MySQL Flush privileges error",
     "Fix MySQL 'Flush privileges' error. Resolve permission reload failures.",
     "ERROR 1227 (42000): Access denied; you need the RELOAD privilege\n\nThis error occurs when you do not have permission to run FLUSH PRIVILEGES."),
    ("mysql-load-data-error", "MySQL LOAD DATA error",
     "Fix MySQL 'LOAD DATA' error. Resolve bulk data import failures.",
     "ERROR 29 (HY000): File '<path>' not found (Errcode: 2)\n\nThis error occurs when the file specified in LOAD DATA INFILE does not exist."),
    ("mysql-select-into-error", "MySQL SELECT INTO error",
     "Fix MySQL 'SELECT INTO' error. Resolve query export failures.",
     "ERROR 1329 (02000): No data - zero rows fetched, selected, or processed\n\nThis warning occurs when SELECT INTO returns no rows."),
    ("mysql-handler-error", "MySQL Handler error",
     "Fix MySQL 'Handler' error. Resolve HANDLER statement failures.",
     "ERROR 1190 (HY000): Table 'tablename' was not opened with HANDLER\n\nThis error occurs when you try to use HANDLER READ without opening the table first."),
    ("mysql-check-table", "MySQL CHECK TABLE error",
     "Fix MySQL 'CHECK TABLE' error. Resolve table checking and repair issues.",
     "Warning: Table is marked as crashed\n\nThis warning appears when a table check finds corruption."),
    ("mysql-repair-table", "MySQL REPAIR TABLE error",
     "Fix MySQL 'REPAIR TABLE' error. Resolve table repair failures.",
     "ERROR 145 (HY000): Table 'tablename' is marked as crashed and should be repaired\n\nThis error occurs when MySQL detects a corrupted table."),
    ("mysql-analyze-table", "MySQL ANALYZE TABLE error",
     "Fix MySQL 'ANALYZE TABLE' error. Resolve table statistics update failures.",
     "ERROR 1064 (42000): You have an error in your SQL syntax\n\nThis error can occur when the ANALYZE TABLE syntax is incorrect."),
    ("mysql-optimize-table", "MySQL OPTIMIZE TABLE error",
     "Fix MySQL 'OPTIMIZE TABLE' error. Resolve table optimization failures.",
     "ERROR 1062 (23000): Duplicate entry '<key>' for key <n>\n\nThis error can occur during OPTIMIZE TABLE if there are duplicate keys."),
    ("mysql-xa-error", "MySQL XA transaction error",
     "Fix MySQL 'XA transaction' error. Resolve distributed transaction failures.",
     "ERROR 1397 (XAE04): XAER_NOTA: Unknown XID\n\nThis error occurs when an XA transaction ID is not recognized."),
    ("mysql-savepoint-error", "MySQL SAVEPOINT error",
     "Fix MySQL 'SAVEPOINT' error. Resolve transaction savepoint issues.",
     "ERROR 1305 (42000): SAVEPOINT <name> does not exist\n\nThis error occurs when you try to release or roll back to a non-existent savepoint."),
    ("mysql-lock-tables-error", "MySQL LOCK TABLES error",
     "Fix MySQL 'LOCK TABLES' error. Resolve table locking failures.",
     "ERROR 1461 (42000): Can't lock table, check privileges\n\nThis error occurs when you do not have LOCK TABLES privilege."),
    ("mysql-unlock-tables", "MySQL UNLOCK TABLES error",
     "Fix MySQL 'UNLOCK TABLES' error. Resolve table unlocking issues.",
     "ERROR 1105 (HY000): You are not using LOCK TABLES\n\nThis error occurs when you try to unlock tables without holding any locks."),
    ("mysql-set-transaction", "MySQL SET TRANSACTION error",
     "Fix MySQL 'SET TRANSACTION' error. Resolve transaction isolation level configuration issues.",
     "ERROR 1568 (25001): Transaction isolation level can't be changed while a transaction is in progress\n\nThis error occurs when trying to change isolation level mid-transaction."),
    ("mysql-character-set-error", "MySQL Character set error",
     "Fix MySQL 'Character set' error. Resolve encoding and collation issues.",
     "ERROR 1115 (42000): Unknown character set: '<charset>'\n\nThis error occurs when you specify an unknown character set."),
    ("mysql-collation-error", "MySQL Collation error",
     "Fix MySQL 'Collation' error. Resolve collation mismatch issues.",
     "ERROR 1267 (HY000): Illegal mix of collations for operation '<op>'\n\nThis error occurs when comparing or combining strings with incompatible collations."),
    ("mysql-timezone-error", "MySQL Timezone error",
     "Fix MySQL 'Timezone' error. Resolve timezone configuration failures.",
     "ERROR 1298 (HY000): Unknown or incorrect time zone: '<tz>'\n\nThis error occurs when you reference a timezone that is not loaded in MySQL."),
    ("mysql-fulltext-error", "MySQL Fulltext error",
     "Fix MySQL 'Fulltext' error. Resolve FULLTEXT index and search issues.",
     "ERROR 1191 (HY000): Can't find FULLTEXT index matching the column list\n\nThis error occurs when a FULLTEXT search references columns without a FULLTEXT index."),
    ("mysql-spatial-error", "MySQL Spatial error",
     "Fix MySQL 'Spatial' error. Resolve spatial data type and index issues.",
     "ERROR 3037 (22023): Invalid GIS data provided to function <func>\n\nThis error occurs when spatial data is invalid or malformed."),
    ("mysql-json-error", "MySQL JSON error",
     "Fix MySQL 'JSON' error. Resolve JSON data type and function issues.",
     "ERROR 3140 (22032): Invalid JSON text in argument <n>\n\nThis error occurs when invalid JSON data is provided to a JSON function."),
    ("mysql-generated-column-error", "MySQL Generated column error",
     "Fix MySQL 'Generated column' error. Resolve virtual and stored column definition issues.",
     "ERROR 3106 (HY000): Defining a generated column as <type> is not supported\n\nThis error occurs when the generated column definition is invalid."),
    ("mysql-cte-error", "MySQL CTE error",
     "Fix MySQL 'CTE error' error. Resolve Common Table Expression issues.",
     "ERROR 3593 (HY000): You cannot use the recursive keyword without a column list\n\nThis error occurs when a recursive CTE is missing the required column list."),
    ("mysql-window-function", "MySQL Window function error",
     "Fix MySQL 'Window function' error. Resolve window function syntax and usage issues.",
     "ERROR 3587 (HY000): Window '<name>' not found\n\nThis error occurs when referencing a non-existent window name."),
    ("mysql-lateral-derived", "MySQL Lateral derived table error",
     "Fix MySQL 'Lateral derived table' error. Resolve LATERAL keyword usage issues.",
     "ERROR 3577 (HY000): The LATERAL keyword is not supported here\n\nThis error occurs when LATERAL is used in an unsupported position."),
    ("mysql-explain-error", "MySQL EXPLAIN error",
     "Fix MySQL 'EXPLAIN' error. Resolve query plan analysis failures.",
     "ERROR 1064 (42000): You have an error in your SQL syntax\n\nThis error can occur when EXPLAIN is used with invalid syntax."),
    ("mysql-show-create-table", "MySQL SHOW CREATE TABLE error",
     "Fix MySQL 'SHOW CREATE TABLE' error. Resolve table definition display issues.",
     "ERROR 1146 (42S02): Table '<db>.<table>' doesn't exist\n\nThis error occurs when you try to SHOW CREATE TABLE for a non-existent table."),
    ("mysql-show-create-db", "MySQL SHOW CREATE DATABASE error",
     "Fix MySQL 'SHOW CREATE DATABASE' error. Resolve database definition display issues.",
     "ERROR 1049 (42000): Unknown database '<db>'\n\nThis error occurs when you try to show the create statement for a non-existent database."),
    ("mysql-kill-error", "MySQL KILL error",
     "Fix MySQL 'KILL' error. Resolve connection termination failures.",
     "ERROR 1094 (HY000): Unknown thread id: <n>\n\nThis error occurs when you try to kill a non-existent thread or connection."),
    ("mysql-show-processlist", "MySQL SHOW PROCESSLIST error",
     "Fix MySQL 'SHOW PROCESSLIST' error. Resolve active connection listing issues.",
     "ERROR 1227 (42000): Access denied; you need the PROCESS privilege\n\nThis error occurs when you do not have the PROCESS privilege to view other connections."),
    ("mysql-reset-connection", "MySQL RESET CONNECTION error",
     "Fix MySQL 'RESET CONNECTION' error. Resolve connection state reset issues.",
     "ERROR 1835 (HY000): Malformed communication packet\n\nThis error can occur when the connection is in an invalid state for reset."),
    ("mysql-change-user", "MySQL CHANGE USER error",
     "Fix MySQL 'CHANGE USER' error. Resolve user context switch failures.",
     "ERROR 1045 (28000): Access denied for user 'user'@'host' (using password: YES)\n\nThis error occurs when CHANGE USER provides invalid credentials."),
    ("mysql-compression-error", "MySQL Compression error",
     "Fix MySQL 'Compression' error. Resolve client-server compression issues.",
     "ERROR 2026 (HY000): SSL connection error: protocol version mismatch\n\nThis error can occur when compression and SSL settings conflict."),
    ("mysql-pipe-error", "MySQL Named pipe error",
     "Fix MySQL 'Named pipe' error. Resolve Windows named pipe connection issues.",
     "ERROR 1045 (28000): Access denied for user using pipe\n\nThis error occurs when named pipe connections are not properly configured."),
    ("mysql-shared-memory", "MySQL Shared memory error",
     "Fix MySQL 'Shared memory' error. Resolve shared memory connection issues.",
     "ERROR 1045 (28000): Access denied for user using shared memory\n\nThis error occurs when shared memory connections are not configured."),
    ("mysql-localhost-error", "MySQL Localhost connection error",
     "Fix MySQL 'Localhost' connection error. Resolve socket vs TCP connection issues.",
     "ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock'\n\nThis error occurs when the MySQL socket file is not found."),
    ("mysql-host-blocked", "MySQL Host blocked error",
     "Fix MySQL 'Host blocked' error. Resolve connection denials from too many failed attempts.",
     "ERROR 1129 (HY000): Host 'host' is blocked because of many connection errors\n\nThis error occurs when a host has too many failed connection attempts."),
    ("mysql-too-many-connections-adv", "MySQL Too many connections advanced",
     "Fix MySQL 'Too many connections' advanced error. Resolve connection pool exhaustion issues.",
     "ERROR 1040 (HY000): Too many connections\n\nThis error occurs when all available MySQL connections are in use."),
    ("mysql-wait-timeout", "MySQL Wait timeout error",
     "Fix MySQL 'Wait timeout' error. Resolve connection idle timeout issues.",
     "ERROR 2006 (HY000): MySQL server has gone away\n\nThis error can occur when a connection remains idle longer than wait_timeout."),
    ("mysql-interactive-timeout", "MySQL Interactive timeout",
     "Fix MySQL 'Interactive timeout' error. Resolve interactive connection timeout issues.",
     "ERROR 2006 (HY000): MySQL server has gone away\n\nThis error can occur for interactive connections that exceed interactive_timeout."),
    ("mysql-net-read-timeout", "MySQL Net read timeout error",
     "Fix MySQL 'Net read timeout' error. Resolve network read timeout issues.",
     "ERROR 1159 (08S01): Got timeout reading communication packets\n\nThis error occurs when MySQL times out while reading data from a connection."),
    ("mysql-net-write-timeout", "MySQL Net write timeout error",
     "Fix MySQL 'Net write timeout' error. Resolve network write timeout issues.",
     "ERROR 1160 (08S01): Got timeout writing communication packets\n\nThis error occurs when MySQL times out while writing data to a connection."),
    ("mysql-packet-too-large", "MySQL Packet too large error",
     "Fix MySQL 'Packet too large' error. Resolve max_allowed_packet size issues.",
     "ERROR 1153 (08S01): Got a packet bigger than 'max_allowed_packet' bytes\n\nThis error occurs when a query or result set exceeds the max_allowed_packet setting."),
    ("mysql-ssl-error-adv", "MySQL SSL connection error",
     "Fix MySQL 'SSL connection error'. Resolve SSL/TLS connection failures.",
     "ERROR 2026 (HY000): SSL connection error: <detail>\n\nThis error occurs when the SSL/TLS handshake between client and server fails."),
    ("mysql-certificate-error", "MySQL Certificate error",
     "Fix MySQL 'Certificate' error. Resolve SSL certificate verification failures.",
     "ERROR 2026 (HY000): SSL connection error: unable to verify certificate\n\nThis error occurs when the server's SSL certificate cannot be verified."),
    ("mysql-cipher-error", "MySQL Cipher error",
     "Fix MySQL 'Cipher' error. Resolve SSL cipher mismatch issues.",
     "ERROR 2026 (HY000): SSL connection error: no shared cipher\n\nThis error occurs when client and server have no common SSL ciphers."),
    ("mysql-auth-plugin-error", "MySQL Auth plugin error",
     "Fix MySQL 'Auth plugin' error. Resolve authentication plugin compatibility issues.",
     "ERROR 1526 (HY000): Authentication plugin '<plugin>' cannot be loaded\n\nThis error occurs when the server requires an authentication plugin not available on the client."),
    ("mysql-caching-sha2", "MySQL caching_sha2_password error",
     "Fix MySQL 'caching_sha2_password' authentication error. Resolve newer MySQL authentication issues with older clients.",
     "ERROR 2061 (HY000): Authentication plugin 'caching_sha2_password' cannot be loaded\n\nThis error occurs when the client does not support the caching_sha2_password plugin (MySQL 8.0+)."),
    ("mysql-mysql_native_password", "MySQL mysql_native_password error",
     "Fix MySQL 'mysql_native_password' error. Resolve legacy authentication issues.",
     "ERROR 1526 (HY000): Authentication plugin 'mysql_native_password' cannot be loaded\n\nThis error occurs when the plugin is not available on the server."),
    ("mysql-prepared-stmt", "MySQL Prepared statement error",
     "Fix MySQL 'Prepared statement' error. Resolve prepared statement execution issues.",
     "ERROR 1461 (42000): Can't create more than max_prepared_stmt_count statements\n\nThis error occurs when the prepared statement limit is reached."),
    ("mysql-cursor-error", "MySQL Cursor error",
     "Fix MySQL 'Cursor' error. Resolve stored procedure cursor issues.",
     "ERROR 1329 (02000): No data - zero rows fetched, selected, or processed\n\nThis error occurs when a cursor fetch reaches the end of the result set."),
    ("mysql-condition-handler", "MySQL Condition handler error",
     "Fix MySQL 'Condition handler' error. Resolve stored procedure error handling issues.",
     "ERROR 1337 (42000): Variable or condition declaration after cursor or handler definition\n\nThis error occurs when declarations are in the wrong order in a stored procedure."),
    ("mysql-signal-error", "MySQL SIGNAL error",
     "Fix MySQL 'SIGNAL' error. Resolve stored procedure signal/raise error issues.",
     "ERROR 1643 (42000): The SIGNAL statement cannot be used outside of a handler\n\nThis error occurs when SIGNAL is used outside a condition handler context."),
    ("mysql-resignal-error", "MySQL RESIGNAL error",
     "Fix MySQL 'RESIGNAL' error. Resolve stored procedure resignal issues.",
     "ERROR 1646 (42000): RESIGNAL when handler not active\n\nThis error occurs when RESIGNAL is used outside of a condition handler."),
    ("mysql-get-diagnostics", "MySQL GET DIAGNOSTICS error",
     "Fix MySQL 'GET DIAGNOSTICS' error. Resolve diagnostic information retrieval issues.",
     "ERROR 1648 (42000): GET DIAGNOSTICS without a handler active\n\nThis error occurs when GET DIAGNOSTICS is used outside a handler."),
    ("mysql-role-error", "MySQL Role error",
     "Fix MySQL 'Role' error. Resolve database role management issues.",
     "ERROR 3533 (HY000): Invalid role specification '<role>'\n\nThis error occurs when a role name is invalid or does not exist."),
    ("mysql-mandatory-roles", "MySQL Mandatory roles error",
     "Fix MySQL 'Mandatory roles' error. Resolve mandatory role assignment issues.",
     "ERROR 3529 (HY000): Cannot drop role '<role>' because it is mandatory\n\nThis error occurs when trying to drop a mandatory role."),
    ("mysql-clone-plugin", "MySQL Clone plugin error",
     "Fix MySQL 'Clone plugin' error. Resolve cloning and provisioning issues.",
     "ERROR 3870 (HY000): Clone plugin is not installed\n\nThis error occurs when the clone plugin is not enabled."),
    ("mysql-group-replication", "MySQL Group replication error",
     "Fix MySQL 'Group replication' error. Resolve group replication membership and communication issues.",
     "ERROR 3092 (HY000): The server is not configured for group replication\n\nThis error occurs when group replication is not configured."),
    ("mysql-innodb-corruption", "MySQL InnoDB corruption error",
     "Fix MySQL 'InnoDB corruption' error. Resolve InnoDB data page corruption issues.",
     "ERROR 2000 (HY000): InnoDB: Database page corruption on disk or a failed file read\n\nThis error indicates InnoDB has detected data page corruption."),
    ("mysql-innodb-read-only", "MySQL InnoDB read-only error",
     "Fix MySQL 'InnoDB read-only' error. Resolve InnoDB read-only mode issues.",
     "ERROR 1799 (HY000): Cannot execute statement: impossible to write to InnoDB\n\nThis error occurs when InnoDB is in read-only mode."),
    ("mysql-innodb-fulltext", "MySQL InnoDB FULLTEXT error",
     "Fix MySQL 'InnoDB FULLTEXT' error. Resolve InnoDB full-text search issues.",
     "ERROR 3809 (HY000): InnoDB: Fulltext index <n> is not usable\n\nThis error occurs when an InnoDB FULLTEXT index is corrupted."),
    ("mysql-innodb-tablespace-full", "MySQL InnoDB tablespace full",
     "Fix MySQL 'InnoDB tablespace full' error. Resolve InnoDB tablespace exhaustion issues.",
     "ERROR 1114 (HY000): The table '<table>' is full\n\nThis error occurs when the InnoDB tablespace runs out of space."),
    ("mysql-innodb-deadlock", "MySQL InnoDB deadlock error",
     "Fix MySQL 'InnoDB deadlock' error. Resolve transaction deadlock detection issues.",
     "ERROR 1213 (40001): Deadlock found when trying to get lock; try restarting transaction\n\nThis error occurs when two or more transactions hold locks the other needs."),
    ("mysql-innodb-lock-wait", "MySQL InnoDB lock wait timeout",
     "Fix MySQL 'InnoDB lock wait timeout' error. Resolve transaction lock waiting issues.",
     "ERROR 1205 (HY000): Lock wait timeout exceeded; try restarting transaction\n\nThis error occurs when a transaction waits too long for a lock."),
    ("mysql-innodb-log-full", "MySQL InnoDB log full error",
     "Fix MySQL 'InnoDB log full' error. Resolve InnoDB redo log exhaustion issues.",
     "ERROR 1114 (HY000): The table '<table>' is full\n\nThis error can occur when the InnoDB redo log fills up before a checkpoint completes."),
    ("mysql-innodb-temp-table", "MySQL InnoDB temp table error",
     "Fix MySQL 'InnoDB temp table' error. Resolve temporary table creation issues.",
     "ERROR 1877 (HY000): Can't create temporary file\n\nThis error occurs when InnoDB cannot create temporary table files on disk."),
]

def make_mysql_page(slug, title, desc, body):
    lines = [
        '---',
        f'title: "[Solution] {title}"',
        f'description: "{desc}"',
        'tools: ["mysql"]',
        'error-types: ["tool-error"]',
        'severities: ["error"]',
        'weight: 5',
        '---',
        '',
        f'# {title}',
        '',
        body,
        '',
        '## How to Fix',
        '',
        '### Check MySQL Status',
        '',
        '```bash',
        'sudo systemctl status mysql',
        'mysqladmin ping',
        '```',
        '',
        '### Check Error Log',
        '',
        '```bash',
        'sudo tail -100 /var/log/mysql/error.log',
        '```',
        '',
        '### Verify Configuration',
        '',
        '```bash',
        'mysql --help',
        "sudo mysql -e \"SHOW VARIABLES LIKE '%timeout%';\"",
        '```',
        '',
        '## Related Errors',
        '',
        '- [MySQL Connection Refused]({{< relref "/tools/mysql/mysql-connection-refused" >}}) — connection refused',
        '- [MySQL Gone Away]({{< relref "/tools/mysql/mysql-gone-away" >}}) — connection lost',
        '',
    ]
    return '\n'.join(lines)

count = 0
for slug, title, desc, body in PAGES_DATA:
    if slug in EXISTING:
        print(f"SKIP (exists): {slug}")
        continue
    content = make_mysql_page(slug, title, desc, body)
    path = f"/home/admin1/projects/ErrorCode.excellentwiki.com/content/tools/mysql/{slug}.md"
    with open(path, 'w') as f:
        f.write(content)
    count += 1
    print(f"CREATED: {slug}")

print(f"\nTotal created: {count}")
print(f"Total skipped (existing): {len(PAGES_DATA) - count}")
