#!/usr/bin/env python3
"""Generate InfluxDB error pages to reach 100+ total."""
import os

BASE = '/home/admin1/projects/ErrorCode.excellentwiki.com/content/tools/influxdb'
EXISTING = {f.replace('.md', '') for f in os.listdir(BASE) if f.endswith('.md')}

def make_page(slug, title, desc, body):
    return f'''---
title: "[Solution] {title}"
description: "{desc}"
tools: ["influxdb"]
error-types: ["tool-error"]
severities: ["error"]
---

{body}
'''

PAGES = [
    ("influxdb-connection-refused", "InfluxDB Connection Refused", "How to fix InfluxDB connection refused errors", "## Common Causes\n\n- InfluxDB service not running\n- Wrong port (default 8086)\n- Firewall blocking connection\n\n## How to Fix\n\n```bash\nsudo systemctl status influxdb\nsudo systemctl start influxdb\n```\n\n## Examples\n\n```bash\ncurl -s http://localhost:8086/ping\n```"),
    ("influxdb-auth-failed", "InfluxDB Authentication Failed", "How to fix InfluxDB authentication failures", "## Common Causes\n\n- Wrong username or password\n- Token expired or revoked\n- Authentication not enabled\n\n## How to Fix\n\n```bash\ninflux auth create --org myorg --description \"API token\" --read-bucket 000 --write-bucket 000\n```\n\n## Examples\n\n```bash\ncurl -s -H \"Authorization: Token YOUR_TOKEN\" http://localhost:8086/api/v2/me\n```"),
    ("influxdb-database-not-found", "InfluxDB Database Not Found", "How to fix InfluxDB database not found errors", "## Common Causes\n\n- Database name typo\n- Database deleted\n- Using wrong retention policy\n\n## How to Fix\n\n```bash\ninflux -execute 'SHOW DATABASES'\n```\n\n## Examples\n\n```bash\ninflux -execute 'CREATE DATABASE mydb'\n```"),
    ("influxdb-shard-error", "InfluxDB Shard Error", "How to fix InfluxDB shard errors", "## Common Causes\n\n- Shard directory permissions wrong\n- Shard file corrupted\n- Too many shards created\n\n## How to Fix\n\n```bash\ninflux -execute 'SHOW SHARD GROUPS'\n```\n\n## Examples\n\n```bash\ninflux -execute 'SHOW SHARDS ON mydb'\n```"),
    ("influxdb-wal-error", "InfluxDB WAL Error", "How to fix InfluxDB write-ahead log errors", "## Common Causes\n\n- WAL directory corrupted\n- Disk full preventing WAL flush\n- WAL replay failure on startup\n\n## How to Fix\n\n```ini\n[data]\nwal-dir = \"/var/lib/influxdb/wal\"\n```\n\n## Examples\n\n```bash\nls -la /var/lib/influxdb/wal/mydb/\n```"),
    ("influxdb-tsm-error", "InfluxDB TSM Error", "How to fix InfluxDB TSM storage engine errors", "## Common Causes\n\n- TSM file corrupted\n- Compaction failure\n- Disk I/O error\n\n## How to Fix\n\n```bash\ninflux_inspect info /var/lib/influxdb/data/mydb/\n```\n\n## Examples\n\n```bash\ninflux_inspect report /var/lib/influxdb/data/mydb/\n```"),
    ("influxdb-compaction-error", "InfluxDB Compaction Error", "How to fix InfluxDB compaction errors", "## Common Causes\n\n- Not enough disk space for compaction\n- Compaction process crashing\n- Too many TSM files\n\n## How to Fix\n\n```ini\n[data]\nmax-concurrent-compactions = 2\n```\n\n## Examples\n\n```bash\ninflux_inspect report -v /var/lib/influxdb/data/mydb/\n```"),
    ("influxdb-oom-error", "InfluxDB Out of Memory Error", "How to fix InfluxDB OOM errors", "## Common Causes\n\n- Query using too much memory\n- Too many series loaded\n- Query timeout too high\n\n## How to Fix\n\n```ini\n[http]\nmax-body-size = 0\n\n[coordinator]\nquery-timeout = \"30s\"\n```\n\n## Examples\n\n```bash\nfree -h\nps aux | grep influxd | head -1\n```"),
    ("influxdb-write-error", "InfluxDB Write Error", "How to fix InfluxDB write errors", "## Common Causes\n\n- Line protocol syntax error\n- Bucket not found\n- Write permission denied\n\n## How to Fix\n\n```bash\ncurl -X POST http://localhost:8086/api/v2/write?org=myorg&bucket=mybucket \\n  -H \"Authorization: Token YOUR_TOKEN\" \\n  -d \"test,host=server01 value=1.0\"\n```\n\n## Examples\n\n```bash\ncurl -o /dev/null -s -w '%{http_code}' -X POST http://localhost:8086/api/v2/write?org=myorg&bucket=mybucket \\n  -H \"Authorization: Token YOUR_TOKEN\" -d \"test value=1.0\"\n```"),
    ("influxdb-query-error", "InfluxDB Query Error", "How to fix InfluxDB query errors", "## Common Causes\n\n- Flux query syntax error\n- InfluxQL syntax error\n- Measurement not found\n\n## How to Fix\n\n```flux\nfrom(bucket: \"mybucket\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"cpu\")\n```\n\n## Examples\n\n```bash\ninflux query 'from(bucket: \"mybucket\") |> range(start: -1h) |> limit(n: 5)'\n```"),
    ("influxdb-bucket-error", "InfluxDB Bucket Error", "How to fix InfluxDB bucket errors", "## Common Causes\n\n- Bucket name already exists\n- Retention period invalid\n- Bucket permissions wrong\n\n## How to Fix\n\n```bash\ninflux bucket create --name mybucket --org myorg --retention 720h\n```\n\n## Examples\n\n```bash\ninflux bucket list --org myorg\n```"),
    ("influxdb-token-error", "InfluxDB Token Error", "How to fix InfluxDB token errors", "## Common Causes\n- Token does not exist\n- Token permissions insufficient\n- Token expired\n\n## How to Fix\n\n```bash\ninflux auth list --org myorg\ninflux auth create --org myorg --read-bucket 000 --write-bucket 000\n```\n\n## Examples\n\n```bash\ninflux auth find --org myorg\n```"),
    ("influxdb-organization-error", "InfluxDB Organization Error", "How to fix InfluxDB organization errors", "## Common Causes\n- Organization not found\n- Wrong org ID in API call\n- Organization name mismatch\n\n## How to Fix\n\n```bash\ninflux org list\n```\n\n## Examples\n\n```bash\ncurl -s -H \"Authorization: Token YOUR_TOKEN\" http://localhost:8086/api/v2/orgs | jq '.orgs[].name'\n```"),
    ("influxdb-retention-error", "InfluxDB Retention Policy Error", "How to fix InfluxDB retention policy errors", "## Common Causes\n- Retention period too short\n- Default retention policy not set\n- Retention policy not applied to bucket\n\n## How to Fix\n\n```bash\ninflux bucket update --id BUCKET_ID --retention 168h --org myorg\n```\n\n## Examples\n\n```bash\ninflux bucket list --org myorg | grep -E 'name|retention'\n```"),
    ("influxdb-flux-error", "InfluxDB Flux Query Error", "How to fix InfluxDB Flux query errors", "## Common Causes\n- Flux syntax error\n- Function not found\n- Import path wrong\n\n## How to Fix\n\n```flux\nimport \"csv\"\n\ncsv.from(data: \"...")\n  |> filter(fn: (r) => true)\n```\n\n## Examples\n\n```bash\ninflux query 'import \"date\" date.now()'\n```"),
    ("influxdb-influxql-error", "InfluxDB InfluxQL Error", "How to fix InfluxDB InfluxQL query errors", "## Common Causes\n- InfluxQL syntax error\n- Measurement not found in InfluxQL mode\n- Group by time interval too small\n\n## How to Fix\n\n```sql\nSELECT mean(\"value\") FROM \"cpu\" WHERE time > now() - 1h GROUP BY time(5m)\n```\n\n## Examples\n\n```bash\ninflux -database mydb -execute 'SHOW MEASUREMENTS'\n```"),
    ("influxdb-line-protocol-error", "InfluxDB Line Protocol Error", "How to fix InfluxDB line protocol syntax errors", "## Common Causes\n- Missing timestamp\n- Special characters in tag keys\n- Field value type mismatch\n\n## How to Fix\n\n```\nmeasurement,tag1=value1 field1=1.0 1609459200000000000\n```\n\n## Examples\n\n```bash\ncurl -X POST http://localhost:8086/api/v2/write?org=myorg&bucket=mybucket -d 'cpu,host=server01 value=0.5'\n```"),
    ("influxdb-subscription-error", "InfluxDB Subscription Error", "How to fix InfluxDB subscription errors", "## Common Causes\n- Subscription target unreachable\n- Subscription type mismatch\n- Network partition\n\n## How to Fix\n\n```bash\ninflux subscription list --org myorg\n```\n\n## Examples\n\n```bash\ninflux subscription create --org myorg --bucket mybucket --name sub1 --type any --host http://localhost:8089\n```"),
    ("influxdb-task-error", "InfluxDB Task Error", "How to fix InfluxDB task errors", "## Common Causes\n- Task script syntax error\n- Task permissions insufficient\n- Task scheduled too frequently\n\n## How to Fix\n\n```bash\ninflux task list --org myorg\n```\n\n## Examples\n\n```bash\ninflux task create --org myorg --name mytask --every 1h --flux 'from(bucket:\"mybucket\") |> range(start:-1h) |> aggregateWindow(every:1h, fn:mean) |> to(bucket:\"downsampled\", org:\"myorg\")'\n```"),
    ("influxdb-continuous-query-error", "InfluxDB Continuous Query Error", "How to fix InfluxDB continuous query errors", "## Common Causes\n- CQ syntax error\n- Target measurement does not exist\n- CQ running too frequently\n\n## How to Fix\n\n```sql\nCREATE CONTINUOUS QUERY \"cq_1h\" ON \"mydb\" BEGIN SELECT mean(\"value\") INTO \"cpu_1h\" FROM \"cpu\" GROUP BY time(1h) END\n```\n\n## Examples\n\n```bash\ninflux -execute 'SHOW CONTINUOUS QUERIES ON mydb'\n```"),
    ("influxdb-http-error", "InfluxDB HTTP API Error", "How to fix InfluxDB HTTP API errors", "## Common Causes\n- Wrong HTTP method\n- Missing Authorization header\n- Endpoint URL wrong\n\n## How to Fix\n\n```bash\ncurl -s http://localhost:8086/health\n```\n\n## Examples\n\n```bash\ncurl -s -H \"Authorization: Token YOUR_TOKEN\" http://localhost:8086/api/v2/ping\n```"),
    ("influxdb-backup-error", "InfluxDB Backup Error", "How to fix InfluxDB backup errors", "## Common Causes\n- Backup path not writable\n- Database locked during backup\n- Insufficient disk space\n\n## How to Fix\n\n```bash\ninflux backup /var/backups/influxdb --org myorg\n```\n\n## Examples\n\n```bash\ninflux backup /tmp/influx-backup --org myorg 2>&1\n```"),
    ("influxdb-restore-error", "InfluxDB Restore Error", "How to fix InfluxDB restore errors", "## Common Causes\n- Backup format incompatible\n- Database already exists\n- Permissions issue\n\n## How to Fix\n\n```bash\ninflux restore /var/backups/influxdb --org myorg\n```\n\n## Examples\n\n```bash\nls -la /var/backups/influxdb/\n```"),
    ("influxdb-gzip-error", "InfluxDB GZip Error", "How to fix InfluxDB GZip compression errors", "## Common Causes\n- Content-Encoding header wrong\n- GZip not enabled on client\n- Corrupted compressed payload\n\n## How to Fix\n\n```bash\ncurl -X POST http://localhost:8086/api/v2/write?org=myorg&bucket=mybucket \\n  -H \"Authorization: Token YOUR_TOKEN\" \\n  -H \"Content-Encoding: gzip\" \\n  --data-binary @data.gz\n```\n\n## Examples\n\n```bash\ngzip -c data.txt | curl -X POST http://localhost:8086/api/v2/write?org=myorg&bucket=mybucket \\n  -H \"Authorization: Token YOUR_TOKEN\" -H \"Content-Encoding: gzip\" --data-binary @-\n```"),
    ("influxdb-cardinality-error", "InfluxDB High Cardinality Error", "How to fix InfluxDB high cardinality errors", "## Common Causes\n- Too many unique tag combinations\n- Tag values too granular (user IDs, request IDs)\n- Schema design issue\n\n## How to Fix\n\n```flux\nimport \"influxdata/influxdb/schema\"\nschema.measurementTagKeys(bucket: \"mybucket\", measurement: \"cpu\")\n```\n\n## Examples\n\n```bash\ninflux query 'import \"influxdata/influxdb/schema\" schema.measurementTagCardinality(bucket: \"mybucket\", measurement: \"cpu\")'\n```"),
    ("influxdb-tsi-error", "InfluxDB TSI Error", "How to fix InfluxDB Time Series Index errors", "## Common Causes\n- TSI index corrupted\n- Index file missing\n- Disk full preventing index writes\n\n## How to Fix\n\n```bash\ninflux_inspect rebuild-tsi -datadir /var/lib/influxdb/data -waldir /var/lib/influxdb/wal\n```\n\n## Examples\n\n```bash\nls -la /var/lib/influxdb/data/mydb/*/index/\n```"),
    ("influxdb-csv-error", "InfluxDB CSV Export Error", "How to fix InfluxDB CSV export errors", "## Common Causes\n- Query result empty\n- CSV formatter not configured\n- Output path not writable\n\n## How to Fix\n\n```bash\ninflux query 'from(bucket:\"mybucket\") |> range(start:-1h) |> to(bucket:\"export\", org:\"myorg\")'\n```\n\n## Examples\n\n```bash\ninflux query --raw 'from(bucket:\"mybucket\") |> range(start:-1h) |> limit(n:5)' > output.csv\n```"),
    ("influxdb-monitor-error", "InfluxDB Monitor Error", "How to fix InfluxDB monitoring and alert errors", "## Common Causes\n- Monitor check not configured\n- Alert threshold wrong\n- Notification endpoint unreachable\n\n## How to Fix\n\n```ini\n[monitor]\nstore-enabled = true\nstore-database = \"_internal\"\n```\n\n## Examples\n\n```bash\ninflux query 'from(bucket:\"_internal\") |> range(start:-5m) |> filter(fn:(r) => r._measurement == \"write\")'\n```"),
    ("influxdb-meta-error", "InfluxDB Meta Error", "How to fix InfluxDB metadata errors", "## Common Causes\n- Meta directory corrupted\n- Cluster meta sync failure\n- Meta file permissions wrong\n\n## How to Fix\n\n```bash\nls -la /var/lib/influxdb/meta/\n```\n\n## Examples\n\n```bash\ninflux_inspect report /var/lib/influxdb/meta/\n```"),
    ("influxdb-tick-error", "InfluxDB TICKscript Error", "How to fix InfluxDB TICKscript errors", "## Common Causes\n- TICKscript syntax error\n- Kapacitor task failing\n- Alert lambda not defined\n\n## How to Fix\n\n```tickscript\nstream\n  |from()\n    .measurement('cpu')\n  |alert()\n    .crit(lambda: \"usage_idle\" < 10.0)\n```\n\n## Examples\n\n```bash\nkapacitor define myalert -type stream -tick myalert.tick\n```"),
    ("influxdb-telegraf-error", "InfluxDB Telegraf Error", "How to fix InfluxDB Telegraf agent errors", "## Common Causes\n- Telegraf config syntax error\n- Output plugin misconfigured\n- Input plugin permissions\n\n## How to Fix\n\n```toml\n[[outputs.influxdb_v2]]\n  urls = [\"http://localhost:8086\"]\n  token = \"YOUR_TOKEN\"\n  organization = \"myorg\"\n  bucket = \"mybucket\"\n```\n\n## Examples\n\n```bash\ntelegraf --config /etc/telegraf/telegraf.conf --test\n```"),
]

count = 0
for slug, title, desc, body in PAGES:
    if slug in EXISTING:
        continue
    path = os.path.join(BASE, f'{slug}.md')
    with open(path, 'w') as f:
        f.write(make_page(slug, title, desc, body))
    count += 1

print(f'Generated {count} new InfluxDB pages (total: {len(EXISTING) + count})')
