#!/usr/bin/env python3
"""Generate Neo4j error pages to reach 100+ total."""
import os

BASE = '/home/admin1/projects/ErrorCode.excellentwiki.com/content/tools/neo4j'
EXISTING = {f.replace('.md', '') for f in os.listdir(BASE) if f.endswith('.md')}

def make_page(slug, title, desc, body):
    return f'''---
title: "[Solution] {title}"
description: "{desc}"
tools: ["neo4j"]
error-types: ["tool-error"]
severities: ["error"]
---

{body}
'''

PAGES = [
    ("neo4j-cluster-failover-error", "Neo4j Cluster Failover Error", "How to fix Neo4j cluster failover errors", "## Common Causes\n\n- Leader election timeout\n- Network partition between core servers\n- Too few cores for consensus\n\n## How to Fix\n\n```cypher\nCALL dbms.cluster.overview()\n```\n\n## Examples\n\n```bash\nneo4j-adminserver status\n```"),
    ("neo4j-backup-restore-error", "Neo4j Backup Restore Error", "How to fix Neo4j backup and restore errors", "## Common Causes\n- Backup corrupted\n- Version mismatch between backup and restore\n- Disk space insufficient\n\n## How to Fix\n\n```bash\nneo4j-admin database backup mydb --to-path=/backup/\nneo4j-admin database restore mydb --from-path=/backup/mydb/\n```\n\n## Examples\n\n```bash\nls -la /backup/\n```"),
    ("neo4j-page-cache-miss-error", "Neo4j Page Cache Miss Error", "How to fix Neo4j page cache miss errors", "## Common Causes\n\n- Page cache too small\n- Data larger than allocated cache\n- Cache eviction rate too high\n\n## How to Fix\n\n```ini\nserver.memory.pagecache.size=1G\n```\n\n## Examples\n\n```cypher\nCALL dbms.listConfig() YIELD name, value WHERE name = 'dbms.memory.pagecache.size'\n```"),
    ("neo4j-wal-replay-error", "Neo4j WAL Replay Error", "How to fix Neo4j WAL replay errors", "## Common Causes\n\n- WAL file corrupted\n- WAL directory not writable\n- Crash during WAL flush\n\n## How to Fix\n\n```bash\nls -la /var/lib/neo4j/data/transactions/\n```\n\n## Examples\n\n```bash\nneo4j-admin database info mydb\n```"),
    ("neo4j-disk-space-error", "Neo4j Disk Space Error", "How to fix Neo4j disk space errors", "## Common Causes\n\n- Transaction log growth\n- Store files growing unbounded\n- Temp files not cleaned\n\n## How to Fix\n\n```ini\ndbms.tx_log.rotation.size=100M\n```\n\n## Examples\n\n```bash\ndu -sh /var/lib/neo4j/data/databases/mydb/\n```"),
    ("neo4j-id-type-error", "Neo4j ID Type Error", "How to fix Neo4j ID type errors in queries", "## Common Causes\n\n- Using internal ID after store switch\n- ID type mismatch in parameters\n- Deprecated ID() function usage\n\n## How to Fix\n\n```cypher\nMATCH (n) WHERE n.myId = $id RETURN n\n```\n\n## Examples\n\n```cypher\nCREATE CONSTRAINT FOR (n:Person) REQUIRE n.myId IS UNIQUE\n```"),
    ("neo4j-temp-index-error", "Neo4j Temp Index Error", "How to fix Neo4j temporal index errors", "## Common Causes\n\n- Temporal value format wrong\n- Index not created for temporal field\n- Timezone mismatch\n\n## How to Fix\n\n```cypher\nCREATE INDEX FOR (n:Event) ON (n.timestamp)\n```\n\n## Examples\n\n```cypher\nMATCH (n:Event) WHERE n.timestamp > datetime() - duration('PT1H') RETURN n\n```"),
    ("neo4j-spatial-index-error", "Neo4j Spatial Index Error", "How to fix Neo4j spatial index errors", "## Common Causes\n\n- Point type not indexed\n- Wrong coordinate system\n- Bounding box query too large\n\n## How to Fix\n\n```cypher\nCREATE POINT INDEX FOR (n:Location) ON (n.point)\n```\n\n## Examples\n\n```cypher\nMATCH (n:Location) WHERE point.distance(n.point, point({latitude: 51.5, longitude: -0.1})) < 1000 RETURN n\n```"),
    ("neo4j-text-index-error", "Neo4j Full-Text Index Error", "How to fix Neo4j full-text index errors", "## Common Causes\n\n- Full-text index not created\n- Analyzer mismatch\n- Query syntax wrong for full-text search\n\n## How to Fix\n\n```cypher\nCREATE FULLTEXT INDEX mytextindex FOR (n:Person) ON EACH [n.name, n.bio]\n```\n\n## Examples\n\n```cypher\nCALL db.index.fulltext.queryNodes('mytextindex', 'search term') YIELD node, score\n```"),
    ("neo4j-vector-index-error", "Neo4j Vector Index Error", "How to fix Neo4j vector index errors", "## Common Causes\n\n- Vector dimension mismatch\n- Index not built for vector field\n- Similarity metric wrong\n\n## How to Fix\n\n```cypher\nCREATE VECTOR INDEX myvec FOR (n:Item) ON (n.embedding) OPTIONS {indexConfig: {`vector.dimensions`: 1536, `vector.similarity_function`: 'cosine'}}\n```\n\n## Examples\n\n```cypher\nCALL db.index.vector.queryNodes('myvec', 10, $queryVector) YIELD node, score\n```"),
    ("neo4j-uuid-error", "Neo4j UUID Error", "How to fix Neo4j UUID generation and constraint errors", "## Common Causes\n\n- UUID not generated on create\n- UUID constraint not unique\n- UUID format invalid\n\n## How to Fix\n\n```cypher\nCREATE CONSTRAINT FOR (n:Person) REQUIRE n.uuid IS UNIQUE\n```\n\n## Examples\n\n```cypher\nCREATE (n:Person {uuid: randomUUID(), name: 'Alice'})\n```"),
    ("neo4j-list-index-error", "Neo4j List Index Error", "How to fix Neo4j list index out of bounds errors", "## Common Causes\n- Accessing index beyond list length\n- Empty list access\n- Negative index\n\n## How to Fix\n\n```cypher\nMATCH (n) WHERE size(n.tags) > 0 RETURN n.tags[0]\n```\n\n## Examples\n\n```cypher\nMATCH (n) RETURN CASE WHEN size(n.items) > 2 THEN n.items[2] ELSE null END\n```"),
    ("neo4j-pattern-match-error", "Neo4j Pattern Match Error", "How to fix Neo4j pattern matching errors", "## Common Causes\n- Variable length path too long\n- Pattern not matching expected data\n- Cartesian product from disconnected patterns\n\n## How to Fix\n\n```cypher\nMATCH (a:Person)-[:KNOWS*1..3]->(b:Person) WHERE a.name = 'Alice' RETURN b\n```\n\n## Examples\n\n```cypher\nPROFILE MATCH (a)-[:KNOWS]->(b) RETURN count(*)\n```"),
    ("neo4j-explain-error", "Neo4j Query Plan Error", "How to fix Neo4j query execution plan errors", "## Common Causes\n- Wrong index chosen by planner\n- Full scan instead of index scan\n- Missing statistics\n\n## How to Fix\n\n```cypher\nEXPLAIN MATCH (n:Person {name: 'Alice'}) RETURN n\n```\n\n## Examples\n\n```cypher\nCALL dbms.queryJProfiler()\n```"),
    ("neo4j-foreach-error", "Neo4j Foreach Error", "How to fix Neo4j FOREACH clause errors", "## Common Causes\n- FOREACH not allowed in MATCH RETURN\n- Variable scope issue\n- Empty list in FOREACH\n\n## How to Fix\n\n```cypher\nMATCH (n:Person) FOREACH (tag IN n.tags | CREATE (n)-[:HAS_TAG]->(:Tag {name: tag}))\n```\n\n## Examples\n\n```cypher\nMATCH (n:Person) WHERE n.name = 'Alice' FOREACH (i IN range(1,3) | CREATE (n)-[:REL]->(:Node {val: i}))\n```"),
    ("neo4j-apoc-periodic-error", "Neo4j APOC Periodic Error", "How to fix Neo4j APOC periodic iteration errors", "## Common Causes\n- Batch size too large\n- APOC not installed\n- Transaction timeout during iteration\n\n## How to Fix\n\n```cypher\nCALL apoc.periodic.iterate('MATCH (n:Person) RETURN n', 'SET n.processed = true', {batchSize: 1000})\n```\n\n## Examples\n\n```cypher\nCALL apoc.periodic.list()\n```"),
    ("neo4j-apoc-refactor-error", "Neo4j APOC Refactor Error", "How to fix Neo4j APOC node/relationship refactor errors", "## Common Causes\n- Node has relationships that prevent deletion\n- Refactor creates duplicate nodes\n- Label or property name collision\n\n## How to Fix\n\n```cypher\nCALL apoc.refactor.rename.type('OLD_REL', 'NEW_REL')\n```\n\n## Examples\n\n```cypher\nCALL apoc.refactor.cloneNodes([nodeId1, nodeId2])\n```"),
    ("neo4j-apoc-load-csv-error", "Neo4j APOC Load CSV Error", "How to fix Neo4j APOC CSV loading errors", "## Common Causes\n- File not accessible from server\n- CSV format wrong\n- URL not whitelisted\n\n## How to Fix\n\n```ini\ndbms.security.procedures.unrestricted=apoc.load.*\n```\n\n## Examples\n\n```cypher\nCALL apoc.load.csv('file:///data.csv') YIELD row RETURN row\n```"),
    ("neo4j-apoc-convert-error", "Neo4j APOC Convert Error", "How to fix Neo4j APOC type conversion errors", "## Common Causes\n- Value cannot be converted to target type\n- Null value in conversion\n- Format string mismatch\n\n## How to Fix\n\n```cypher\nRETURN apoc.convert.toJson({name: 'Alice', age: 30})\n```\n\n## Examples\n\n```cypher\nRETURN apoc.convert.toSet([1, 2, 2, 3])\n```"),
    ("neo4j-apoc-date-error", "Neo4j APOC Date Error", "How to fix Neo4j APOC date parsing errors", "## Common Causes\n- Date format not matching parser pattern\n- Invalid date value\n- Timezone not specified\n\n## How to Fix\n\n```cypher\nRETURN apoc.date.parse('2024-01-15', 'ms', 'yyyy-MM-dd')\n```\n\n## Examples\n\n```cypher\nRETURN apoc.date.format(timestamp(), 'ms', 'yyyy-MM-dd HH:mm:ss')\n```"),
    ("neo4j-apoc-xml-error", "Neo4j APOC XML Error", "How to fix Neo4j APOC XML processing errors", "## Common Causes\n- XML malformed\n- XPath expression wrong\n- Namespace not registered\n\n## How to Fix\n\n```cypher\nCALL apoc.load.xml('file:///data.xml') YIELD doc RETURN doc\n```\n\n## Examples\n\n```cypher\nRETURN apoc.xml.parse('<root><item id=\"1\"/>')\n```"),
    ("neo4j-apoc-json-error", "Neo4j APOC JSON Error", "How to fix Neo4j APOC JSON processing errors", "## Common Causes\n- JSON malformed\n- JSON path expression wrong\n- Nested depth too deep\n\n## How to Fix\n\n```cypher\nRETURN apoc.json.toJson({name: 'Alice', nested: {key: 'value'}})\n```\n\n## Examples\n\n```cypher\nCALL apoc.json.path('$.store.book[*].author', $jsonString)\n```"),
    ("neo4j-apoc-uuid-error", "Neo4j APOC UUID Error", "How to fix Neo4j APOC UUID generation errors", "## Common Causes\n- APOC UUID procedure not found\n- UUID format not as expected\n- Duplicate UUIDs generated\n\n## How to Fix\n\n```cypher\nCREATE (n:Person {uuid: apoc.create.uuid()})\n```\n\n## Examples\n\n```cypher\nRETURN apoc.create.uuid()\n```"),
    ("neo4j-apoc-path-error", "Neo4j APOC Path Error", "How to fix Neo4j APOC path finding errors", "## Common Causes\n- Path finder takes too long\n- No path found\n- Wrong relationship filter\n\n## How to Fix\n\n```cypher\nMATCH (a:Person {name: 'Alice'}), (b:Person {name: 'Bob'})\nCALL apoc.path.findShortestPaths(a, b, 'KNOWS') YIELD path RETURN path\n```\n\n## Examples\n\n```cypher\nCALL apoc.path.expandConfig('startNode', {relationshipFilter: 'KNOWS', limit: 10})\n```"),
    ("neo4j-apoc-async-error", "Neo4j APOC Async Error", "How to fix Neo4j APOC async procedure errors", "## Common Causes\n- Async task queue full\n- Task timed out\n- Callback function error\n\n## How to Fix\n\n```cypher\nCALL apoc.periodic.iterate('MATCH (n:Person) RETURN n', 'DETACH DELETE n', {async: true})\n```\n\n## Examples\n\n```cypher\nCALL apoc.periodic.list()\n```"),
    ("neo4j-apoc-occ-error", "Neo4j APOC OC (OpenCypher) Error", "How to fix Neo4j APOC openCypher compatibility errors", "## Common Causes\n- OpenCypher syntax not supported\n- Procedure expects different input type\n- Version mismatch between APOC and Neo4j\n\n## How to Fix\n\n```cypher\nCALL apoc.merge.node(['Person'], {name: 'Alice'}, {created: datetime()}) YIELD node RETURN node\n```\n\n## Examples\n\n```cypher\nCALL dbms.procedures() YIELD name WHERE name STARTS WITH 'apoc.merge'\n```"),
    ("neo4j-apoc-config-error", "Neo4j APOC Configuration Error", "How to fix Neo4j APOC configuration errors", "## Common Causes\n- APOC not in plugins directory\n- Version mismatch\n- Missing APOC config entries\n\n## How to Fix\n\n```ini\ndbms.security.procedures.unrestricted=apoc.*\n```\n\n## Examples\n\n```bash\nls /var/lib/neo4j/plugins/apoc*.jar\n```"),
    ("neo4j-apoc-transaction-error", "Neo4j APOC Transaction Error", "How to fix Neo4j APOC transaction function errors", "## Common Causes\n- Transaction function not registered\n- Timeout during transaction function\n- Rollback in transaction function\n\n## How to Fix\n\n```cypher\nCALL apoc.tx.run('MATCH (n:Person) RETURN count(n)', {}) YIELD result\n```\n\n## Examples\n\n```cypher\nCALL dbms.procedures() YIELD name WHERE name = 'apoc.tx.run'\n```"),
    ("neo4j-apoc-schema-error", "Neo4j APOC Schema Error", "How to fix Neo4j APOC schema procedure errors", "## Common Causes\n- Schema procedure not found\n- Index not yet available\n- Constraint not applied\n\n## How to Fix\n\n```cypher\nCALL apoc.schema.assert({Person: ['name']}, {Friend: ['since']})\n```\n\n## Examples\n\n```cypher\nCALL db.indexes() YIELD labelsOrTypes, properties\n```"),
]

count = 0
for slug, title, desc, body in PAGES:
    if slug in EXISTING:
        continue
    path = os.path.join(BASE, f'{slug}.md')
    with open(path, 'w') as f:
        f.write(make_page(slug, title, desc, body))
    count += 1

print(f'Generated {count} new Neo4j pages (total: {len(EXISTING) + count})')
