#!/usr/bin/env python3
"""Generate new npm error pages"""
import os, sys

EXISTING = {f.replace('.md', '') for f in os.listdir('/home/admin1/projects/ErrorCode.excellentwiki.com/content/tools/npm/') if f.endswith('.md')}

PAGES_DATA = [
    ("npm-install-eacces", "npm install EACCES permission denied",
     "Fix npm 'EACCES permission denied' error. Resolve permission issues when installing npm packages globally or locally.",
     "EACCES: permission denied, access '/usr/local/lib/node_modules'\n\nThis error occurs when npm does not have write permissions to the installation directory. Global installs typically require root or proper user permissions."),
    ("npm-install-eexist", "npm install EEXIST file exists",
     "Fix npm 'EEXIST file exists' error. Resolve npm installation conflicts when a file already exists at the target path.",
     "EEXIST: file already exists\n\nThis error occurs when npm tries to create a file or symlink that already exists at the target location."),
    ("npm-install-enoent", "npm install ENOENT error",
     "Fix npm 'ENOENT' error. Resolve npm installation failures when a required file or directory does not exist.",
     "ENOENT: no such file or directory\n\nThis error occurs when npm cannot find a required file or directory during installation."),
    ("npm-install-enospc", "npm install ENOSPC no space left",
     "Fix npm 'ENOSPC no space left' error. Resolve npm installation failures due to insufficient disk space or inode exhaustion.",
     "ENOSPC: no space left on device\n\nThis error occurs when the filesystem has run out of disk space or inodes during npm operations."),
    ("npm-install-econnreset", "npm install ECONNRESET error",
     "Fix npm 'ECONNRESET' error. Resolve npm installation failures when the connection is reset by the remote server.",
     "ECONNRESET: connection reset by peer\n\nThis error occurs when the TCP connection to the npm registry is interrupted or reset by the server."),
    ("npm-install-ehostunreach", "npm install EHOSTUNREACH error",
     "Fix npm 'EHOSTUNREACH' error. Resolve npm installation failures when the registry host is unreachable.",
     "EHOSTUNREACH: no route to host\n\nThis error occurs when the npm registry server is unreachable from your network."),
    ("npm-install-enotfound", "npm install ENOTFOUND error",
     "Fix npm 'ENOTFOUND' error. Resolve npm DNS resolution failures when the registry hostname cannot be resolved.",
     "ENOTFOUND: getaddrinfo ENOTFOUND registry.npmjs.org\n\nThis error occurs when the DNS lookup for the npm registry fails."),
    ("npm-registry-timeout", "npm registry timeout error",
     "Fix npm registry timeout errors. Resolve slow or timed-out connections to the npm registry.",
     "ERR! network 'https://registry.npmjs.org/...' is not a valid npm registry\n\nThis error occurs when npm cannot connect to the registry within the timeout period."),
    ("npm-publish-e409", "npm publish E409 conflict",
     "Fix npm 'E409 conflict' error. Resolve npm publish failures when the package version already exists.",
     "npm ERR! 409 Conflict\n\nThis error occurs when you try to publish a package version that already exists in the registry."),
    ("npm-publish-e412", "npm publish E412 precondition failed",
     "Fix npm 'E412 precondition failed' error. Resolve npm publish failures due to unmet preconditions.",
     "npm ERR! 412 Precondition Failed\n\nThis error occurs when npm publish fails due to unmet preconditions like two-factor authentication requirements."),
    ("npm-publish-e429", "npm publish E429 rate limited",
     "Fix npm 'E429 rate limited' error. Resolve npm publish rate limiting issues.",
     "npm ERR! 429 Too Many Requests\n\nThis error occurs when you have exceeded the npm registry rate limit for publishing packages."),
    ("npm-publish-two-factor", "npm publish two-factor authentication error",
     "Fix npm 'two-factor authentication' error. Resolve npm publish failures requiring OTP codes.",
     "npm ERR! 403 Forbidden - PUT ... - requires a one-time password\n\nThis error occurs when publishing to a package that requires two-factor authentication."),
    ("npm-publish-totp-invalid", "npm publish invalid TOTP code",
     "Fix npm 'invalid TOTP code' error. Resolve npm publish failures due to incorrect one-time passwords.",
     "npm ERR! 401 Unauthorized - Invalid one-time password\n\nThis error occurs when the two-factor authentication OTP code is incorrect or expired."),
    ("npm-scope-not-allowed", "npm scope not allowed error",
     "Fix npm 'scope not allowed' error. Resolve publishing failures for unscoped packages that should be scoped.",
     "npm ERR! 403 Forbidden - You do not have permission to publish unscoped packages\n\nThis error occurs when your npm user account requires scoped packages."),
    ("npm-publish-name-too-similar", "npm publish name too similar error",
     "Fix npm 'package name too similar' error. Resolve publish failures when the package name resembles an existing package.",
     "npm ERR! 403 Forbidden - package name too similar to existing package\n\nThis error occurs when your package name is confusingly similar to an existing popular package."),
    ("npm-version-exists", "npm version already exists error",
     "Fix npm 'version already exists' error. Resolve failures when trying to publish a version that already exists.",
     "npm ERR! 403 Forbidden - version already exists\n\nThis error occurs when you try to publish a package version number that already exists in the registry."),
    ("npm-ls-cycle", "npm ls cycle detected error",
     "Fix npm 'cycle detected' error. Resolve circular dependency detection issues in the dependency tree.",
     "npm ERR! cycle detected: pkg1 -> pkg2 -> pkg3 -> pkg1\n\nThis error occurs when npm detects circular dependencies in your package tree."),
    ("npm-ls-extraneous", "npm ls extraneous package error",
     "Fix npm 'extraneous package' error. Resolve issues with packages installed but not in package.json.",
     "extraneous: package@version\n\nThis warning indicates a package is installed in node_modules but not listed in package.json."),
    ("npm-outdated-registry", "npm outdated registry error",
     "Fix npm 'outdated' registry error. Resolve failures when checking for outdated packages.",
     "npm ERR! code E404: Not Found\n\nThis error occurs when npm outdated cannot reach the registry or find a specific package."),
    ("npm-rebuild-failed", "npm rebuild failed error",
     "Fix npm 'rebuild failed' error. Resolve npm package rebuild failures for native modules.",
     "npm ERR! rebuild: <package> Failed to rebuild\n\nThis error occurs when npm cannot rebuild native modules, often due to missing build tools."),
    ("npm-uninstall-global", "npm uninstall global error",
     "Fix npm 'uninstall global' error. Resolve permission issues when uninstalling global packages.",
     "npm ERR! Error: EACCES: permission denied, unlink '/usr/local/lib/node_modules/<package>'\n\nThis error occurs when trying to uninstall a global package without sufficient permissions."),
    ("npm-install-shrinkwrap", "npm install shrinkwrap conflict",
     "Fix npm 'shrinkwrap conflict' error. Resolve npm-shrinkwrap.json and package-lock.json conflicts.",
     "npm ERR! Found: package@version\nnpm ERR! node_modules/package\nnpm ERR! package.json: package@other-version\n\nThis error occurs when the shrinkwrap file conflicts with package.json."),
    ("npm-ci-version-mismatch", "npm ci version mismatch error",
     "Fix npm 'ci version mismatch' error. Resolve npm CI failures when package-lock.json does not match package.json.",
     "npm ERR! cipm: CI can't install: package-lock.json and package.json don't match\n\nThis error occurs when the package-lock.json is out of sync with package.json."),
    ("npm-install-git-dependency", "npm install git dependency error",
     "Fix npm 'git dependency' error. Resolve failures when installing packages from Git repositories.",
     "npm ERR! git clone <url>: remote: Repository not found\n\nThis error occurs when npm cannot clone a Git repository specified as a dependency."),
    ("npm-install-tarball", "npm install tarball error",
     "Fix npm 'tarball' error. Resolve issues when installing packages from tarball URLs.",
     "npm ERR! tarball download failed: <url>\n\nThis error occurs when npm cannot download or extract a package tarball."),
    ("npm-install-unsupported-platform", "npm install unsupported platform error",
     "Fix npm 'unsupported platform' error. Resolve installation failures due to operating system or architecture incompatibility.",
     "npm WARN notsup Unsupported platform: package@version: wanted {os: \"darwin\"}, current: {os: \"linux\"}\n\nThis warning indicates the package does not support the current operating system."),
    ("npm-install-blocked-by-npmrc", "npm install blocked by .npmrc error",
     "Fix npm 'blocked by .npmrc' error. Resolve installation failures caused by restrictive npm configuration.",
     "npm ERR! 403 Forbidden - Public registration is not allowed\n\nThis error occurs when .npmrc restricts package installations to a specific registry."),
    ("npm-install-self-signed-cert", "npm install self-signed certificate error",
     "Fix npm 'self-signed certificate' error. Resolve SSL certificate verification failures when using custom registries.",
     "npm ERR! code ERR_TLS_CERT_ALTNAME_INVALID\n\nThis error occurs when the SSL certificate of the npm registry is self-signed or invalid."),
    ("npm-install-strict-ssl", "npm install strict-ssl error",
     "Fix npm 'strict-ssl' error. Resolve npm SSL verification failures behind corporate proxies.",
     "npm ERR! code ECONNRESET\nnpm ERR! errno ECONNRESET\n\nThis error can occur when strict-ssl verification fails behind a corporate proxy."),
    ("npm-config-env-error", "npm config environment error",
     "Fix npm 'config environment' error. Resolve npm configuration issues caused by environment variables.",
     "npm ERR! config Cannot determine config type for <key>\n\nThis error occurs when environment variables override npm configurations with invalid values."),
    ("npm-config-proxy-error", "npm config proxy error",
     "Fix npm 'proxy' configuration error. Resolve npm connectivity issues through HTTP/HTTPS proxies.",
     "npm ERR! code ECONNREFUSED\n\nThis error can occur when the configured proxy server refuses the connection."),
    ("npm-ping-error", "npm ping error",
     "Fix npm 'ping' error. Resolve npm registry connectivity testing failures.",
     "npm ERR! code E404\nnpm ERR! 404 Not Found: registry.npmjs.org\n\nThis error occurs when npm cannot reach the registry to verify connectivity."),
    ("npm-access-ls-collaborators", "npm access ls-collaborators error",
     "Fix npm 'access ls-collaborators' error. Resolve permission errors when listing package collaborators.",
     "npm ERR! 403 Forbidden - You do not have permission to list collaborators\n\nThis error occurs when you do not have read access to the package's collaborator list."),
    ("npm-access-grant-error", "npm access grant error",
     "Fix npm 'access grant' error. Resolve failures when granting access permissions to packages.",
     "npm ERR! 403 Forbidden - You do not have permission to set permissions\n\nThis error occurs when you are not a maintainer of the package with sufficient permissions."),
    ("npm-access-revoke-error", "npm access revoke error",
     "Fix npm 'access revoke' error. Resolve failures when revoking access permissions from packages.",
     "npm ERR! 404 Not Found - User not found\n\nThis error occurs when the user specified for access revocation does not exist."),
    ("npm-team-create", "npm team create error",
     "Fix npm 'team create' error. Resolve npm team creation failures.",
     "npm ERR! 403 Forbidden - You do not have permission to create teams\n\nThis error occurs when your npm account does not have the required permissions to create teams."),
    ("npm-team-add", "npm team add error",
     "Fix npm 'team add' error. Resolve failures when adding users to npm teams.",
     "npm ERR! 404 Not Found - Team not found\n\nThis error occurs when the specified npm team does not exist."),
    ("npm-team-rm", "npm team rm error",
     "Fix npm 'team rm' error. Resolve failures when removing users from npm teams.",
     "npm ERR! 403 Forbidden - You do not have permission to remove users\n\nThis error occurs when you are not a team admin."),
    ("npm-team-ls", "npm team ls error",
     "Fix npm 'team ls' error. Resolve failures when listing npm team members.",
     "npm ERR! 404 Not Found - Team not found\n\nThis error occurs when the specified team does not exist or you lack permissions."),
    ("npm-owner-add", "npm owner add error",
     "Fix npm 'owner add' error. Resolve failures when adding package owners.",
     "npm ERR! 403 Forbidden - You are not a package owner\n\nThis error occurs when you are not a current owner of the package."),
    ("npm-owner-rm", "npm owner rm error",
     "Fix npm 'owner rm' error. Resolve failures when removing package owners.",
     "npm ERR! 403 Forbidden - Cannot remove the last owner\n\nThis error occurs when you try to remove the last owner of a package."),
    ("npm-owner-ls", "npm owner ls error",
     "Fix npm 'owner ls' error. Resolve failures when listing package owners.",
     "npm ERR! 404 Not Found - Package not found\n\nThis error occurs when the specified package does not exist."),
    ("npm-access-public", "npm access public error",
     "Fix npm 'access public' error. Resolve failures when making a package public.",
     "npm ERR! 403 Forbidden - Public packages cannot be made public\n\nThis error occurs when the package is already public."),
    ("npm-access-restricted", "npm access restricted error",
     "Fix npm 'access restricted' error. Resolve failures when restricting package access.",
     "npm ERR! 403 Forbidden - You do not have permission to restrict access\n\nThis error occurs when you are not a package maintainer."),
    ("npm-star-error", "npm star error",
     "Fix npm 'star' error. Resolve failures when starring npm packages.",
     "npm ERR! 404 Not Found - Package not found\n\nThis error occurs when the package you are trying to star does not exist."),
    ("npm-unstar-error", "npm unstar error",
     "Fix npm 'unstar' error. Resolve failures when unstarring npm packages.",
     "npm ERR! 404 Not Found - Package not found\n\nThis error occurs when the package you are trying to unstar does not exist."),
    ("npm-hook-create", "npm hook create error",
     "Fix npm 'hook create' error. Resolve failures when creating npm webhooks.",
     "npm ERR! 422 Unprocessable Entity - Invalid hook URL\n\nThis error occurs when the webhook URL provided is invalid."),
    ("npm-hook-rm", "npm hook rm error",
     "Fix npm 'hook rm' error. Resolve failures when removing npm webhooks.",
     "npm ERR! 404 Not Found - Hook not found\n\nThis error occurs when the specified webhook does not exist."),
    ("npm-hook-ls", "npm hook ls error",
     "Fix npm 'hook ls' error. Resolve failures when listing npm webhooks.",
     "npm ERR! 404 Not Found - No hooks found\n\nThis error occurs when there are no hooks configured for your packages."),
    ("npm-hook-update", "npm hook update error",
     "Fix npm 'hook update' error. Resolve failures when updating npm webhooks.",
     "npm ERR! 404 Not Found - Hook not found\n\nThis error occurs when the specified webhook does not exist."),
    ("npm-dist-tag-add", "npm dist-tag add error",
     "Fix npm 'dist-tag add' error. Resolve failures when adding distribution tags to package versions.",
     "npm ERR! 403 Forbidden - You are not a package maintainer\n\nThis error occurs when you do not have permission to add tags to the package."),
    ("npm-dist-tag-rm", "npm dist-tag rm error",
     "Fix npm 'dist-tag rm' error. Resolve failures when removing distribution tags.",
     "npm ERR! 404 Not Found - Tag not found\n\nThis error occurs when the specified distribution tag does not exist."),
    ("npm-dist-tag-ls", "npm dist-tag ls error",
     "Fix npm 'dist-tag ls' error. Resolve failures when listing distribution tags.",
     "npm ERR! 404 Not Found - Package not found\n\nThis error occurs when the specified package does not exist."),
    ("npm-deprecate-error", "npm deprecate error",
     "Fix npm 'deprecate' error. Resolve failures when deprecating package versions.",
     "npm ERR! 403 Forbidden - You are not a package maintainer\n\nThis error occurs when you do not have permission to deprecate the package."),
    ("npm-org-create", "npm org create error",
     "Fix npm 'org create' error. Resolve failures when creating npm organizations.",
     "npm ERR! 403 Forbidden - Organization name already taken\n\nThis error occurs when the organization name is already in use."),
    ("npm-org-rm", "npm org rm error",
     "Fix npm 'org rm' error. Resolve failures when removing npm organizations.",
     "npm ERR! 403 Forbidden - You are not the organization owner\n\nThis error occurs when you do not have permissions to delete the organization."),
    ("npm-org-ls", "npm org ls error",
     "Fix npm 'org ls' error. Resolve failures when listing npm organization members.",
     "npm ERR! 404 Not Found - Organization not found\n\nThis error occurs when the specified organization does not exist."),
    ("npm-token-create", "npm token create error",
     "Fix npm 'token create' error. Resolve failures when creating npm authentication tokens.",
     "npm ERR! 401 Unauthorized - Login first\n\nThis error occurs when you are not logged in to npm before creating a token."),
    ("npm-token-rm", "npm token rm error",
     "Fix npm 'token rm' error. Resolve failures when removing npm authentication tokens.",
     "npm ERR! 404 Not Found - Token not found\n\nThis error occurs when the specified token does not exist."),
    ("npm-token-ls", "npm token ls error",
     "Fix npm 'token ls' error. Resolve failures when listing npm authentication tokens.",
     "npm ERR! 401 Unauthorized - Login first\n\nThis error occurs when you are not logged in."),
    ("npm-search-parse", "npm search parse error",
     "Fix npm 'search parse' error. Resolve npm search failures caused by invalid search syntax.",
     "npm ERR! search failed with error: Invalid search term\n\nThis error occurs when the search query contains invalid syntax."),
    ("npm-pack-error-v2", "npm pack error",
     "Fix npm 'pack' error. Resolve failures when creating npm package tarballs.",
     "npm ERR! code E404: Not Found\n\nThis error can occur when npm pack cannot find required files."),
    ("npm-install-link", "npm install link error",
     "Fix npm 'install link' error. Resolve issues with npm link and symlinked packages.",
     "npm ERR! code ELOOP: too many symbolic links encountered\n\nThis error occurs when npm encounters circular or excessive symlinks."),
    ("npm-npx-outdated", "npm npx outdated package error",
     "Fix npm 'npx outdated' error. Resolve npx execution failures when a cached package version is outdated.",
     "npx: cached version is outdated\n\nThis warning occurs when the locally cached version of a package is older than the registry version."),
    ("npm-exec-no-cache", "npm exec no cache error",
     "Fix npm 'exec no cache' error. Resolve npx/npm exec failures when packages cannot be fetched.",
     "npm ERR! could not determine executable to run\n\nThis error occurs when npm exec cannot determine which package to execute."),
    ("npm-install-bundle", "npm install bundle error",
     "Fix npm 'bundle' error. Resolve issues with bundled dependencies in npm packages.",
     "npm WARN bundledDependencies: package@version: dependency not found in package.json\n\nThis warning occurs when bundledDependencies references packages not in package.json."),
    ("npm-install-optional", "npm install optional dep error",
     "Fix npm 'optional dependency' error. Resolve optional dependency installation failures.",
     "npm WARN optional SKIPPING OPTIONAL DEPENDENCY: package@version\n\nThis warning occurs when an optional dependency fails to install."),
    ("npm-install-dev", "npm install dev dependency error",
     "Fix npm 'dev dependency' error. Resolve dev dependency installation issues.",
     "npm ERR! code E404: Not Found\n\nThis error occurs when a dev dependency package does not exist."),
    ("npm-install-bin", "npm install binary link error",
     "Fix npm 'binary link' error. Resolve failures when npm creates binary symlinks.",
     "npm ERR! EEXIST: file already exists, symlink\n\nThis error occurs when a binary symlink conflicts with an existing file."),
    ("npm-install-legacy-peer", "npm install legacy peer deps error",
     "Fix npm 'legacy peer deps' error. Resolve peer dependency conflicts using legacy resolution.",
     "npm ERR! Could not resolve dependency:\nnpm ERR! peer dep missing\n\nThis error occurs when peer dependencies cannot be resolved automatically."),
    ("npm-install-override", "npm install override error",
     "Fix npm 'override' error. Resolve issues with npm overrides configuration.",
     "npm ERR! Invalid override for <package>: version <ver> not found\n\nThis error occurs when an override specifies a version that does not exist."),
    ("npm-audit-signatures", "npm audit signatures error",
     "Fix npm 'audit signatures' error. Resolve npm audit failures when package signatures cannot be verified.",
     "npm ERR! audit: Signature verification failed\n\nThis error occurs when npm cannot verify the cryptographic signature of a package."),
    ("npm-cache-verify", "npm cache verify error",
     "Fix npm 'cache verify' error. Resolve npm cache integrity verification failures.",
     "npm ERR! cache verify failed: content checksum mismatch\n\nThis error occurs when cached package content has been corrupted."),
    ("npm-clean-cache", "npm clean cache error",
     "Fix npm 'clean cache' error. Resolve issues when clearing npm cache.",
     "npm ERR! cache clean: unable to remove directory\n\nThis error occurs when npm cannot remove the cache directory."),
    ("npm-install-package-lock", "npm install package-lock error",
     "Fix npm 'package-lock' error. Resolve issues with package-lock.json file generation.",
     "npm ERR! error: package-lock.json: <description>\n\nThis error occurs when package-lock.json has conflicts or invalid entries."),
    ("npm-ci-offline", "npm ci offline error",
     "Fix npm 'ci offline' error. Resolve npm CI failures when packages are not cached.",
     "npm ERR! code EOFFLINE: Can not install in offline mode, no cache\n\nThis error occurs when running npm ci with --offline but packages are not cached."),
    ("npm-dedupe", "npm dedupe error",
     "Fix npm 'dedupe' error. Resolve npm package deduplication issues.",
     "npm ERR! code EDEDUPE: Cannot dedupe\n\nThis error occurs when npm cannot deduplicate packages due to conflicting version requirements."),
    ("npm-install-not-found-error", "npm install E404 package not found",
     "Fix npm 'E404 package not found' error. Resolve npm install failures when a package does not exist in the registry.",
     "npm ERR! 404 Not Found - GET https://registry.npmjs.org/<package>\n\nThis error occurs when the specified package does not exist in the npm registry."),
    ("npm-install-server-error", "npm install 5xx server error",
     "Fix npm '5xx server error' during install. Resolve npm registry server-side failures.",
     "npm ERR! 5xx Server Error: npm ERR! code E500\n\nThis error occurs when the npm registry returns a server error (500, 502, 503)."),
    ("npm-install-rollback", "npm install rollback error",
     "Fix npm 'rollback' error. Resolve npm install failures that trigger automatic rollback.",
     "npm ERR! rollback failed removing <package>\n\nThis error occurs when npm fails to roll back changes after a failed installation."),
    ("npm-update-package", "npm update error",
     "Fix npm 'update' error. Resolve failures when updating npm packages to newer versions.",
     "npm ERR! code E404: Package not found\n\nThis error can occur when npm update cannot find the latest version of a package."),
    ("npm-build-script", "npm build script error",
     "Fix npm 'build script' error. Resolve failures in package build scripts.",
     "npm ERR! code ELIFECYCLE\nnpm ERR! errno <n>\n\nThis error occurs when a build script exits with a non-zero exit code."),
    ("npm-postinstall-script", "npm postinstall script error",
     "Fix npm 'postinstall script' error. Resolve failures in postinstall scripts.",
     "npm ERR! Failed at the <package>@<version> postinstall script.\n\nThis error occurs when the postinstall script fails to execute."),
    ("npm-prestart-script", "npm prestart script error",
     "Fix npm 'prestart script' error. Resolve failures in prestart lifecycle scripts.",
     "npm ERR! Failed at the <package>@<version> prestart script.\n\nThis error occurs when the prestart script exits with an error."),
    ("npm-custom-script", "npm custom script error",
     "Fix npm 'custom script' error. Resolve failures when running custom npm scripts.",
     "npm ERR! missing script: <name>\n\nThis error occurs when the specified npm script is not defined in package.json."),
    ("npm-script-env", "npm script environment error",
     "Fix npm 'script environment' error. Resolve npm script execution environment issues.",
     "npm ERR! env: node: No such file or directory\n\nThis error occurs when Node.js is not available in the PATH during script execution."),
    ("npm-publish-count", "npm publish count limit error",
     "Fix npm 'publish count limit' error. Resolve npm registry rate limiting for package publishes.",
     "npm ERR! 429 Too Many Requests - You have exceeded the number of publishes per hour\n\nThis error occurs when you exceed the npm publish rate limit."),
    ("npm-profile-update", "npm profile update error",
     "Fix npm 'profile update' error. Resolve failures when updating npm profile settings.",
     "npm ERR! 401 Unauthorized - Login first\n\nThis error occurs when you are not logged in."),
    ("npm-profile-enable-2fa", "npm profile enable 2fa error",
     "Fix npm 'enable 2fa' error. Resolve failures when enabling two-factor authentication.",
     "npm ERR! 409 Conflict - Two-factor authentication already enabled\n\nThis error occurs when 2FA is already enabled on your account."),
    ("npm-profile-disable-2fa", "npm profile disable 2fa error",
     "Fix npm 'disable 2fa' error. Resolve failures when disabling two-factor authentication.",
     "npm ERR! 401 Unauthorized - Invalid password\n\nThis error occurs when the password provided does not match."),
    ("npm-find-dupes", "npm find-dupes error",
     "Fix npm 'find-dupes' error. Resolve duplicate package detection failures.",
     "npm WARN deprecated: package@version\n\nThis warning appears when find-dupes detects duplicate packages in node_modules."),
    ("npm-query", "npm query error",
     "Fix npm 'query' error. Resolve failures when querying package metadata.",
     "npm ERR! Failed to parse query: <query>\n\nThis error occurs when the query syntax is invalid."),
    ("npm-explore", "npm explore error",
     "Fix npm 'explore' error. Resolve failures when exploring package contents.",
     "npm ERR! package not found: <package>\n\nThis error occurs when the specified package is not installed."),
    ("npm-bugs", "npm bugs error",
     "Fix npm 'bugs' error. Resolve failures when opening package bug trackers.",
     "npm ERR! no bugs URL\n\nThis error occurs when the package does not specify a bugs URL."),
    ("npm-repo", "npm repo error",
     "Fix npm 'repo' error. Resolve failures when opening package repository URLs.",
     "npm ERR! no repository URL\n\nThis error occurs when the package does not specify a repository URL."),
    ("npm-docs", "npm docs error",
     "Fix npm 'docs' error. Resolve failures when opening package documentation URLs.",
     "npm ERR! no homepage URL\n\nThis error occurs when the package does not specify a homepage URL."),
    ("npm-fund", "npm fund error",
     "Fix npm 'fund' error. Resolve failures when viewing package funding information.",
     "npm ERR! no funding information\n\nThis error occurs when the package does not specify funding information."),
    ("npm-view", "npm view error",
     "Fix npm 'view' error. Resolve failures when viewing package registry metadata.",
     "npm ERR! 404 Not Found - Package not found\n\nThis error occurs when the specified package does not exist in the registry."),
    ("npm-search-connection", "npm search connection error",
     "Fix npm 'search connection' error. Resolve npm search failures due to network issues.",
     "npm ERR! network: search failed: connection refused\n\nThis error occurs when npm cannot connect to the search endpoint."),
    ("npm-login-sso", "npm login SSO error",
     "Fix npm 'login SSO' error. Resolve single sign-on authentication failures.",
     "npm ERR! 401 Unauthorized - SSO authentication failed\n\nThis error occurs when SSO login fails."),
    ("npm-init-author-url", "npm init author URL error",
     "Fix npm 'init author URL' error. Resolve package.json field validation failures.",
     "npm ERR! Invalid author URL\n\nThis error occurs when the author URL in package.json is not a valid URL."),
    ("npm-init-git", "npm init git error",
     "Fix npm 'init git' error. Resolve failures when git initialization fails during npm init.",
     "npm ERR! git: failed to initialize git repository\n\nThis error occurs when npm cannot initialize a git repository for the new package."),
    ("npm-install-workspace", "npm install workspace error",
     "Fix npm 'workspace install' error. Resolve npm workspace installation issues.",
     "npm ERR! ERESOLVE unable to resolve dependency tree\n\nThis error occurs when workspace dependencies have conflicts."),
    ("npm-set-script", "npm set-script error",
     "Fix npm 'set-script' error. Resolve failures when adding scripts to package.json.",
     "npm ERR! package.json: failed to write\n\nThis error occurs when npm cannot write to package.json."),
    ("npm-config-location", "npm config location error",
     "Fix npm 'config location' error. Resolve issues when determining the location of npm configurations.",
     "npm ERR! config: config file not found\n\nThis error occurs when the specified config file does not exist."),
    ("npm-root", "npm root error",
     "Fix npm 'root' error. Resolve issues with npm's output of the node_modules directory path.",
     "npm root -g\n\nThis shows the global node_modules path. Errors occur when the directory does not exist."),
    ("npm-bin", "npm bin error",
     "Fix npm 'bin' error. Resolve issues with npm's output of the binaries directory path.",
     "npm bin -g\n\nThis shows the global binaries path. Errors occur when the path is not writable."),
    ("npm-prefix", "npm prefix error",
     "Fix npm 'prefix' error. Resolve issues with npm's output of the current prefix path.",
     "npm prefix -g\n\nThis shows the global prefix path. Errors may occur if the prefix is not properly configured."),
    ("npm-logout", "npm logout error",
     "Fix npm 'logout' error. Resolve failures when logging out of npm registry.",
     "npm ERR! Not logged in\n\nThis error occurs when you are not currently logged in."),
    ("npm-whoami", "npm whoami error",
     "Fix npm 'whoami' error. Resolve failures when checking the current npm user.",
     "npm ERR! Not logged in\n\nThis error occurs when you are not logged in to the npm registry."),
    ("npm-edit", "npm edit error",
     "Fix npm 'edit' error. Resolve failures when editing installed packages.",
     "npm ERR! package not installed: <package>\n\nThis error occurs when the specified package is not installed in the current directory."),
    ("npm-help-search", "npm help-search error",
     "Fix npm 'help-search' error. Resolve failures when searching npm documentation.",
     "npm ERR! No results for <term>\n\nThis error occurs when the help search term does not match any documentation."),
    ("npm-install-overwrite", "npm install overwrite bin error",
     "Fix npm 'install overwrite' error. Resolve conflicts when package binaries overwrite existing files.",
     "npm ERR! EEXIST: file already exists\n\nThis error occurs when a package binary conflicts with an existing binary."),
    ("npm-version-git", "npm version git error",
     "Fix npm 'version git' error. Resolve failures when npm version creates a git tag.",
     "npm ERR! Git: not a git repository\n\nThis error occurs when there is no git repository to tag."),
]

def make_npm_page(slug, title, desc, body):
    lines = [
        '---',
        f'title: "[Solution] {title}"',
        f'description: "{desc}"',
        'tools: ["npm"]',
        'error-types: ["tool-error"]',
        'severities: ["error"]',
        'weight: 5',
        '---',
        '',
        f'# {title}',
        '',
        body,
        '',
        '## How to Fix',
        '',
        '### Check npm Version',
        '',
        '```bash',
        'npm --version',
        'node --version',
        '```',
        '',
        '### Clear npm Cache',
        '',
        '```bash',
        'npm cache clean --force',
        '```',
        '',
        '### Check Registry Status',
        '',
        '```bash',
        'npm ping',
        'npm config get registry',
        '```',
        '',
        '### Verify Permissions',
        '',
        '```bash',
        'ls -la $(npm root -g)',
        'whoami',
        '```',
        '',
        '## Related Errors',
        '',
        '- [Module Not Found]({{< relref "/tools/npm/module-not-found" >}}) — missing module',
        '- [ERESOLVE]({{< relref "/tools/npm/peer-deps" >}}) — dependency conflict',
        '',
    ]
    return '\n'.join(lines)

count = 0
for slug, title, desc, body in PAGES_DATA:
    if slug in EXISTING:
        print(f"SKIP (exists): {slug}")
        continue
    content = make_npm_page(slug, title, desc, body)
    path = f"/home/admin1/projects/ErrorCode.excellentwiki.com/content/tools/npm/{slug}.md"
    with open(path, 'w') as f:
        f.write(content)
    count += 1
    print(f"CREATED: {slug}")

print(f"\nTotal created: {count}")
print(f"Total skipped (existing): {len(PAGES_DATA) - count}")
