#!/usr/bin/env python3
"""Generate CouchDB error pages to reach 100+ total."""
import os

BASE = '/home/admin1/projects/ErrorCode.excellentwiki.com/content/tools/couchdb'
EXISTING = {f.replace('.md', '') for f in os.listdir(BASE) if f.endswith('.md')}

def make_page(slug, title, desc, body):
    return f'''---
title: "[Solution] {title}"
description: "{desc}"
tools: ["couchdb"]
error-types: ["tool-error"]
severities: ["error"]
---

{body}
'''

PAGES = [
    ("couchdb-replication-conflict-error", "CouchDB Replication Conflict Error", "How to fix CouchDB replication conflicts", "## Common Causes\n\n- Concurrent writes to same document\n- Replication filter mismatch\n- Document revision mismatch\n\n## How to Fix\n\n```bash\ncurl -s http://localhost:5984/mydb/_conflicts?revs=true | jq .\n```\n\n## Examples\n\n```bash\ncurl -s http://localhost:5984/mydb/_conflicts?revs=true | jq '.rows[] | {_id: ._id}'\n```"),
    ("couchdb-bulk-ops-error", "CouchDB Bulk Operations Error", "How to fix CouchDB bulk insert and update errors", "## Common Causes\n\n- Bulk payload too large\n- Document conflict in batch\n- Missing _rev in update\n\n## How to Fix\n\n```bash\ncurl -X POST http://localhost:5984/mydb/_bulk_docs -H 'Content-Type: application/json' -d '{\"docs\":[{\"_id\":\"doc1\",\"value\":1}]}'\n```\n\n## Examples\n\n```bash\ncurl -X POST http://localhost:5984/mydb/_bulk_docs -H 'Content-Type: application/json' -d '{\"docs\":[]}'\n```"),
    ("couchdb-view-compaction-error", "CouchDB View Compaction Error", "How to fix CouchDB view compaction errors", "## Common Causes\n\n- View compaction taking too long\n- View index corrupted\n- Disk space insufficient\n\n## How to Fix\n\n```bash\ncurl -X POST http://localhost:5984/mydb/_compact\n```\n\n## Examples\n\n```bash\ncurl -s http://localhost:5984/mydb/_info | jq '.view_index'\n```"),
    ("couchdb-compaction-daemon-error", "CouchDB Compaction Daemon Error", "How to fix CouchDB automatic compaction errors", "## Common Causes\n\n- Compaction daemon not running\n- Compaction threshold not met\n- Compaction failing due to disk space\n\n## How to Fix\n\n```ini\n[compaction]\ndaemon = true\ninterval = 600\n```\n\n## Examples\n\n```bash\ncurl -s http://localhost:5984/mydb/_info | jq '.db_size'\n```"),
    ("couchdb-document-update-conflict", "CouchDB Document Update Conflict", "How to fix CouchDB document update conflicts", "## Common Causes\n\n- Stale revision used\n- Concurrent update to same document\n- Missing _rev field\n\n## How to Fix\n\n```bash\ncurl -s http://localhost:5984/mydb/doc1 | jq '._rev'\n```\n\n## Examples\n\n```bash\ncurl -s http://localhost:5984/mydb/doc1 | jq '._rev'\n```"),
    ("couchdb-disk-full-error", "CouchDB Disk Full Error", "How to fix CouchDB disk space errors", "## Common Causes\n\n- Database partition full\n- Compaction not freeing space\n- View index consuming disk\n\n## How to Fix\n\n```bash\ndu -sh /var/lib/couchdb/*.couch\n```\n\n## Examples\n\n```bash\ncurl -s http://localhost:5984/mydb/_info | jq '.db_size'\n```"),
    ("couchdb-index-error", "CouchDB Mango Index Error", "How to fix CouchDB Mango index errors", "## Common Causes\n\n- Index not created for query field\n- Index creation failed\n- Index out of sync\n\n## How to Fix\n\n```bash\ncurl -X POST http://localhost:5984/mydb/_index -H 'Content-Type: application/json' -d '{\"index\":{\"fields\":[\"name\"]},\"type\":\"json\",\"name\":\"name-index\"}'\n```\n\n## Examples\n\n```bash\ncurl -s http://localhost:5984/mydb/_index | jq '.total_rows'\n```"),
    ("couchdb-find-error", "CouchDB Find Query Error", "How to fix CouchDB Mango find query errors", "## Common Causes\n\n- Mango selector syntax wrong\n- Missing index for query\n- Query returning too many results\n\n## How to Fix\n\n```bash\ncurl -X POST http://localhost:5984/mydb/_find -H 'Content-Type: application/json' -d '{\"selector\":{\"name\":\"Alice\"}}'\n```\n\n## Examples\n\n```bash\ncurl -X POST http://localhost:5984/mydb/_find -H 'Content-Type: application/json' -d '{\"selector\":{}}'\n```"),
    ("couchdb-changes-error", "CouchDB Changes Feed Error", "How to fix CouchDB changes feed errors", "## Common Causes\n\n- Changes feed timeout\n- Filter function error\n- Long polling not working\n\n## How to Fix\n\n```bash\ncurl -s http://localhost:5984/mydb/_changes?include_docs=true\n```\n\n## Examples\n\n```bash\ncurl -s http://localhost:5984/mydb/_changes?since=0&limit=10\n```"),
    ("couchdb-security-error", "CouchDB Security Error", "How to fix CouchDB security and authentication errors", "## Common Causes\n\n- Admin party mode disabled\n- Wrong credentials\n- Security doc not set\n\n## How to Fix\n\n```bash\ncurl -X PUT http://localhost:5984/_users/org.couchdb.user:admin -H 'Content-Type: application/json' -d '{\"name\":\"admin\",\"password\":\"password\",\"roles\":[],\"type\":\"user\"}'\n```\n\n## Examples\n\n```bash\ncurl -s http://localhost:5984/_users/org.couchdb.user:admin | jq '.name'\n```"),
    ("couchdb-cors-error", "CouchDB CORS Error", "How to fix CouchDB CORS errors", "## Common Causes\n\n- CORS not enabled\n- Origin not whitelisted\n- Credentials not allowed\n\n## How to Fix\n\n```ini\n[httpd]\nenable_cors = true\n\n[cors]\norigins = *\ncredentials = true\n```\n\n## Examples\n\n```bash\ncurl -I -H 'Origin: http://localhost:3000' http://localhost:5984/\n```"),
    ("couchdb-shard-error", "CouchDB Shard Error", "How to fix CouchDB cluster shard errors", "## Common Causes\n\n- Shard not accessible\n- Shard not in correct node\n- Shard rebalance failed\n\n## How to Fix\n\n```bash\ncurl -s http://localhost:5984/mydb | jq '.shard_count'\n```\n\n## Examples\n\n```bash\ncurl -s http://localhost:5984/_membership | jq '.all_nodes'\n```"),
    ("couchdb-node-error", "CouchDB Cluster Node Error", "How to fix CouchDB cluster node errors", "## Common Causes\n\n- Node not joining cluster\n- Node out of sync\n- Cluster membership error\n\n## How to Fix\n\n```bash\ncurl -s http://localhost:5984/_membership | jq '.'\n```\n\n## Examples\n\n```bash\ncurl -s http://localhost:5984/_nodes | jq '.rows[].id'\n```"),
    ("couchdb-cluster-error", "CouchDB Cluster Configuration Error", "How to fix CouchDB cluster setup errors", "## Common Causes\n\n- Cluster not initialized\n- n (replicas) wrong\n- q (shards) mismatch\n\n## How to Fix\n\n```bash\ncurl -s http://localhost:5984/_cluster_setup | jq '.state'\n```\n\n## Examples\n\n```bash\ncurl -s http://localhost:5984/_membership | jq '.all_nodes'\n```"),
    ("couchdb-ssl-error", "CouchDB SSL/TLS Error", "How to fix CouchDB SSL errors", "## Common Causes\n\n- SSL certificate not configured\n- Certificate expired\n- Client not trusting server cert\n\n## How to Fix\n\n```ini\n[ssl]\ncert = /path/to/cert.pem\nkey = /path/to/key.pem\n```\n\n## Examples\n\n```bash\nopenssl s_client -connect localhost:6984\n```"),
    ("couchdb-http-error", "CouchDB HTTP Error", "How to fix CouchDB HTTP API errors", "## Common Causes\n\n- Wrong HTTP method\n- Endpoint URL wrong\n- Content-Type header missing\n\n## How to Fix\n\n```bash\ncurl -s http://localhost:5984/ | jq .\n```\n\n## Examples\n\n```bash\ncurl -s http://localhost:5984/_up\n```"),
    ("couchdb-design-doc-error", "CouchDB Design Document Error", "How to fix CouchDB design document errors", "## Common Causes\n\n- View function syntax error\n- Design doc conflicts\n- Map function error\n\n## How to Fix\n\n```bash\ncurl -X PUT http://localhost:5984/mydb/_design/myview -H 'Content-Type: application/json' -d '{\"views\":{\"all\":{\"map\":\"function(doc){emit(doc._id,doc)}\"}}}'\n```\n\n## Examples\n\n```bash\ncurl -s http://localhost:5984/mydb/_design/myview/_view/all\n```"),
    ("couchdb-view-error", "CouchDB View Error", "How to fix CouchDB view errors", "## Common Causes\n\n- View not defined\n- Map function throwing error\n- View index building slowly\n\n## How to Fix\n\n```bash\ncurl -s http://localhost:5984/mydb/_design/myview/_view/all | jq '.total_rows'\n```\n\n## Examples\n\n```bash\ncurl -s http://localhost:5984/mydb/_design/myview/_view/all?include_docs=true\n```"),
    ("couchdb-list-error", "CouchDB List Function Error", "How to fix CouchDB list function errors", "## Common Causes\n\n- List function not found\n- List function syntax error\n- View referenced by list not found\n\n## How to Fix\n\n```bash\ncurl -s http://localhost:5984/mydb/_design/mylist/_list/mylist/myview\n```\n\n## Examples\n\n```bash\ncurl -s http://localhost:5984/mydb/_design/mylist/_list/mylist/myview?key=\"doc1\"\n```"),
    ("couchdb-show-error", "CouchDB Show Function Error", "How to fix CouchDB show function errors", "## Common Causes\n\n- Show function not defined\n- Document not found\n- Show function syntax error\n\n## How to Fix\n\n```bash\ncurl -s http://localhost:5984/mydb/_design/myshow/_show/myshow/doc1\n```\n\n## Examples\n\n```bash\ncurl -s http://localhost:5984/mydb/_design/myshow/_show/myshow/doc1\n```"),
    ("couchdb-update-handler-error", "CouchDB Update Handler Error", "How to fix CouchDB update handler errors", "## Common Causes\n\n- Update handler not found\n- Handler syntax error\n- Database not found\n\n## How to Fix\n\n```bash\ncurl -X PUT http://localhost:5984/mydb/_design/myupdate/_update/myupdate/doc1\n```\n\n## Examples\n\n```bash\ncurl -X PUT http://localhost:5984/mydb/_design/myupdate/_update/myupdate/newdoc\n```"),
    ("couchdb-attachment-error", "CouchDB Attachment Error", "How to fix CouchDB attachment errors", "## Common Causes\n\n- Attachment too large\n- Content-Type not set\n- Revision conflict on attachment\n\n## How to Fix\n\n```bash\ncurl -X PUT http://localhost:5984/mydb/doc1/attachment.bin -H 'Content-Type: application/octet-stream' -d @file.bin\n```\n\n## Examples\n\n```bash\ncurl -s http://localhost:5984/mydb/doc1/attachment.bin -o attachment.bin\n```"),
    ("couchdb-json-error", "CouchDB JSON Error", "How to fix CouchDB JSON parsing errors", "## Common Causes\n\n- Document not valid JSON\n- Request body not valid JSON\n- Response not valid JSON\n\n## How to Fix\n\n```bash\necho '{\"key\": \"value\"}' | python3 -m json.tool\n```\n\n## Examples\n\n```bash\ncurl -s http://localhost:5984/mydb/doc1 | python3 -m json.tool\n```"),
    ("couchdb-filter-error", "CouchDB Replication Filter Error", "How to fix CouchDB replication filter errors", "## Common Causes\n\n- Filter function not defined\n- Filter function syntax error\n- Filter function throwing error\n\n## How to Fix\n\n```bash\ncurl -X POST http://localhost:5984/_replicate -H 'Content-Type: application/json' -d '{\"source\":\"mydb\",\"target\":\"mydb-replica\",\"filter\":\"myfilter/myfilter\"}'\n```\n\n## Examples\n\n```bash\ncurl -s http://localhost:5984/mydb/_design/myfilter/_filter/myfilter\n```"),
    ("couchdb-stale-error", "CouchDB Stale View Error", "How to fix CouchDB stale view and index errors", "## Common Causes\n\n- View index not updated\n- stale=ok not used when needed\n- View compaction causing delay\n\n## How to Fix\n\n```bash\ncurl -s http://localhost:5984/mydb/_design/myview/_view/all?stale=ok\n```\n\n## Examples\n\n```bash\ncurl -s http://localhost:5984/mydb/_design/myview/_view/all?stale=update_after\n```"),
    ("couchdb-mango-error", "CouchDB Mango Query Error", "How to fix CouchDB Mango query errors", "## Common Causes\n\n- Mango selector syntax wrong\n- Missing index for query\n- Sort field not indexed\n\n## How to Fix\n\n```bash\ncurl -X POST http://localhost:5984/mydb/_find -H 'Content-Type: application/json' -d '{\"selector\":{\"age\":{\"$gt\":25}},\"sort\":[{\"age\":\"asc\"}]}'\n```\n\n## Examples\n\n```bash\ncurl -X POST http://localhost:5984/mydb/_find -H 'Content-Type: application/json' -d '{\"selector\":{\"name\":{\"$regex\":\"^A\"}}}'\n```"),
    ("couchdb-replication-error", "CouchDB Replication Error", "How to fix CouchDB replication errors", "## Common Causes\n\n- Source or target unreachable\n- Authentication failed\n- Continuous replication stopped\n\n## How to Fix\n\n```bash\ncurl -X POST http://localhost:5984/_replicate -H 'Content-Type: application/json' -d '{\"source\":\"mydb\",\"target\":\"mydb-replica\"}'\n```\n\n## Examples\n\n```bash\ncurl -s http://localhost:5984/_active_tasks | jq '.[] | select(.type == \"replication\")'\n```"),
    ("couchdb-upgrade-error", "CouchDB Upgrade Error", "How to fix CouchDB version upgrade errors", "## Common Causes\n\n- Database format incompatible\n- Config file format changed\n- Plugin not compatible\n\n## How to Fix\n\n```bash\ncurl -s http://localhost:5984/ | jq .\n```\n\n## Examples\n\n```bash\ncurl -s http://localhost:5984/_up\n```"),
    ("couchdb-restart-error", "CouchDB Restart Error", "How to fix CouchDB restart and recovery errors", "## Common Causes\n\n- CouchDB service not starting\n- Config file parse error\n- Port already in use\n\n## How to Fix\n\n```bash\nsudo systemctl restart couchdb\n```\n\n## Examples\n\n```bash\nsudo journalctl -u couchdb --since '5 minutes ago'\n```"),
    ("couchdb-conflict-resolution-error", "CouchDB Conflict Resolution Error", "How to fix CouchDB conflict resolution errors", "## Common Causes\n\n- Multiple conflicting revisions\n- Auto-merge not working\n- Conflict not resolved after update\n\n## How to Fix\n\n```bash\ncurl -s http://localhost:5984/mydb/doc1?conflicts=true | jq '.[\"_conflicts\"]'\n```\n\n## Examples\n\n```bash\ncurl -s http://localhost:5984/mydb/doc1?conflicts=true | jq '.'\n```"),
    ("couchdb-attachment-upload-error", "CouchDB Attachment Upload Error", "How to fix CouchDB attachment upload errors", "## Common Causes\n- Attachment data corrupted\n- Content-Length header missing\n- Revision conflict on upload\n\n## How to Fix\n\n```bash\ncurl -X PUT http://localhost:5984/mydb/doc1/file.txt?rev=1-abc -H 'Content-Type: text/plain' -d 'Hello World'\n```\n\n## Examples\n\n```bash\ncurl -s http://localhost:5984/mydb/doc1 | jq '._attachments'\n```"),
    ("couchdb-attachment-download-error", "CouchDB Attachment Download Error", "How to fix CouchDB attachment download errors", "## Common Causes\n- Attachment not found\n- Revision mismatch\n- Content-Encoding issue\n\n## How to Fix\n\n```bash\ncurl -s http://localhost:5984/mydb/doc1/file.txt -o file.txt\n```\n\n## Examples\n\n```bash\ncurl -s http://localhost:5984/mydb/doc1/file.txt | head -5\n```"),
    ("couchdb-attachment-delete-error", "CouchDB Attachment Delete Error", "How to fix CouchDB attachment deletion errors", "## Common Causes\n- Revision not specified\n- Attachment not found\n- Conflict on delete\n\n## How to Fix\n\n```bash\ncurl -X DELETE http://localhost:5984/mydb/doc1/file.txt?rev=2-abc\n```\n\n## Examples\n\n```bash\ncurl -s http://localhost:5984/mydb/doc1 | jq '._attachments'\n```"),
    ("couchdb-attachment-revisions-error", "CouchDB Attachment Revision Error", "How to fix CouchDB attachment revision errors", "## Common Causes\n- Wrong revision used\n- Revision not incremented\n- Old revision referenced\n\n## How to Fix\n\n```bash\ncurl -s http://localhost:5984/mydb/doc1 | jq '._rev'\n```\n\n## Examples\n\n```bash\ncurl -s http://localhost:5984/mydb/doc1 | jq '.[\"_rev\"]'\n```"),
    ("couchdb-attachment-content-type-error", "CouchDB Attachment Content-Type Error", "How to fix CouchDB attachment content type errors", "## Common Causes\n- Content-Type not set\n- Wrong Content-Type for file\n- Browser not rendering file\n\n## How to Fix\n\n```bash\ncurl -X PUT http://localhost:5984/mydb/doc1/image.png -H 'Content-Type: image/png' -d @image.png\n```\n\n## Examples\n\n```bash\ncurl -s http://localhost:5984/mydb/doc1 | jq '._attachments | to_entries[] | {name: .key, content_type: .value.content_type}'\n```"),
    ("couchdb-attachment-range-error", "CouchDB Attachment Range Request Error", "How to fix CouchDB attachment range request errors", "## Common Causes\n- Range header not supported\n- Partial content not returned\n- Range boundary wrong\n\n## How to Fix\n\n```bash\ncurl -s -H 'Range: bytes=0-100' http://localhost:5984/mydb/doc1/file.txt\n```\n\n## Examples\n\n```bash\ncurl -s -I -H 'Range: bytes=0-100' http://localhost:5984/mydb/doc1/file.txt | grep -i content-range\n```"),
    ("couchdb-attachment-gzip-error", "CouchDB Attachment GZip Error", "How to fix CouchDB attachment compression errors", "## Common Causes\n- GZip encoding not accepted\n- Compressed attachment corrupted\n- Decompression failing\n\n## How to Fix\n\n```bash\ncurl -s -H 'Accept-Encoding: gzip' http://localhost:5984/mydb/doc1/file.txt -o file.gz\n```\n\n## Examples\n\n```bash\ngunzip file.gz\n```"),
    ("couchdb-attachment-max-size-error", "CouchDB Attachment Max Size Error", "How to fix CouchDB attachment size limit errors", "## Common Causes\n- Attachment exceeds max_document_size\n- Attachment too large for HTTP body\n- Disk space insufficient\n\n## How to Fix\n\n```ini\n[max_document_size]\nmax_document_size = 50000000\n```\n\n## Examples\n\n```bash\ncurl -s http://localhost:5984/ | jq '.couchdb'\n```"),
    ("couchdb-attachment-md5-error", "CouchDB Attachment MD5 Error", "How to fix CouchDB attachment MD5 checksum errors", "## Common Causes\n- MD5 mismatch during upload\n- Corrupted attachment data\n- Encoding issue\n\n## How to Fix\n\n```bash\ncurl -s http://localhost:5984/mydb/doc1/file.txt | md5sum\n```\n\n## Examples\n\n```bash\ncurl -s -I http://localhost:5984/mydb/doc1/file.txt | grep -i etag\n```"),
    ("couchdb-attachment-rename-error", "CouchDB Attachment Rename Error", "How to fix CouchDB attachment rename errors", "## Common Causes\n- Cannot rename attachment directly\n- Must re-upload with new name\n- Old attachment not deleted\n\n## How to Fix\n\n```bash\ncurl -X PUT http://localhost:5984/mydb/doc1/newname.txt?rev=2-abc -H 'Content-Type: text/plain' -d 'content'\ncurl -X DELETE http://localhost:5984/mydb/doc1/oldname.txt?rev=3-def\n```\n\n## Examples\n\n```bash\ncurl -s http://localhost:5984/mydb/doc1 | jq '._attachments | keys'\n```"),
    ("couchdb-attachment-move-error", "CouchDB Attachment Move Error", "How to fix CouchDB attachment move errors", "## Common Causes\n- Cannot move attachment between documents\n- Must copy and delete\n- Revision conflict during move\n\n## How to Fix\n\n```bash\ncurl -s http://localhost:5984/mydb/doc1/file.txt -o temp.txt\ncurl -X PUT http://localhost:5984/mydb/doc2/file.txt -H 'Content-Type: text/plain' -d @temp.txt\ncurl -X DELETE http://localhost:5984/mydb/doc1/file.txt?rev=2-abc\n```\n\n## Examples\n\n```bash\ncurl -s http://localhost:5984/mydb/doc2 | jq '._attachments'\n```"),
    ("couchdb-attachment-list-error", "CouchDB Attachment List Error", "How to fix CouchDB attachment list errors", "## Common Causes\n- No attachments on document\n- Attachments not returned in listing\n- Query parameter wrong\n\n## How to Fix\n\n```bash\ncurl -s http://localhost:5984/mydb/doc1 | jq '._attachments | keys'\n```\n\n## Examples\n\n```bash\ncurl -s 'http://localhost:5984/mydb/_all_docs?include_docs=true&attachments=true' | jq '.rows[] | ._attachments'\n```"),
    ("couchdb-attachment-stream-error", "CouchDB Attachment Streaming Error", "How to fix CouchDB attachment streaming errors", "## Common Causes\n- Stream interrupted\n- Connection reset\n- Timeout on large attachment\n\n## How to Fix\n\n```bash\ncurl -s --max-time 300 http://localhost:5984/mydb/doc1/largefile.bin -o largefile.bin\n```\n\n## Examples\n\n```bash\ncurl -s -o /dev/null -w '%{size_download} %{time_total}' http://localhost:5984/mydb/doc1/largefile.bin\n```"),
    ("couchdb-attachment-batch-error", "CouchDB Attachment Batch Upload Error", "How to fix CouchDB attachment batch upload errors", "## Common Causes\n- Multiple attachments failing\n- Partial upload success\n- Timeout on batch\n\n## How to Fix\n\n```bash\nfor f in file1.txt file2.txt file3.txt; do\ncurl -X PUT \"http://localhost:5984/mydb/doc1/$f\" -H 'Content-Type: text/plain' -d @$f\ndone\n```\n\n## Examples\n\n```bash\ncurl -s http://localhost:5984/mydb/doc1 | jq '._attachments | keys'\n```"),
    ("couchdb-attachment-meta-error", "CouchDB Attachment Metadata Error", "How to fix CouchDB attachment metadata errors", "## Common Causes\n- Metadata fields missing\n- Wrong metadata format\n- Metadata not preserved\n\n## How to Fix\n\n```bash\ncurl -s http://localhost:5984/mydb/doc1 | jq '._attachments | to_entries[] | {name: .key, length: .value.length, digest: .value.digest}'\n```\n\n## Examples\n\n```bash\ncurl -s http://localhost:5984/mydb/doc1 | jq '._attachments'\n```"),
    ("couchdb-attachment-cache-error", "CouchDB Attachment Cache Error", "How to fix CouchDB attachment caching errors", "## Common Causes\n- Stale attachment served from cache\n- Cache not invalidated\n- ETag not set properly\n\n## How to Fix\n\n```bash\ncurl -s -I http://localhost:5984/mydb/doc1/file.txt | grep -i 'etag\\|cache-control'\n```\n\n## Examples\n\n```bash\ncurl -s -H 'If-None-Match: \"abc\"' -o /dev/null -w '%{http_code}' http://localhost:5984/mydb/doc1/file.txt\n```"),
    ("couchdb-attachment-cors-error", "CouchDB Attachment CORS Error", "How to fix CouchDB attachment CORS errors", "## Common Causes\n- CORS headers missing for attachments\n- Preflight request failing\n- Origin not whitelisted\n\n## How to Fix\n\n```ini\n[cors]\norigins = http://localhost:3000\nheaders = accept, authorization, content-type, origin\nmethods = GET, PUT, POST, DELETE, HEAD\ncredentials = true\n```\n\n## Examples\n\n```bash\ncurl -I -H 'Origin: http://localhost:3000' http://localhost:5984/mydb/doc1/file.txt\n```"),
    ("couchdb-attachment-redirect-error", "CouchDB Attachment Redirect Error", "How to fix CouchDB attachment redirect errors", "## Common Causes\n- Attachment URL redirects\n- Redirect loop detected\n- Redirect not followed\n\n## How to Fix\n\n```bash\ncurl -L -s http://localhost:5984/mydb/doc1/file.txt -o file.txt\n```\n\n## Examples\n\n```bash\ncurl -v http://localhost:5984/mydb/doc1/file.txt 2>&1 | grep -i location\n```"),
    ("couchdb-attachment-snapshot-error", "CouchDB Attachment Snapshot Error", "How to fix CouchDB attachment snapshot errors", "## Common Causes\n- Attachment not in snapshot\n- Snapshot not including attachments\n- Snapshot query wrong\n\n## How to Fix\n\n```bash\ncurl -s 'http://localhost:5984/mydb/_changes?include_docs=true&attachments=true' | jq '.rows[] | ._attachments'\n```\n\n## Examples\n\n```bash\ncurl -s 'http://localhost:5984/mydb/_all_docs?include_docs=true&attachments=true' | jq '.rows[] | {id: .id, attachments: (._attachments | keys)}'\n```"),
    ("couchdb-attachment-compact-error", "CouchDB Attachment Compaction Error", "How to fix CouchDB attachment compaction errors", "## Common Causes\n- Compaction not reclaiming attachment space\n- Attachment revisions not cleaned\n- Compaction timeout\n\n## How to Fix\n\n```bash\ncurl -X POST http://localhost:5984/mydb/_compact\n```\n\n## Examples\n\n```bash\ncurl -s http://localhost:5984/mydb/_info | jq '.sizes'\n```"),
    ("couchdb-attachment-sync-error", "CouchDB Attachment Sync Error", "How to fix CouchDB attachment replication sync errors", "## Common Causes\n- Attachment not synced during replication\n- Sync conflict on attachment\n- Attachment size mismatch\n\n## How to Fix\n\n```bash\ncurl -X POST http://localhost:5984/_replicate -H 'Content-Type: application/json' -d '{\"source\":\"mydb\",\"target\":\"mydb-replica\",\"create_target\":true}'\n```\n\n## Examples\n\n```bash\ncurl -s http://localhost:5984/_active_tasks | jq '.[] | select(.type == \"replication\")'\n```"),
    ("couchdb-attachment-proxy-error", "CouchDB Attachment Proxy Error", "How to fix CouchDB attachment proxy errors", "## Common Causes\n- Proxy not forwarding attachment\n- Proxy buffer overflow\n- Proxy timeout on large attachment\n\n## How to Fix\n\n```bash\ncurl -s --max-time 60 http://proxy-host:5984/mydb/doc1/file.txt -o file.txt\n```\n\n## Examples\n\n```bash\ncurl -v --max-time 60 http://proxy-host:5984/mydb/doc1/file.txt 2>&1 | head -20\n```"),
    ("couchdb-attachment-ratelimit-error", "CouchDB Attachment Rate Limit Error", "How to fix CouchDB attachment rate limit errors", "## Common Causes\n- Too many attachment requests\n- Rate limit exceeded\n- Concurrent upload limit\n\n## How to Fix\n\n```bash\ncurl -s --retry 3 --retry-delay 5 http://localhost:5984/mydb/doc1/file.txt\n```\n\n## Examples\n\n```bash\ncurl -s -o /dev/null -w '%{http_code}' http://localhost:5984/mydb/doc1/file.txt\n```"),
    ("couchdb-attachment-auth-error", "CouchDB Attachment Auth Error", "How to fix CouchDB attachment authentication errors", "## Common Causes\n- Attachment requires auth\n- Wrong credentials\n- Session expired\n\n## How to Fix\n\n```bash\ncurl -s -u admin:password http://localhost:5984/mydb/doc1/file.txt\n```\n\n## Examples\n\n```bash\ncurl -s -b cookies.txt http://localhost:5984/mydb/doc1/file.txt -o file.txt\n```"),
    ("couchdb-attachment-permission-error", "CouchDB Attachment Permission Error", "How to fix CouchDB attachment permission errors", "## Common Causes\n- User lacks write permission\n- Database security blocks attachment\n- Role not authorized\n\n## How to Fix\n\n```bash\ncurl -s http://localhost:5984/mydb/_security | jq '.'\n```\n\n## Examples\n\n```bash\ncurl -X PUT http://localhost:5984/mydb/_security -H 'Content-Type: application/json' -d '{\"admins\":{\"names\":[\"admin\"],\"roles\":[]},\"members\":{\"names\":[],\"roles\":[\"user\"]}}'\n```"),
    ("couchdb-attachment-quota-error", "CouchDB Attachment Quota Error", "How to fix CouchDB attachment quota and limit errors", "## Common Causes\n- Database quota exceeded\n- Attachment count limit\n- Total attachment size limit\n\n## How to Fix\n\n```ini\n[replicator]\ndb_quota = 0\n```\n\n## Examples\n\n```bash\ncurl -s http://localhost:5984/mydb/_info | jq '.sizes'\n```"),
    ("couchdb-attachment-retry-error", "CouchDB Attachment Retry Error", "How to fix CouchDB attachment retry errors", "## Common Causes\n- Upload retry failing\n- Network interruption\n- Timeout on retry\n\n## How to Fix\n\n```bash\ncurl -s --retry 5 --retry-delay 3 http://localhost:5984/mydb/doc1/file.txt\n```\n\n## Examples\n\n```bash\ncurl -v --retry 3 http://localhost:5984/mydb/doc1/file.txt 2>&1 | grep -i retry\n```"),
    ("couchdb-attachment-vendor-error", "CouchDB Attachment Vendor Error", "How to fix CouchDB attachment vendor-specific errors", "## Common Causes\n- CouchDB version vendor extension\n- Vendor-specific header not recognized\n- Feature not supported in version\n\n## How to Fix\n\n```bash\ncurl -s http://localhost:5984/ | jq '.version'\n```\n\n## Examples\n\n```bash\ncurl -s http://localhost:5984/_up | jq '.'\n```"),
]

count = 0
for slug, title, desc, body in PAGES:
    if slug in EXISTING:
        continue
    path = os.path.join(BASE, f'{slug}.md')
    with open(path, 'w') as f:
        f.write(make_page(slug, title, desc, body))
    count += 1

print(f'Generated {count} new CouchDB pages (total: {len(EXISTING) + count})')
