#!/usr/bin/env python3
"""Generate new PostgreSQL error pages"""
import os

EXISTING = {f.replace('.md', '') for f in os.listdir('/home/admin1/projects/ErrorCode.excellentwiki.com/content/tools/postgresql/') if f.endswith('.md')}

PAGES_DATA = [
    ("pg-cant-connect", "PostgreSQL Can't connect to server",
     "Fix PostgreSQL 'Can't connect to server' error. Resolve connection failures when the PostgreSQL server is unreachable.",
     "psql: error: connection to server at 'host' (IP), port 5432 failed: Connection refused\n\nThis error occurs when the PostgreSQL client cannot connect to the server. The server may not be running or a firewall may be blocking connections."),
    ("pg-ident-failed", "PostgreSQL Ident authentication failed",
     "Fix PostgreSQL 'ident authentication failed' error. Resolve authentication failures with ident/auth methods.",
     "FATAL: ident authentication failed for user 'user'\n\nThis error occurs when PostgreSQL uses ident authentication and the operating system user does not match the database user."),
    ("pg-password-auth-failed", "PostgreSQL Password authentication failed",
     "Fix PostgreSQL 'password authentication failed' error. Resolve login failures due to incorrect passwords.",
     "FATAL: password authentication failed for user 'user'\n\nThis error occurs when the password provided for the PostgreSQL user is incorrect."),
    ("pg-peer-auth-failed", "PostgreSQL Peer authentication failed",
     "Fix PostgreSQL 'peer authentication failed' error. Resolve local connection authentication issues.",
     "FATAL: Peer authentication failed for user 'user'\n\nThis error occurs when the operating system user does not match the PostgreSQL user for local connections."),
    ("pg-ssl-required", "PostgreSQL SSL required error",
     "Fix PostgreSQL 'SSL required' error. Resolve connection failures when SSL is required but not provided.",
     "FATAL: no pg_hba.conf entry for host, SSL required\n\nThis error occurs when the server requires SSL connections but the client is not using SSL."),
    ("pg-no-pg-hba-entry", "PostgreSQL no pg_hba.conf entry",
     "Fix PostgreSQL 'no pg_hba.conf entry' error. Resolve host-based authentication configuration issues.",
     "FATAL: no pg_hba.conf entry for host, database, user\n\nThis error occurs when there is no matching rule in pg_hba.conf for the connection."),
    ("pg-database-already-exists", "PostgreSQL Database already exists",
     "Fix PostgreSQL 'database already exists' error. Resolve database creation failures.",
     "ERROR: database '<name>' already exists\n\nThis error occurs when you try to create a database that already exists."),
    ("pg-cant-drop-database", "PostgreSQL Can't drop database",
     "Fix PostgreSQL 'can't drop database' error. Resolve database deletion failures.",
     "ERROR: database '<name>' does not exist\n\nThis error occurs when you try to drop a database that does not exist."),
    ("pg-database-not-empty", "PostgreSQL Database not empty error",
     "Fix PostgreSQL 'database not empty' error. Resolve database drop failures when the database is in use.",
     "ERROR: cannot drop the currently open database\n\nThis error occurs when you try to drop a database that you are currently connected to."),
    ("pg-schema-already-exists", "PostgreSQL Schema already exists",
     "Fix PostgreSQL 'schema already exists' error. Resolve schema creation failures.",
     "ERROR: schema '<name>' already exists\n\nThis error occurs when you try to create a schema that already exists."),
    ("pg-schema-not-found", "PostgreSQL Schema not found",
     "Fix PostgreSQL 'schema not found' error. Resolve schema reference failures.",
     "ERROR: schema '<name>' does not exist\n\nThis error occurs when you reference a schema that does not exist."),
    ("pg-table-already-exists", "PostgreSQL Table already exists",
     "Fix PostgreSQL 'relation already exists' error. Resolve table creation failures.",
     "ERROR: relation '<name>' already exists\n\nThis error occurs when you try to create a table that already exists."),
    ("pg-table-not-found", "PostgreSQL Table not found",
     "Fix PostgreSQL 'relation does not exist' error. Resolve table reference failures.",
     "ERROR: relation '<name>' does not exist\n\nThis error occurs when you reference a table that does not exist in the database."),
    ("pg-column-not-found", "PostgreSQL Column not found",
     "Fix PostgreSQL 'column not found' error. Resolve query failures from invalid column references.",
     "ERROR: column '<col>' does not exist\n\nThis error occurs when a column referenced in a query does not exist in the table."),
    ("pg-ambiguous-column-ref", "PostgreSQL Ambiguous column reference",
     "Fix PostgreSQL 'ambiguous column reference' error. Resolve query failures from unclear column references.",
     "ERROR: column reference '<col>' is ambiguous\n\nThis error occurs when a column name exists in multiple joined tables and is not qualified."),
    ("pg-cannot-coerce", "PostgreSQL Cannot coerce type error",
     "Fix PostgreSQL 'cannot coerce type' error. Resolve type conversion failures in queries.",
     "ERROR: cannot cast type <type1> to <type2>\n\nThis error occurs when PostgreSQL cannot convert one data type to another."),
    ("pg-numeric-precision", "PostgreSQL Numeric precision error",
     "Fix PostgreSQL 'numeric precision' error. Resolve numeric overflow or precision issues.",
     "ERROR: numeric field overflow (value exceeds the maximum precision)\n\nThis error occurs when a numeric value exceeds the defined precision."),
    ("pg-division-by-zero", "PostgreSQL Division by zero error",
     "Fix PostgreSQL 'division by zero' error. Resolve arithmetic operation failures.",
     "ERROR: division by zero\n\nThis error occurs when a mathematical expression attempts to divide by zero."),
    ("pg-integer-out-of-range", "PostgreSQL Integer out of range error",
     "Fix PostgreSQL 'integer out of range' error. Resolve integer overflow issues.",
     "ERROR: integer out of range\n\nThis error occurs when a value exceeds the range of the integer column type."),
    ("pg-value-too-long", "PostgreSQL Value too long error",
     "Fix PostgreSQL 'value too long' error. Resolve character value length issues.",
     "ERROR: value too long for type character varying(<n>)\n\nThis error occurs when a string value exceeds the column's maximum length."),
    ("pg-not-null-violation", "PostgreSQL Not null violation error",
     "Fix PostgreSQL 'not null violation' error. Resolve NOT NULL constraint violations.",
     "ERROR: null value in column '<col>' violates not-null constraint\n\nThis error occurs when you try to insert NULL into a NOT NULL column."),
    ("pg-check-violation", "PostgreSQL Check constraint violation",
     "Fix PostgreSQL 'check constraint violation' error. Resolve CHECK constraint validation failures.",
     "ERROR: new row for relation '<table>' violates check constraint '<constraint>'\n\nThis error occurs when a value violates a CHECK constraint."),
    ("pg-unique-violation", "PostgreSQL Unique constraint violation",
     "Fix PostgreSQL 'unique constraint violation' error. Resolve duplicate value issues.",
     "ERROR: duplicate key value violates unique constraint '<constraint>'\n\nThis error occurs when an INSERT or UPDATE creates a duplicate value in a unique column."),
    ("pg-foreign-key-violation", "PostgreSQL Foreign key violation error",
     "Fix PostgreSQL 'foreign key violation' error. Resolve referential integrity constraint failures.",
     "ERROR: insert or update on table '<table>' violates foreign key constraint '<fk>'\n\nThis error occurs when a foreign key value does not match a primary key in the referenced table."),
    ("pg-exclusion-violation", "PostgreSQL Exclusion constraint violation",
     "Fix PostgreSQL 'exclusion constraint violation' error. Resolve exclusion constraint failures.",
     "ERROR: conflicting key value violates exclusion constraint '<constraint>'\n\nThis error occurs when a new row conflicts with an existing row under an exclusion constraint."),
    ("pg-invalid-input-syntax", "PostgreSQL Invalid input syntax error",
     "Fix PostgreSQL 'invalid input syntax' error. Resolve type conversion failures from malformed input.",
     "ERROR: invalid input syntax for type <type>: '<value>'\n\nThis error occurs when a string cannot be parsed as the target data type."),
    ("pg-invalid-datetime-format", "PostgreSQL Invalid datetime format",
     "Fix PostgreSQL 'invalid datetime format' error. Resolve date/time parsing failures.",
     "ERROR: invalid input syntax for type timestamp: '<value>'\n\nThis error occurs when a string does not match the expected timestamp format."),
    ("pg-date-field-overflow", "PostgreSQL Date field overflow error",
     "Fix PostgreSQL 'date field overflow' error. Resolve date/time value range issues.",
     "ERROR: date/time field value out of range: '<value>'\n\nThis error occurs when a date/time value is outside the valid range."),
    ("pg-interval-field-overflow", "PostgreSQL Interval field overflow error",
     "Fix PostgreSQL 'interval field overflow' error. Resolve interval value range issues.",
     "ERROR: interval field overflow\n\nThis error occurs when an interval value exceeds the allowed range."),
    ("pg-toast-oversize", "PostgreSQL TOAST tuple overflow error",
     "Fix PostgreSQL 'TOAST tuple overflow' error. Resolve issues with large column values exceeding row limits.",
     "ERROR: row is too big: size <n>, maximum size <m>\n\nThis error occurs when a single row exceeds the maximum row size limit."),
    ("pg-too-many-columns", "PostgreSQL Too many columns error",
     "Fix PostgreSQL 'too many columns' error. Resolve table column limit issues.",
     "ERROR: tables can have at most <n> columns\n\nThis error occurs when you try to add more columns than PostgreSQL supports."),
    ("pg-too-many-indexes", "PostgreSQL Too many indexes error",
     "Fix PostgreSQL 'too many indexes' error. Resolve index limit issues on a single table.",
     "ERROR: too many indexes on table '<table>'\n\nThis error occurs when the index limit for a table is exceeded."),
    ("pg-index-does-not-exist", "PostgreSQL Index does not exist",
     "Fix PostgreSQL 'index does not exist' error. Resolve index reference failures.",
     "ERROR: index '<name>' does not exist\n\nThis error occurs when you reference an index that does not exist."),
    ("pg-index-already-exists", "PostgreSQL Index already exists",
     "Fix PostgreSQL 'index already exists' error. Resolve duplicate index creation issues.",
     "ERROR: relation '<name>' already exists\n\nThis error occurs when you try to create an index that already exists."),
    ("pg-view-not-found", "PostgreSQL View not found",
     "Fix PostgreSQL 'view does not exist' error. Resolve view reference failures.",
     "ERROR: view '<name>' does not exist\n\nThis error occurs when you reference a view that does not exist."),
    ("pg-materialized-view-error", "PostgreSQL Materialized view error",
     "Fix PostgreSQL 'materialized view' error. Resolve materialized view refresh and maintenance issues.",
     "ERROR: cannot refresh materialized view '<name>' concurrently\n\nThis error occurs when a concurrent refresh is not possible without a unique index."),
    ("pg-sequence-not-found", "PostgreSQL Sequence not found",
     "Fix PostgreSQL 'sequence does not exist' error. Resolve sequence reference failures.",
     "ERROR: sequence '<name>' does not exist\n\nThis error occurs when you reference a sequence that does not exist."),
    ("pg-function-not-found", "PostgreSQL Function does not exist",
     "Fix PostgreSQL 'function does not exist' error. Resolve function call failures.",
     "ERROR: function <name>(<args>) does not exist\n\nThis error occurs when the specified function does not exist or argument types do not match."),
    ("pg-function-ambiguous", "PostgreSQL Ambiguous function error",
     "Fix PostgreSQL 'ambiguous function' error. Resolve function overload resolution failures.",
     "ERROR: function <name>(<args>) is not unique\n\nThis error occurs when multiple functions match the call signature."),
    ("pg-procedure-not-found", "PostgreSQL Procedure not found",
     "Fix PostgreSQL 'procedure does not exist' error. Resolve stored procedure call failures.",
     "ERROR: procedure <name>(<args>) does not exist\n\nThis error occurs when you call a procedure that does not exist."),
    ("pg-trigger-not-found", "PostgreSQL Trigger not found",
     "Fix PostgreSQL 'trigger does not exist' error. Resolve trigger reference failures.",
     "ERROR: trigger '<name>' for relation '<table>' does not exist\n\nThis error occurs when you try to drop or alter a non-existent trigger."),
    ("pg-rule-not-found", "PostgreSQL Rule not found",
     "Fix PostgreSQL 'rule does not exist' error. Resolve rewrite rule reference failures.",
     "ERROR: rule '<name>' for relation '<table>' does not exist\n\nThis error occurs when you reference a non-existent rewrite rule."),
    ("pg-cast-not-found", "PostgreSQL Cast not found",
     "Fix PostgreSQL 'cast not found' error. Resolve type cast reference failures.",
     "ERROR: cannot cast type <type1> to <type2>\n\nThis error occurs when no cast exists between the specified types."),
    ("pg-domain-not-found", "PostgreSQL Domain not found",
     "Fix PostgreSQL 'domain does not exist' error. Resolve domain type reference failures.",
     "ERROR: type '<name>' does not exist\n\nThis error occurs when you reference a domain that does not exist."),
    ("pg-extension-not-found", "PostgreSQL Extension not found",
     "Fix PostgreSQL 'extension does not exist' error. Resolve extension reference failures.",
     "ERROR: extension '<name>' does not exist\n\nThis error occurs when you try to drop or alter a non-existent extension."),
    ("pg-extension-already-exists", "PostgreSQL Extension already exists",
     "Fix PostgreSQL 'extension already exists' error. Resolve duplicate extension creation issues.",
     "ERROR: extension '<name>' already exists\n\nThis error occurs when you try to create an extension that is already installed."),
    ("pg-extension-version", "PostgreSQL Extension version error",
     "Fix PostgreSQL 'extension version' error. Resolve extension update and version compatibility issues.",
     "ERROR: extension '<name>' has no update path from version <v1> to <v2>\n\nThis error occurs when no update path exists between extension versions."),
    ("pg-fdw-not-found", "PostgreSQL FDW not found error",
     "Fix PostgreSQL 'foreign data wrapper not found' error. Resolve FDW reference failures.",
     "ERROR: foreign-data wrapper '<name>' does not exist\n\nThis error occurs when you reference a non-existent foreign data wrapper."),
    ("pg-foreign-server-error", "PostgreSQL Foreign server error",
     "Fix PostgreSQL 'foreign server not found' error. Resolve foreign server reference failures.",
     "ERROR: server '<name>' does not exist\n\nThis error occurs when you reference a non-existent foreign server."),
    ("pg-user-mapping-error", "PostgreSQL User mapping error",
     "Fix PostgreSQL 'user mapping' error. Resolve foreign table user mapping issues.",
     "ERROR: user mapping for '<user>' does not exist\n\nThis error occurs when no user mapping exists for a foreign server."),
    ("pg-publication-not-found", "PostgreSQL Publication not found",
     "Fix PostgreSQL 'publication does not exist' error. Resolve logical replication publication issues.",
     "ERROR: publication '<name>' does not exist\n\nThis error occurs when you reference a non-existent publication."),
    ("pg-subscription-not-found", "PostgreSQL Subscription not found",
     "Fix PostgreSQL 'subscription does not exist' error. Resolve logical replication subscription issues.",
     "ERROR: subscription '<name>' does not exist\n\nThis error occurs when you reference a non-existent subscription."),
    ("pg-wal-level-error", "PostgreSQL WAL level error",
     "Fix PostgreSQL 'WAL level' error. Resolve replication configuration issues.",
     "ERROR: logical decoding requires wal_level >= logical\n\nThis error occurs when wal_level is insufficient for logical replication."),
    ("pg-hot-standby-error", "PostgreSQL Hot standby error",
     "Fix PostgreSQL 'hot standby' error. Resolve replication conflict issues on standby servers.",
     "ERROR: canceling statement due to conflict with recovery\n\nThis error occurs when a query on a standby conflicts with replaying WAL records."),
    ("pg-recovery-conflict", "PostgreSQL Recovery conflict error",
     "Fix PostgreSQL 'recovery conflict' error. Resolve query cancellations on standby servers.",
     "FATAL: terminating connection due to administrator command\n\nThis error can occur on standby servers when the primary triggers a conflict resolution."),
    ("pg-max-connections", "PostgreSQL Max connections error",
     "Fix PostgreSQL 'max connections' error. Resolve connection pool exhaustion issues.",
     "FATAL: sorry, too many clients already\n\nThis error occurs when all available PostgreSQL connections are in use."),
    ("pg-reserved-connections", "PostgreSQL Reserved connections error",
     "Fix PostgreSQL 'reserved connections' error. Resolve superuser connection reservation issues.",
     "FATAL: remaining connection slots are reserved for non-replication superuser connections\n\nThis error occurs when regular connections exceed the limit minus superuser_reserved_connections."),
    ("pg-out-of-memory-query", "PostgreSQL Out of memory error",
     "Fix PostgreSQL 'out of memory' error. Resolve memory exhaustion during query execution.",
     "ERROR: out of memory\nDETAIL: Failed on request of size <n>.\n\nThis error occurs when PostgreSQL runs out of memory during query processing."),
    ("pg-disk-full", "PostgreSQL Disk full error",
     "Fix PostgreSQL 'disk full' error. Resolve storage exhaustion issues.",
     "ERROR: could not extend file: No space left on device\n\nThis error occurs when the filesystem containing PostgreSQL data is full."),
    ("pg-cannot-write-to-pmap", "PostgreSQL Cannot write to pg_stat error",
     "Fix PostgreSQL 'cannot write to pg_stat' error. Resolve statistics file system issues.",
     "ERROR: could not open statistics file: Permission denied\n\nThis error occurs when PostgreSQL cannot write to the statistics directory."),
    ("pg-pid-file-error", "PostgreSQL PID file error",
     "Fix PostgreSQL 'PID file' error. Resolve postmaster.pid file issues preventing server start.",
     "FATAL: lock file 'postmaster.pid' already exists\n\nThis error occurs when a stale PID file exists from a previous PostgreSQL instance."),
    ("pg-cannot-lock-data-dir", "PostgreSQL Cannot lock data directory",
     "Fix PostgreSQL 'cannot lock data directory' error. Resolve data directory locking issues.",
     "FATAL: could not create lock file: Permission denied\n\nThis error occurs when PostgreSQL cannot create lock files in the data directory."),
    ("pg-shared-memory", "PostgreSQL Shared memory error",
     "Fix PostgreSQL 'shared memory' error. Resolve shared memory configuration issues.",
     "FATAL: could not create shared memory segment: Cannot allocate memory\n\nThis error occurs when the kernel shared memory limits are too low for PostgreSQL."),
    ("pg-semaphore-error", "PostgreSQL Semaphore error",
     "Fix PostgreSQL 'semaphore' error. Resolve System V semaphore configuration issues.",
     "FATAL: could not create semaphores: No space left on device\n\nThis error occurs when the system semaphore limits are too low for PostgreSQL."),
    ("pg-listen-address", "PostgreSQL Listen address error",
     "Fix PostgreSQL 'listen address' error. Resolve network binding configuration issues.",
     "FATAL: could not bind to address: Cannot assign requested address\n\nThis error occurs when the listen_addresses configuration does not match available network interfaces."),
    ("pg-port-in-use", "PostgreSQL Port in use error",
     "Fix PostgreSQL 'port in use' error. Resolve port binding conflicts.",
     "FATAL: could not bind to address: Address already in use\n\nThis error occurs when another process is already using the PostgreSQL port (default 5432)."),
    ("pg-timezone-not-loaded", "PostgreSQL Timezone not loaded error",
     "Fix PostgreSQL 'timezone not loaded' error. Resolve timezone database loading issues.",
     "ERROR: time zone '<zone>' not recognized\n\nThis error occurs when the timezone data is not loaded or the zone name is incorrect."),
    ("pg-locale-error", "PostgreSQL Locale error",
     "Fix PostgreSQL 'locale' error. Resolve locale configuration issues during database creation.",
     "ERROR: invalid locale name: '<locale>'\n\nThis error occurs when the specified locale is not available on the system."),
    ("pg-encoding-error", "PostgreSQL Encoding mismatch error",
     "Fix PostgreSQL 'encoding mismatch' error. Resolve character encoding issues.",
     "ERROR: encoding <encoding1> does not match locale <locale>\n\nThis error occurs when the database encoding is incompatible with the locale."),
    ("pg-collation-error", "PostgreSQL Collation error",
     "Fix PostgreSQL 'collation' error. Resolve collation creation and usage issues.",
     "ERROR: collation '<name>' is not valid for encoding <encoding>\n\nThis error occurs when a collation is not compatible with the database encoding."),
    ("pg-full-text-search", "PostgreSQL Full text search error",
     "Fix PostgreSQL 'full text search' error. Resolve FTS configuration and query issues.",
     "ERROR: text search configuration '<name>' does not exist\n\nThis error occurs when you reference a non-existent text search configuration."),
    ("pg-ts-dictionary-error", "PostgreSQL Text search dictionary error",
     "Fix PostgreSQL 'text search dictionary' error. Resolve FTS dictionary configuration issues.",
     "ERROR: text search dictionary '<name>' does not exist\n\nThis error occurs when you reference a non-existent text search dictionary."),
    ("pg-ts-parser-error", "PostgreSQL Text search parser error",
     "Fix PostgreSQL 'text search parser' error. Resolve FTS parser configuration issues.",
     "ERROR: text search parser '<name>' does not exist\n\nThis error occurs when you reference a non-existent text search parser."),
    ("pg-ts-template-error", "PostgreSQL Text search template error",
     "Fix PostgreSQL 'text search template' error. Resolve FTS template configuration issues.",
     "ERROR: text search template '<name>' does not exist\n\nThis error occurs when you reference a non-existent text search template."),
    ("pg-jsonb-error", "PostgreSQL JSONB error",
     "Fix PostgreSQL 'JSONB' error. Resolve JSONB data manipulation issues.",
     "ERROR: cannot extract element from a scalar\n\nThis error occurs when you try to extract a field from a JSON scalar value."),
    ("pg-json-path-error", "PostgreSQL JSON path error",
     "Fix PostgreSQL 'JSON path' error. Resolve JSON path query execution issues.",
     "ERROR: jsonpath member accessor can only be applied to an object\n\nThis error occurs when a JSON path expression is applied to the wrong JSON type."),
    ("pg-array-subscript", "PostgreSQL Array subscript error",
     "Fix PostgreSQL 'array subscript' error. Resolve array index out of bounds issues.",
     "ERROR: subscript out of range\n\nThis error occurs when an array index is outside the valid range."),
    ("pg-array-size", "PostgreSQL Array size mismatch error",
     "Fix PostgreSQL 'array size mismatch' error. Resolve array dimension compatibility issues.",
     "ERROR: number of array dimensions <n> does not match the expected <m>\n\nThis error occurs when array dimensions do not match expectations."),
    ("pg-range-error", "PostgreSQL Range type error",
     "Fix PostgreSQL 'range type' error. Resolve range data type manipulation issues.",
     "ERROR: range lower bound must be less than or equal to range upper bound\n\nThis error occurs when a range has a lower bound greater than the upper bound."),
    ("pg-domain-constraint", "PostgreSQL Domain constraint error",
     "Fix PostgreSQL 'domain constraint' error. Resolve domain value constraint violations.",
     "ERROR: value for domain <name> violates check constraint\n\nThis error occurs when a value violates the domain's check constraint."),
    ("pg-assert-statement", "PostgreSQL ASSERT statement error",
     "Fix PostgreSQL 'ASSERT' statement error. Resolve assertion failures in PL/pgSQL.",
     "ERROR: assertion failed\n\nThis error occurs when an ASSERT statement's condition evaluates to false."),
    ("pg-raise-exception", "PostgreSQL RAISE exception error",
     "Fix PostgreSQL 'RAISE' exception error. Resolve PL/pgSQL exception handling issues.",
     "ERROR: <custom error message>\n\nThis error occurs when a RAISE statement with EXCEPTION level is executed."),
    ("pg-permission-deny", "PostgreSQL Permission denied error",
     "Fix PostgreSQL 'permission denied' error. Resolve object permission and privilege issues.",
     "ERROR: permission denied for table <table>\n\nThis error occurs when a user lacks the necessary privileges to access a database object."),
    ("pg-cannot-execute-during-recovery", "PostgreSQL Cannot execute during recovery",
     "Fix PostgreSQL 'cannot execute during recovery' error. Resolve write operation failures on standby servers.",
     "ERROR: cannot execute <command> in a read-only transaction\n\nThis error occurs when you try to execute a write command on a standby server."),
    ("pg-transaction-rollback", "PostgreSQL Transaction rollback error",
     "Fix PostgreSQL 'transaction rollback' error. Resolve serialization and deadlock transaction failures.",
     "ERROR: could not serialize access due to concurrent update\n\nThis error occurs when a serializable transaction cannot complete due to concurrent modifications."),
    ("pg-snapshot-too-old", "PostgreSQL Snapshot too old error",
     "Fix PostgreSQL 'snapshot too old' error. Resolve long-running query issues.",
     "ERROR: snapshot too old\n\nThis error occurs when a query's snapshot is older than old_snapshot_threshold."),
    ("pg-cannot-import-server", "PostgreSQL Cannot import server schema error",
     "Fix PostgreSQL 'cannot import server schema' error. Resolve cross-database schema import issues.",
     "ERROR: cannot create a foreign server with options\n\nThis error occurs when the dblink extension or foreign server import fails."),
    ("pg-copy-error", "PostgreSQL COPY command error",
     "Fix PostgreSQL 'COPY' command error. Resolve bulk data import/export failures.",
     "ERROR: could not open file '<path>' for reading: Permission denied\n\nThis error occurs when PostgreSQL cannot read or write the specified file for COPY operations."),
    ("pg-listen-notify", "PostgreSQL LISTEN/NOTIFY error",
     "Fix PostgreSQL 'LISTEN/NOTIFY' error. Resolve asynchronous notification issues.",
     "ERROR: cannot LISTEN while not in normal query processing\n\nThis error occurs when LISTEN is used in an invalid context."),
    ("pg-prepared-stmt-already-exists", "PostgreSQL Prepared statement exists",
     "Fix PostgreSQL 'prepared statement already exists' error. Resolve duplicate prepared statement names.",
     "ERROR: prepared statement '<name>' already exists\n\nThis error occurs when you try to create a prepared statement with a name that is already in use."),
    ("pg-prepared-stmt-not-found", "PostgreSQL Prepared statement not found",
     "Fix PostgreSQL 'prepared statement does not exist' error. Resolve prepared statement reference failures.",
     "ERROR: prepared statement '<name>' does not exist\n\nThis error occurs when you try to execute a non-existent prepared statement."),
    ("pg-cursor-already-exists", "PostgreSQL Cursor already exists",
     "Fix PostgreSQL 'cursor already exists' error. Resolve duplicate cursor name issues.",
     "ERROR: cursor '<name>' already exists\n\nThis error occurs when you DECLARE a cursor with a name that is already in use."),
    ("pg-cursor-not-found", "PostgreSQL Cursor not found error",
     "Fix PostgreSQL 'cursor does not exist' error. Resolve cursor reference failures.",
     "ERROR: cursor '<name>' does not exist\n\nThis error occurs when you try to FETCH from or CLOSE a non-existent cursor."),
    ("pg-parallel-query-error", "PostgreSQL Parallel query error",
     "Fix PostgreSQL 'parallel query' error. Resolve parallel query execution failures.",
     "ERROR: parallel workers failed to initialize\n\nThis error occurs when PostgreSQL cannot start parallel query workers."),
    ("pg-partition-error", "PostgreSQL Partition error",
     "Fix PostgreSQL 'partition' error. Resolve table partitioning issues.",
     "ERROR: cannot create partition: partitioning key column must be part of the primary key\n\nThis error occurs when the partition key is not part of the primary key."),
    ("pg-partition-bound", "PostgreSQL Partition bound error",
     "Fix PostgreSQL 'partition bound' error. Resolve partition boundary specification issues.",
     "ERROR: every partition bound must be of the same data type\n\nThis error occurs when partition bounds have mismatched types."),
    ("pg-inheritance-error", "PostgreSQL Inheritance error",
     "Fix PostgreSQL 'table inheritance' error. Resolve table inheritance issues.",
     "ERROR: cannot inherit from a temporary relation\n\nThis error occurs when you try to inherit from a temporary table."),
    ("pg-row-security", "PostgreSQL Row-level security error",
     "Fix PostgreSQL 'row-level security' error. Resolve row-level security policy issues.",
     "ERROR: query would be affected by row-level security but table has no policy\n\nThis error occurs when RLS is enabled on a table but no policies are defined."),
    ("pg-force-not-null", "PostgreSQL FORCE NOT NULL error",
     "Fix PostgreSQL 'FORCE NOT NULL' error. Resolve COPY command with NULL handling issues.",
     "ERROR: FORCE NOT NULL column doesn't exist\n\nThis error occurs when a column specified in FORCE NOT NULL does not exist."),
    ("pg-force-null", "PostgreSQL FORCE NULL error",
     "Fix PostgreSQL 'FORCE NULL' error. Resolve COPY command NULL override issues.",
     "ERROR: FORCE NULL column is not a text type column\n\nThis error occurs when FORCE NULL is used on a non-text column."),
    ("pg-convert-error", "PostgreSQL CONVERT error",
     "Fix PostgreSQL 'CONVERT' error. Resolve encoding conversion issues.",
     "ERROR: conversion between <enc1> and <enc2> is not supported\n\nThis error occurs when PostgreSQL does not support the requested encoding conversion."),
    ("pg-default-acl", "PostgreSQL Default privileges error",
     "Fix PostgreSQL 'default privileges' error. Resolve ALTER DEFAULT PRIVILEGES issues.",
     "ERROR: cannot use IN SCHEMA clause when using FOR ROLE\n\nThis error occurs when the FOR ROLE and IN SCHEMA combination is invalid."),
    ("pg-policy-error", "PostgreSQL Policy error",
     "Fix PostgreSQL 'policy' error. Resolve row-level security policy creation issues.",
     "ERROR: policy '<name>' for table '<table>' already exists\n\nThis error occurs when you create a policy with a duplicate name."),
    ("pg-transform-error", "PostgreSQL Transform error",
     "Fix PostgreSQL 'transform' error. Resolve type transform creation issues.",
     "ERROR: transform for type <type> already exists\n\nThis error occurs when you create a transform for a type that already has one."),
    ("pg-operator-error", "PostgreSQL Operator error",
     "Fix PostgreSQL 'operator' error. Resolve custom operator issues.",
     "ERROR: operator does not exist: <type1> <op> <type2>\n\nThis error occurs when the specified operator is not defined for the operand types."),
    ("pg-aggregate-error", "PostgreSQL Aggregate error",
     "Fix PostgreSQL 'aggregate' error. Resolve custom aggregate function issues.",
     "ERROR: aggregate '<name>' does not exist\n\nThis error occurs when you reference a non-existent aggregate function."),
    ("pg-opfamily-error", "PostgreSQL Operator family error",
     "Fix PostgreSQL 'operator family' error. Resolve operator family index issues.",
     "ERROR: operator family '<name>' does not exist\n\nThis error occurs when you reference a non-existent operator family."),
    ("pg-opclass-error", "PostgreSQL Operator class error",
     "Fix PostgreSQL 'operator class' error. Resolve operator class index issues.",
     "ERROR: operator class '<name>' does not exist for access method '<method>'\n\nThis error occurs when the operator class is not valid for the access method."),
    ("pg-access-method-error", "PostgreSQL Access method error",
     "Fix PostgreSQL 'access method' error. Resolve index access method issues.",
     "ERROR: access method '<name>' does not exist\n\nThis error occurs when you reference a non-existent index access method."),
]

def make_pg_page(slug, title, desc, body):
    lines = [
        '---',
        f'title: "[Solution] {title}"',
        f'description: "{desc}"',
        'tools: ["postgresql"]',
        'error-types: ["tool-error"]',
        'severities: ["error"]',
        'weight: 5',
        '---',
        '',
        f'# {title}',
        '',
        body,
        '',
        '## How to Fix',
        '',
        '### Check PostgreSQL Status',
        '',
        '```bash',
        'sudo systemctl status postgresql',
        'pg_isready',
        '```',
        '',
        '### Check PostgreSQL Logs',
        '',
        '```bash',
        'sudo tail -100 /var/log/postgresql/postgresql-*-main.log',
        '```',
        '',
        '### Verify pg_hba.conf',
        '',
        '```bash',
        'sudo cat /etc/postgresql/*/main/pg_hba.conf',
        '```',
        '',
        '## Related Errors',
        '',
        '- [Connection Refused]({{< relref "/tools/postgresql/pg-connection-refused" >}}) — server unreachable',
        '- [Database Does Not Exist]({{< relref "/tools/postgresql/pg-database-does-not-exist" >}}) — missing database',
        '',
    ]
    return '\n'.join(lines)

count = 0
for slug, title, desc, body in PAGES_DATA:
    if slug in EXISTING:
        print(f"SKIP (exists): {slug}")
        continue
    content = make_pg_page(slug, title, desc, body)
    path = f"/home/admin1/projects/ErrorCode.excellentwiki.com/content/tools/postgresql/{slug}.md"
    with open(path, 'w') as f:
        f.write(content)
    count += 1
    print(f"CREATED: {slug}")

print(f"\nTotal created: {count}")
print(f"Total skipped (existing): {len(PAGES_DATA) - count}")
